# Batch 12: standalone statements, same short/direct style as batch 11
# (single-claim, no long sentence with one word swapped), but mixed
# true/false this time (12/12) rather than all-false, to keep the bank's
# overall true/false balance from drifting too far after an all-false batch.

ENTRIES = [
    ("language", "'Hallelujah' comes from Hebrew and literally means something like 'praise God.'", True,
     "'Hallelujah' combines 'halelu' (praise) and 'Yah' (a name for God)."),
    ("language", "'Amen,' used across Judaism, Christianity, and Islam, comes from a Hebrew word meaning something like 'truth' or 'so be it.'", True,
     "'Amen' derives from a Hebrew root related to truth and certainty, and is shared across all three Abrahamic religions."),
    ("ritual_objects", "A shofar is traditionally never made from the horn of a cow, due to its association with the biblical Golden Calf.", True,
     "Tradition specifically avoids cow horns for a shofar because of their association with the Golden Calf story."),
    ("history", "Jerusalem has been ruled by many different empires over the centuries, including Roman, Byzantine, and Ottoman rule.", True,
     "Jerusalem's history includes long periods under Roman, Byzantine, Ottoman, and other rule, among many others."),
    ("food", "Lox, thinly sliced cured salmon, is a classic topping for bagels in Ashkenazi Jewish-American cuisine.", True,
     "Lox and bagels is a well-known Ashkenazi Jewish-American culinary tradition, especially associated with New York."),
    ("symbols", "A hamsa is shaped like an open hand and is traditionally believed by many to offer protection.", True,
     "The hamsa's open-hand shape is traditionally associated with protection in Jewish and several other regional traditions."),
    ("kashrut", "Kosher law traditionally forbids eating an animal that died of natural causes, even if the species itself is otherwise kosher.", True,
     "An animal that died on its own (nevelah), rather than through proper slaughter, is not kosher even if the species normally is."),
    ("texts", "Ecclesiastes, a book in the Hebrew Bible, includes the well-known line 'To every thing there is a season.'", True,
     "That line opens a famous passage in Ecclesiastes (chapter 3), part of the Hebrew Bible's Writings section."),
    ("language", "The Hebrew calendar counts years from a traditional calculation of the world's creation, making current Hebrew years in the 5000s.", True,
     "The Hebrew calendar's year count is based on a traditional creation-dating system, putting current years well into the 5000s."),
    ("food", "Matzah ball soup, made with unleavened dumplings in chicken broth, is a traditional Ashkenazi comfort food, especially around Passover.", True,
     "Matzah ball soup is a well-known traditional Ashkenazi dish, particularly associated with Passover."),
    ("prayer", "Many Jewish prayers are structured as call-and-response, with a leader reciting a line and the congregation responding.", True,
     "Call-and-response is a common traditional structure in Jewish liturgy, such as in the Kaddish and Kedusha."),
    ("kashrut", "A traditionally kosher-certified restaurant will not serve both meat dishes and dairy dishes at the same time.", True,
     "A kosher-certified restaurant is generally designated as meat, dairy, or pareve, not a mix of meat and dairy together."),

    ("kashrut", "Kosher certification allows a restaurant to serve pork as long as it's prepared separately from other dishes.", False,
     "Pork is never kosher, regardless of how it's prepared or separated from other food."),
    ("holidays", "Yom Kippur is traditionally celebrated with a large family feast at midday.", False,
     "Yom Kippur is a fast day; eating and drinking are traditionally avoided, not featured in a midday feast."),
    ("lifecycle", "A Jewish wedding ceremony traditionally lasts several hours, similar to a full-day event.", False,
     "The ceremony itself is traditionally brief, often around 20-30 minutes, though celebrations afterward may last longer."),
    ("ritual_objects", "A mezuzah case must always be made of gold to be considered valid.", False,
     "A mezuzah case can be made of many materials — what matters religiously is the scroll inside, not the case's material."),
    ("prayer", "Jewish prayer services traditionally last only a few minutes, similar to a quick daily check-in.", False,
     "Traditional services, especially on Shabbat and holidays, often run considerably longer than a few minutes."),
    ("kashrut", "Kosher wine can only be red wine; white and rosé wine cannot be kosher.", False,
     "Kosher status isn't tied to wine color — white and rosé wines can be kosher just as red wines can."),
    ("holidays", "Sukkot is a one-day holiday observed only in Israel.", False,
     "Sukkot is a multi-day holiday observed by Jewish communities worldwide, not a single day limited to Israel."),
    ("diaspora", "There is a single unified form of Judaism practiced identically by all Jewish communities worldwide, with no regional variation.", False,
     "Jewish practice includes real regional and denominational variation across different communities worldwide."),
    ("lifecycle", "Jewish funerals traditionally include an open casket viewing as a central part of the ceremony.", False,
     "Traditional Jewish funerals generally use a closed casket; open casket viewing isn't customary practice."),
    ("language", "The word 'kibbutz' refers to a type of Jewish prayer book.", False,
     "A kibbutz is a collective community or settlement, not a prayer book."),
    ("texts", "The Zohar is the primary legal code used to determine Jewish dietary laws.", False,
     "The Zohar is a foundational mystical (Kabbalistic) text; the Shulchan Aruch is the widely referenced legal code."),
    ("ritual_objects", "A tallit is traditionally worn only by rabbis, never by ordinary congregants.", False,
     "A tallit is traditionally worn by congregants generally, not reserved exclusively for rabbis."),
]
