# Batch 7: ~47 new true/false pairs. Two-thirds of this batch is a new
# "diaspora" category covering country- and region-specific Jewish customs
# (Yemenite, Ethiopian, Persian, Bukharan, Georgian, Indian, Moroccan,
# Syrian, Iraqi, Italian, German, Litvak, Chinese, French, Karaite, Libyan,
# Greek, Dutch, Algerian, and general Ashkenazi origins). The rest continues
# the general laws/customs emphasis (prayer, holidays, shabbat, texts,
# history, language).

PAIRS = [
    # --- diaspora: regional and country-specific customs ---
    ("diaspora",
     "Yemenite Jewish tradition preserves a distinctive Hebrew pronunciation, including sound distinctions not maintained in many other Jewish traditions.",
     "Yemenite Jewish tradition uses the exact same Hebrew pronunciation as every other Jewish community worldwide, with no distinguishing features.",
     "Yemenite Hebrew pronunciation is well known among linguists for preserving distinctions that other traditions have lost over time."),
    ("diaspora",
     "Traditional Yemenite Jewish wedding customs include the bride wearing an elaborate, heavily decorated traditional headdress and jewelry.",
     "Traditional Yemenite Jewish wedding customs include the bride shaving her head completely before the ceremony.",
     "Elaborate traditional headdress and jewelry, not head-shaving, is the well-documented Yemenite Jewish bridal custom."),
    ("diaspora",
     "Yemenite Jewish tradition has historically maintained especially close adherence to Maimonides' legal rulings, more so than many other communities.",
     "Yemenite Jewish tradition has historically rejected Maimonides' rulings entirely, following a completely separate legal authority.",
     "Yemenite Jews are especially well known among scholars for closely following Maimonides' Mishneh Torah as their primary legal guide."),
    ("diaspora",
     "Ethiopian Jewish tradition, among the Beta Israel community, developed with limited early contact with rabbinic Judaism elsewhere, basing practice primarily on the Torah rather than the Talmud.",
     "Ethiopian Jewish tradition developed in constant close contact with rabbinic authorities in Babylon and Europe, closely mirroring Talmudic practice from an early period.",
     "Beta Israel's relative isolation and Torah-centered practice, without Talmudic influence, is a well-documented distinguishing feature of the community."),
    ("diaspora",
     "The Ethiopian Jewish community traditionally observes a unique holiday called Sigd, about 50 days after Yom Kippur, renewing the covenant and expressing longing for Jerusalem.",
     "The Ethiopian Jewish community traditionally observes a unique holiday called Sigd, celebrated the same week as Hanukkah and focused on lighting candles.",
     "Sigd falls roughly 50 days after Yom Kippur and centers on covenant renewal, not a Hanukkah-adjacent candle-lighting custom."),
    ("diaspora",
     "Ethiopian Jewish religious leaders are traditionally called Kessim (or Kes), a distinct title from rabbis elsewhere.",
     "Ethiopian Jewish religious leaders are traditionally called Gaon, a term historically used for heads of medieval Babylonian academies.",
     "Kes/Kessim is the traditional Ethiopian Jewish religious leadership title, distinct from the historical Babylonian 'Gaon.'"),
    ("diaspora",
     "Persian (Iranian) Jewish communities trace their presence in the region back over 2,500 years, among the oldest Jewish diaspora communities in the world.",
     "Persian Jewish communities trace their presence in the region back only to the 20th century, following a mid-century wave of immigration.",
     "Persian Jewish history goes back millennia, tied to the ancient Achaemenid period, not a 20th-century arrival."),
    ("diaspora",
     "Iranian Jewish communities have historically maintained a site traditionally associated with the graves of Esther and Mordechai, from the biblical Book of Esther.",
     "Iranian Jewish communities have no historical connection to the story or setting of the Book of Esther.",
     "A traditional tomb site associated with Esther and Mordechai has long been maintained in Iran, reflecting the story's Persian setting."),
    ("diaspora",
     "Bukharan Jews, historically from Central Asia, developed a distinct Judeo-Tajik language blending Tajik/Persian with Hebrew elements.",
     "Bukharan Jews, historically from Central Asia, spoke only standard Modern Hebrew, with no distinct regional language of their own.",
     "Bukharan Jews developed their own distinct language (Bukhori), not simply standard Hebrew."),
    ("diaspora",
     "Since the late 20th century, most Bukharan Jews have emigrated from Central Asia, with large communities now established in Israel and the New York City area.",
     "Since the late 20th century, the Bukharan Jewish community has grown dramatically within Central Asia itself, becoming one of the region's largest religious groups.",
     "Large-scale emigration, not growth within Central Asia, has defined the Bukharan Jewish community's recent history."),
    ("diaspora",
     "Georgian Jews, one of the oldest diaspora communities, trace their presence in the Caucasus region back over 2,000 years.",
     "Georgian Jews are a community that formed entirely in the 20th century, with no historical presence in the region before then.",
     "Georgian Jewish presence in the Caucasus is traditionally dated back over two millennia, not to the 20th century."),
    ("diaspora",
     "India has historically been home to several distinct Jewish communities, including the Cochin Jews, Bene Israel, and Baghdadi Jews, each with its own history and customs.",
     "India has historically been home to a single unified Jewish community, with no distinction between different groups or regions.",
     "India's Jewish population has genuinely included several historically distinct communities, not one uniform group."),
    ("diaspora",
     "The Bene Israel community of India traditionally maintained core Jewish practices like Shabbat and dietary laws for centuries with limited outside contact, later reconnecting with other Jewish communities.",
     "The Bene Israel community of India arrived only in the 20th century as refugees from Europe, with no older historical presence in the region.",
     "Bene Israel tradition holds a much older presence in India, with practices preserved over centuries before renewed outside contact."),
    ("diaspora",
     "Cochin Jews in Kerala, India, historically maintained their own distinct synagogues, including the Paradesi Synagogue, dating to the 16th century.",
     "Cochin Jews in Kerala, India, have no historical synagogues, having always worshipped exclusively in private homes.",
     "The Paradesi Synagogue, built in the 16th century, is a well-documented historic Cochin Jewish synagogue, still standing today."),
    ("diaspora",
     "Moroccan Jewish tradition includes a distinctive post-Passover celebration called Mimouna, marking the end of the holiday's dietary restrictions with a festive gathering.",
     "Moroccan Jewish tradition includes a distinctive pre-Passover celebration called Mimouna, marking the beginning of the holiday's dietary restrictions with a solemn fast.",
     "Mimouna is a festive celebration held right after Passover ends, not a solemn fast beforehand."),
    ("diaspora",
     "Traditional Mimouna celebrations often feature a table decorated with symbols of luck and prosperity, such as flour, honey, and gold jewelry.",
     "Traditional Mimouna celebrations traditionally involve fasting from sundown to sundown, with no food served at all.",
     "Mimouna is a festive, food-centered celebration with symbolic decorations, not a fast day."),
    ("diaspora",
     "The Syrian Jewish community historically centered in cities like Aleppo and Damascus, with the Aleppo community once safeguarding an ancient, important manuscript of the Hebrew Bible called the Aleppo Codex.",
     "The Syrian Jewish community historically centered in cities like Aleppo and Damascus, and was responsible for creating the standardized printed Talmud page layout still used today.",
     "The Aleppo community's historic role was safeguarding the Aleppo Codex; the standard Talmud page layout instead traces to 16th-century Venice."),
    ("diaspora",
     "Syrian Jewish tradition historically maintained distinct communal enactments (takanot), including a well-known 20th-century policy discouraging conversion into the community.",
     "Syrian Jewish tradition has historically been unusually welcoming to converts, with a formal policy actively encouraging conversion into the community.",
     "Syrian Jewish communal leadership historically enacted a well-documented policy discouraging, not encouraging, conversion into the community."),
    ("diaspora",
     "Iraqi Jewish history traces back to the Babylonian exile over 2,500 years ago, making it one of the oldest continuous Jewish communities before its near-total emigration in the 20th century.",
     "Iraqi Jewish history began only in the 19th century with Ottoman-era immigration, with no earlier historical presence.",
     "Iraqi Jewish history is traditionally traced back millennia to the Babylonian exile, not just the 19th century."),
    ("diaspora",
     "The city of Baghdad was historically home to a large and influential Jewish community, which had largely emigrated, mainly to Israel, by the mid-20th century.",
     "The city of Baghdad has never had a significant Jewish community at any point in its history.",
     "Baghdad's large historic Jewish community is well documented, with most emigrating around the mid-20th century."),
    ("diaspora",
     "Italian Jewish communities maintain one of the oldest continuous Jewish presences in Europe, with a distinct liturgical tradition (the Italian rite) separate from both Ashkenazi and Sephardic custom.",
     "Italian Jewish communities follow the exact same liturgical tradition as either the Ashkenazi or Sephardic rite, with no distinct tradition of their own.",
     "The Italian rite is a genuinely separate liturgical tradition, distinct from both the Ashkenazi and Sephardic rites most people are familiar with."),
    ("diaspora",
     "German Jews are sometimes informally called 'Yekkes,' a nickname whose exact origin is debated but often associated with a reputation for formality and punctuality.",
     "German Jews are sometimes informally called 'Yekkes,' a term originally referring to their historical role as vintners in the Rhineland wine industry.",
     "'Yekke' is a cultural nickname tied to a reputation for formality, with a debated origin — not a wine-industry occupational term."),
    ("diaspora",
     "Litvak, referring to Lithuanian Jewish tradition, is historically associated with an emphasis on rigorous Talmudic scholarship and a more rationalist approach, distinct from some Hasidic traditions.",
     "Litvak, referring to Lithuanian Jewish tradition, is historically associated with founding the Hasidic movement itself.",
     "Litvak tradition (the Mitnagdim) is historically distinguished from, not the founder of, the Hasidic movement."),
    ("diaspora",
     "Kaifeng, China was historically home to a small Jewish community dating back roughly a thousand years, with a synagogue that no longer stands today.",
     "Kaifeng, China has been home to one of the world's largest Jewish communities for the past thousand years, with a synagogue larger than any in Europe.",
     "Kaifeng's historic Jewish community was small, and its old synagogue no longer stands, contrary to claims of being one of the world's largest."),
    ("diaspora",
     "France is home to one of the largest Jewish communities in Europe today, shaped significantly by 20th-century immigration from North Africa.",
     "France's Jewish community today is composed almost entirely of families who have lived continuously in France since Roman times, with negligible 20th-century immigration.",
     "Modern French Jewry was significantly shaped by North African immigration in the 20th century, particularly after several countries' independence."),
    ("diaspora",
     "Karaite Judaism is a distinct branch that traditionally rejects rabbinic and Talmudic authority, basing practice directly on the Hebrew Bible instead.",
     "Karaite Judaism is simply another name for Reform Judaism, founded in 19th-century Germany.",
     "Karaite Judaism is a much older, separate tradition defined by rejecting rabbinic authority, distinct from the modern Reform movement."),
    ("diaspora",
     "The Tunisian island of Djerba is home to the El Ghriba Synagogue, one of the oldest synagogues in Africa and an annual pilgrimage destination.",
     "The Tunisian island of Djerba is home to the El Ghriba Synagogue, built in the 1990s as a modern tourist attraction with no older history.",
     "El Ghriba is a genuinely ancient synagogue and long-standing pilgrimage site, not a recent construction."),
    ("diaspora",
     "Yemenite Jews were historically renowned as skilled silversmiths in Yemen, producing intricate jewelry and ceremonial items.",
     "Yemenite Jews were historically forbidden from working with metals, restricted only to agricultural labor in Yemen.",
     "Yemenite Jewish silversmithing is a well-documented, celebrated historical craft tradition, not a restriction to agricultural work."),
    ("diaspora",
     "Moroccan Jewish tradition includes hillulot, pilgrimage celebrations at the tombs of revered rabbis, particularly widespread in Morocco.",
     "Moroccan Jewish tradition specifically forbids visiting the graves of deceased rabbis, treating such visits as a violation of Jewish law.",
     "Pilgrimage to rabbis' tombs (hillulot) is a well-documented, widespread Moroccan Jewish custom, not a forbidden practice."),
    ("diaspora",
     "Some Indian Jewish communities, such as the Bene Israel, historically abstained from eating beef out of respect for local custom, in addition to following standard kosher dietary laws.",
     "Indian Jewish communities historically ignored all standard kosher dietary laws, eating any food freely available regardless of Jewish tradition.",
     "Indian Jewish communities are documented as adapting local customs like beef avoidance on top of, not instead of, standard kosher practice."),
    ("diaspora",
     "Algerian Jews were granted French citizenship collectively in 1870 under the Crémieux Decree, a distinct historical event in Algerian Jewish history.",
     "Algerian Jews were granted Ottoman citizenship collectively in 1870 under the Crémieux Decree, a distinct historical event in Algerian Jewish history.",
     "The Crémieux Decree specifically granted French citizenship, reflecting France's colonial rule over Algeria, not Ottoman citizenship."),
    ("diaspora",
     "Israel's population includes Jews from dozens of different countries of origin, each historically bringing distinct customs, liturgical traditions, and cuisines still practiced today.",
     "Israel's population is composed of Jews from only two countries of origin, with all other diaspora customs having fully disappeared since 1948.",
     "Israel's Jewish population is famously diverse in origin, with many distinct diaspora traditions still actively practiced, not reduced to just two."),
    ("diaspora",
     "Kurdish Jews, historically living across mountainous parts of Iraq, Iran, Turkey, and Syria, traditionally spoke forms of Aramaic rather than Arabic.",
     "Kurdish Jews historically spoke a form of Mandarin Chinese as their vernacular language, brought by ancient trade routes.",
     "Kurdish Jewish communities were among the last groups to speak Aramaic as an everyday vernacular language, not Mandarin."),
    ("diaspora",
     "Libyan Jews, historically concentrated in Tripoli, developed distinct customs and largely emigrated following persecution and violence in the mid-20th century, mainly to Israel and Italy.",
     "Libyan Jews historically remained a large, stable community throughout the 20th century, with most still living in Libya today.",
     "Libyan Jewish emigration in the mid-20th century was extensive, not a case of the community remaining large and stable in Libya."),
    ("diaspora",
     "The Jewish community of Salonika (Thessaloniki), Greece, became a major center of Sephardic Jewish life and Ladino culture after Jews expelled from Spain resettled there under Ottoman rule.",
     "The Jewish community of Salonika, Greece, was historically a major center of Ashkenazi Jewish life, having relocated there from Germany in the 19th century.",
     "Salonika's historic Jewish community was overwhelmingly Sephardic, tracing to the Spanish expulsion, not a 19th-century Ashkenazi relocation."),
    ("diaspora",
     "Amsterdam is historically home to a notable Jewish community of Portuguese and Spanish origin, whose 17th-century Portuguese Synagogue remains a landmark today.",
     "Amsterdam is historically home to a notable Jewish community of Portuguese and Spanish origin, whose Portuguese Synagogue was demolished in the 19th century and never rebuilt.",
     "Amsterdam's Portuguese Synagogue, built in the 17th century, still stands and remains in use today, rather than having been demolished."),
    ("diaspora",
     "Ashkenazi Jewish communities historically developed in the Rhineland region of medieval Germany before spreading eastward into Poland, Lithuania, and Russia.",
     "Ashkenazi Jewish communities historically developed in North Africa before spreading into Western Europe.",
     "'Ashkenaz' traditionally refers to the medieval German Rhineland, the historical origin point before eastward migration, not North Africa."),

    # --- general laws/customs and related facts ---
    ("prayer",
     "Jewish tradition includes different blessings depending on the type of food, such as HaEtz for fruit grown on trees and Ha'adama for vegetables grown from the ground.",
     "Jewish tradition uses exactly one blessing for all food and drink, regardless of type.",
     "Traditional practice distinguishes blessings by food category, rather than using a single universal blessing."),
    ("holidays",
     "Rosh Hashanah is traditionally celebrated for two days even within Israel itself, unlike most other holidays, which are one day in Israel.",
     "Rosh Hashanah is traditionally celebrated for only one day everywhere, including outside Israel, unlike most other holidays.",
     "Rosh Hashanah is a notable exception to the usual Israel/diaspora day-length pattern, observed for two days even in Israel."),
    ("prayer",
     "Borei Nefashot is a shorter after-blessing traditionally recited following foods that don't require the full Birkat HaMazon.",
     "Borei Nefashot is a blessing traditionally recited only during the Passover seder, unrelated to everyday eating.",
     "Borei Nefashot is a general everyday after-blessing for many foods, not a Passover-specific prayer."),
    ("shabbat",
     "At least two Shabbat candles are traditionally lit, though some households light an additional candle for each child in the family.",
     "Exactly seven Shabbat candles must always be lit, regardless of family size or custom.",
     "The traditional minimum is two candles, with some families adding more per child, not a fixed requirement of seven."),
    ("texts",
     "Aggadah refers to the narrative, homiletical, and non-legal portions of rabbinic literature, distinct from halakha's legal material.",
     "Aggadah is simply another word for halakha, referring to the same legal material under a different name.",
     "Aggadah and halakha are distinct categories of rabbinic literature — narrative/homiletical versus legal."),
    ("history",
     "The Balfour Declaration of 1917 was a British statement expressing support for a Jewish homeland in Palestine.",
     "The Balfour Declaration of 1917 was a French statement expressing opposition to any Jewish presence in Palestine.",
     "The Balfour Declaration was issued by the British government and expressed support, not opposition, for a Jewish homeland."),
    ("language",
     "'Aliyah,' the term for immigration to Israel, literally means 'ascent,' sharing its root with the word for being called up to the Torah.",
     "'Aliyah,' the term for immigration to Israel, literally means 'departure,' unrelated to the word for being called up to the Torah.",
     "Both uses of 'aliyah' — immigration and the Torah call-up — share the same root meaning 'ascent' or 'going up.'"),
    ("prayer",
     "Al HaNissim is a special prayer insert added to daily prayers and Birkat HaMazon during Hanukkah and Purim, giving thanks for those holidays' miracles.",
     "Al HaNissim is a special prayer insert added to daily prayers only during Passover, giving thanks for the miracle of the Exodus.",
     "Al HaNissim is specifically tied to Hanukkah and Purim, not Passover."),
    ("history",
     "The term 'ghetto' originated in 16th-century Venice, referring to the segregated quarter where Jewish residents were required to live.",
     "The term 'ghetto' originated in 20th-century America, coined by urban planners with no connection to Jewish history.",
     "'Ghetto' traces back to Venice's Jewish quarter in the 1500s, centuries before its later, broader use."),
    ("language",
     "'Shalom,' commonly translated as 'hello,' 'goodbye,' or 'peace,' shares its root with the Hebrew word for 'whole' or 'complete.'",
     "'Shalom' shares its root with the Hebrew word for 'war,' reflecting an ancient blessing for victory in conflict.",
     "'Shalom' is rooted in a word meaning wholeness or completeness, not war."),
]
