# Batch 16: further Yiddish words, origins, and language-culture facts.
# Genuinely well-documented, non-obscure loanwords are a finite set — this
# batch pushes further than batch 14 but deliberately stops short of padding
# with shaky or overly obscure claims just to hit a round number.

PAIRS = [
    ("language",
     "The Yiddish-derived word 'schmutz,' used in English, means dirt, grime, or a smudge.",
     "The Yiddish-derived word 'schmutz,' used in English, means a lavish, formal banquet.",
     "Schmutz refers to dirt or grime, not a type of meal.",
     2),
    ("language",
     "The Yiddish-derived word 'schnorrer,' used in English, describes a moocher who persistently asks for or expects things for free.",
     "The Yiddish-derived word 'schnorrer,' used in English, describes an exceptionally generous host.",
     "A schnorrer is a freeloader or moocher, the opposite of a generous giver.",
     3),
    ("language",
     "The Yiddish-derived word 'kibitz,' used in English, means to offer unsolicited advice or chat idly while others are working or playing.",
     "The Yiddish-derived word 'kibitz,' used in English, means to work silently without any conversation.",
     "To kibitz is to chatter or offer commentary, not to stay silent.",
     3),
    ("language",
     "The Yiddish-derived word 'plotz,' used in English, means to collapse or practically explode from strong emotion, like excitement or exasperation.",
     "The Yiddish-derived word 'plotz,' used in English, means to fall asleep peacefully.",
     "To plotz is to be overwhelmed by strong emotion, not to doze off calmly.",
     3),
    ("language",
     "The Yiddish-derived word 'bubkes' (or bupkis), used in English, means absolutely nothing.",
     "The Yiddish-derived word 'bubkes' (or bupkis), used in English, means an enormous amount of something.",
     "Bubkes means nothing at all — the opposite of an enormous amount.",
     2),
    ("language",
     "The Yiddish-derived word 'gonif,' used in English, describes a thief or a dishonest, crooked person.",
     "The Yiddish-derived word 'gonif,' used in English, describes a trusted family accountant.",
     "A gonif is a thief or crook, not a trusted professional.",
     3),
    ("language",
     "The Yiddish-derived word 'mishegoss,' used in English, means craziness or chaotic nonsense.",
     "The Yiddish-derived word 'mishegoss,' used in English, means a peaceful, orderly routine.",
     "Mishegoss describes chaos or craziness, the opposite of calm order.",
     3),
    ("language",
     "The Yiddish-derived word 'zaftig,' used in English, describes someone pleasantly plump or curvaceous.",
     "The Yiddish-derived word 'zaftig,' used in English, describes someone extremely tall and thin.",
     "Zaftig describes a pleasantly full-figured build, not a tall, thin one.",
     3),
    ("language",
     "The Yiddish-derived word 'tsuris,' used in English, means troubles, worries, or grief.",
     "The Yiddish-derived word 'tsuris,' used in English, means a joyful celebration.",
     "Tsuris refers to troubles or grief, the opposite of celebration.",
     3),
    ("language",
     "The Yiddish word 'meshuggeneh' describes a crazy or foolish person.",
     "The Yiddish word 'meshuggeneh' describes a highly respected judge or elder.",
     "A meshuggeneh is someone acting crazy or foolish, not a respected authority figure.",
     2),
    ("language",
     "The Yiddish-derived word 'yutz,' used in English, describes a foolish, inept person.",
     "The Yiddish-derived word 'yutz,' used in English, describes a brilliant strategist.",
     "A yutz is a foolish or clumsy person, not a brilliant strategist.",
     3),
    ("language",
     "The Yiddish-derived word 'shpilkes,' used in English, describes restless, nervous energy or impatience.",
     "The Yiddish-derived word 'shpilkes,' used in English, describes a state of deep, calm relaxation.",
     "Shpilkes describes restless impatience, sometimes likened to 'ants in one's pants' — not relaxation.",
     3),
    ("language",
     "The Yiddish-derived word 'shvitz,' used in English, means to sweat, and can also refer to a steam bath.",
     "The Yiddish-derived word 'shvitz,' used in English, means to shiver from the cold.",
     "Shvitz relates to sweating and heat, not shivering from cold.",
     2),
    ("language",
     "The Yiddish-derived word 'tush' (or tuchus), used in English, is an informal term for one's backside.",
     "The Yiddish-derived word 'tush' (or tuchus), used in English, is an informal term for one's elbow.",
     "Tush/tuchus refers to the backside, not the elbow.",
     1),
    ("language",
     "On its own, the Yiddish/Hebrew-derived word 'mazel' simply means 'luck' — the phrase 'mazel tov' literally combines it with 'tov' (good).",
     "On its own, the Yiddish/Hebrew-derived word 'mazel' means 'family,' unrelated to luck.",
     "Mazel means luck; mazel tov literally means 'good luck,' used to say congratulations.",
     3),
    ("language",
     "The Yiddish-derived word 'schmear,' used in English, means a generous spread of something, as in a bagel with a schmear of cream cheese.",
     "The Yiddish-derived word 'schmear,' used in English, means a thin, barely-there layer of something.",
     "A schmear implies a generous, thick spread, not a thin layer.",
     2),
    ("language",
     "The word 'Yiddish' itself comes from the Yiddish word for 'Jewish.'",
     "The word 'Yiddish' itself comes from a German word meaning 'ancient.'",
     "Yiddish (Yidish) literally means 'Jewish' in the language itself.",
     2),
    ("language",
     "Even though Yiddish is written in the Hebrew alphabet, its core grammar and vocabulary are fundamentally Germanic, making it more closely related to German than to Hebrew.",
     "Because Yiddish is written in the Hebrew alphabet, its grammar is fundamentally Hebraic, making it more closely related to Hebrew than to German.",
     "Yiddish is classified as a Germanic language grammatically, despite being written with Hebrew letters.",
     4),
    ("language",
     "The blending of Yiddish and English vocabulary and speech patterns is sometimes called 'Yinglish.'",
     "The blending of Yiddish and English vocabulary and speech patterns is sometimes called 'Hebrenglish.'",
     "'Yinglish' is the established term for this blend of Yiddish and English.",
     3),
    ("language",
     "'The Joys of Yiddish,' a popular reference book explaining Yiddish words and their meanings, was written by Leo Rosten.",
     "'The Joys of Yiddish,' a popular reference book explaining Yiddish words and their meanings, was written by Isaac Bashevis Singer.",
     "Leo Rosten wrote The Joys of Yiddish (1968); Isaac Bashevis Singer was a Yiddish-language novelist, not this book's author.",
     4),
    ("language",
     "Isaac Bashevis Singer, who wrote primarily in Yiddish, won the Nobel Prize in Literature in 1978.",
     "Isaac Bashevis Singer, who wrote primarily in Yiddish, won the Nobel Peace Prize in 1978.",
     "Singer won the Nobel Prize in Literature, not the Peace Prize.",
     3),
    ("language",
     "The Forward (Forverts), a historically influential Yiddish-language newspaper founded in New York, once had enormous daily circulation among Jewish immigrants.",
     "The Forward (Forverts), a historically influential Yiddish-language newspaper, was founded in Warsaw and never published in the United States.",
     "The Forward was founded in New York in 1897 and became a major American Yiddish paper.",
     4),
    ("language",
     "The YIVO Institute for Jewish Research, based in New York, developed a widely used standard system for spelling and transliterating Yiddish.",
     "The YIVO Institute for Jewish Research, based in New York, is primarily a kosher food certification agency.",
     "YIVO is a research and cultural institution best known for Yiddish scholarship and standardized spelling, not food certification.",
     5),
    ("language",
     "Many Yiddish words entered mainstream American English partly through mid-20th-century 'Borscht Belt' comedians performing in the Catskills.",
     "Yiddish words entered mainstream American English exclusively through academic linguistics textbooks, with no connection to comedy or entertainment.",
     "Borscht Belt comedians were a major, well-documented route by which Yiddish vocabulary spread into everyday American English.",
     4),
    ("language",
     "The classic illustrative example of 'chutzpah' often cited is a child who kills his parents and then begs the court for mercy as an orphan.",
     "The classic illustrative example of 'chutzpah' often cited is a student who studies for months before an exam.",
     "This darkly comic illustration of shameless audacity is a widely cited example of chutzpah, popularized by writers like Leo Rosten.",
     3),
    ("language",
     "'Klezmer,' the term for a traditional Eastern European Jewish instrumental music style, comes from Hebrew words meaning 'vessels of song.'",
     "'Klezmer,' the term for a traditional Eastern European Jewish instrumental music style, comes from a Yiddish word meaning 'silence.'",
     "Klezmer derives from Hebrew 'kli zemer,' literally 'vessel(s) of song,' referring to musical instruments or musicians.",
     4),
]
