# Batch 17: further Jewish pop culture — comedians, musicians, actors,
# directors, comic-book creators, athletes, Broadway composers, film/TV,
# and food-culture crossover facts.

PAIRS = [
    ("pop_culture",
     "Mel Brooks created and starred in 'The Producers,' a comedy about a fraudulent Broadway musical.",
     "Mel Brooks created and starred in 'The Producers,' a serious historical war drama.",
     "The Producers is one of Mel Brooks's best-known comedies, not a drama.",
     2),
    ("pop_culture",
     "Jerry Seinfeld co-created and starred in the sitcom 'Seinfeld,' famously described as 'a show about nothing.'",
     "Jerry Seinfeld co-created and starred in the sitcom 'Seinfeld,' a courtroom drama set in Chicago.",
     "Seinfeld is a sitcom set in New York City, not a courtroom drama.",
     1),
    ("pop_culture",
     "Larry David, co-creator of 'Seinfeld,' also created and stars in 'Curb Your Enthusiasm.'",
     "Larry David, co-creator of 'Seinfeld,' also created and stars in a long-running Saturday morning cartoon.",
     "Larry David's other major show, Curb Your Enthusiasm, is a live-action comedy, not a cartoon.",
     2),
    ("pop_culture",
     "Joan Rivers was a trailblazing stand-up comedian known for her sharp, irreverent humor over a decades-long career.",
     "Joan Rivers was primarily known as a classical opera singer, not a comedian.",
     "Joan Rivers built her career as a stand-up comedian and TV host.",
     2),
    ("pop_culture",
     "Billy Crystal has hosted the Academy Awards ceremony multiple times.",
     "Billy Crystal has never hosted the Academy Awards ceremony.",
     "Billy Crystal hosted the Oscars nine times, one of the most frequent hosts in its history.",
     3),
    ("pop_culture",
     "Gilda Radner was an original cast member of 'Saturday Night Live' when it premiered in 1975.",
     "Gilda Radner joined the cast of 'Saturday Night Live' for the first time in the 2010s.",
     "Gilda Radner was part of the show's very first cast in 1975.",
     3),
    ("pop_culture",
     "Jon Stewart hosted 'The Daily Show' for over 15 years before Trevor Noah succeeded him.",
     "Jon Stewart has never hosted a television news or comedy program.",
     "Jon Stewart hosted The Daily Show from 1999 to 2015.",
     2),
    ("pop_culture",
     "Singer-songwriter Billy Joel, known for hits like 'Piano Man,' is Jewish.",
     "Singer-songwriter Billy Joel, known for hits like 'Piano Man,' has said he has no Jewish heritage.",
     "Billy Joel has Jewish heritage on his father's side and has spoken publicly about it.",
     3),
    ("pop_culture",
     "All three original members of the hip-hop group Beastie Boys were Jewish.",
     "None of the original members of the hip-hop group Beastie Boys were Jewish.",
     "Mike D, MCA, and Ad-Rock, the Beastie Boys' three original members, were all Jewish.",
     3),
    ("pop_culture",
     "Singer Amy Winehouse, known for 'Rehab' and 'Back to Black,' was British and Jewish.",
     "Singer Amy Winehouse, known for 'Rehab' and 'Back to Black,' was American and not Jewish.",
     "Amy Winehouse was born in London to a Jewish family.",
     3),
    ("pop_culture",
     "Musician Lenny Kravitz has a Jewish mother, actress Roxie Roker.",
     "Musician Lenny Kravitz has said both of his parents were raised Christian with no Jewish background.",
     "Lenny Kravitz's mother, actress Roxie Roker, was Jewish.",
     4),
    ("pop_culture",
     "Gene Simmons of the rock band KISS was born in Israel before his family emigrated to the United States.",
     "Gene Simmons of the rock band KISS was born in Japan before his family emigrated to the United States.",
     "Gene Simmons was born in Haifa, Israel, and moved to the US as a child.",
     3),
    ("pop_culture",
     "Singer-songwriter Leonard Cohen, who was Jewish, wrote the widely covered song 'Hallelujah.'",
     "Singer-songwriter Leonard Cohen, who was Jewish, wrote the widely covered song 'Imagine.'",
     "Leonard Cohen wrote 'Hallelujah'; 'Imagine' was written by John Lennon.",
     2),
    ("pop_culture",
     "Paul Simon, of the duo Simon & Garfunkel, is Jewish.",
     "Paul Simon, of the duo Simon & Garfunkel, is not Jewish.",
     "Paul Simon grew up in a Jewish family in New York.",
     3),
    ("pop_culture",
     "Neil Diamond, known for songs like 'Sweet Caroline,' is Jewish and once studied to become a cantor.",
     "Neil Diamond, known for songs like 'Sweet Caroline,' has said he has no connection to Judaism.",
     "Neil Diamond grew up Jewish and even briefly trained toward becoming a cantor before his music career.",
     4),
    ("pop_culture",
     "Actress Scarlett Johansson has a Jewish mother.",
     "Actress Scarlett Johansson has said neither of her parents has any Jewish heritage.",
     "Scarlett Johansson's mother, Melanie Sloan, is from a Jewish family.",
     3),
    ("pop_culture",
     "Actor Jake Gyllenhaal has a Jewish mother, screenwriter Naomi Foner.",
     "Actor Jake Gyllenhaal has said both of his parents were raised Catholic.",
     "Jake Gyllenhaal's mother, Naomi Foner, is Jewish.",
     4),
    ("pop_culture",
     "British actress Rachel Weisz, known for 'The Mummy' and other films, is Jewish.",
     "British actress Rachel Weisz, known for 'The Mummy' and other films, is not Jewish.",
     "Rachel Weisz has Jewish heritage through both of her parents.",
     4),
    ("pop_culture",
     "Actress Winona Ryder has Jewish heritage on her father's side.",
     "Actress Winona Ryder has said she has no Jewish heritage at all.",
     "Winona Ryder's father's family has Jewish roots, which she has discussed publicly.",
     4),
    ("pop_culture",
     "Actor Paul Rudd is Jewish and has spoken about attending Hebrew school as a child.",
     "Actor Paul Rudd has said he was raised with no religious background of any kind.",
     "Paul Rudd has discussed his Jewish upbringing, including attending Hebrew school.",
     3),
    ("pop_culture",
     "Actor Logan Lerman, known for playing Percy Jackson, is Jewish.",
     "Actor Logan Lerman, known for playing Percy Jackson, is not Jewish.",
     "Logan Lerman has Jewish heritage and has discussed it in interviews.",
     4),
    ("pop_culture",
     "Actress Debra Messing, known for 'Will & Grace,' is Jewish.",
     "Actress Debra Messing, known for 'Will & Grace,' is not Jewish.",
     "Debra Messing has Jewish heritage and has spoken about it publicly.",
     3),
    ("pop_culture",
     "Actor and filmmaker Seth Rogen, known for comedies like 'Superbad,' is Jewish and grew up attending a Jewish summer camp.",
     "Actor and filmmaker Seth Rogen, known for comedies like 'Superbad,' has said he was raised with no religious background.",
     "Seth Rogen has spoken extensively about his Jewish upbringing, including attending Jewish summer camp.",
     3),
    ("pop_culture",
     "Director Steven Spielberg, who is Jewish, directed 'Schindler's List,' which won the Academy Award for Best Picture.",
     "Director Steven Spielberg, who is Jewish, directed 'Schindler's List,' which was never nominated for any Academy Award.",
     "Schindler's List won seven Academy Awards, including Best Picture and Best Director, at the 1994 ceremony.",
     2),
    ("pop_culture",
     "Director Stanley Kubrick, known for films like '2001: A Space Odyssey,' was Jewish.",
     "Director Stanley Kubrick, known for films like '2001: A Space Odyssey,' was not Jewish.",
     "Stanley Kubrick was born to a Jewish family in the Bronx, New York.",
     4),
    ("pop_culture",
     "Joel and Ethan Coen, the filmmaking duo behind movies like 'Fargo' and 'No Country for Old Men,' are Jewish brothers.",
     "Joel and Ethan Coen, the filmmaking duo behind movies like 'Fargo' and 'No Country for Old Men,' are not related.",
     "The Coen brothers are siblings from a Jewish family in Minnesota.",
     3),
    ("pop_culture",
     "Director and producer Judd Apatow, known for films like 'Knocked Up,' is Jewish.",
     "Director and producer Judd Apatow, known for films like 'Knocked Up,' is not Jewish.",
     "Judd Apatow has spoken about his Jewish upbringing on Long Island.",
     4),
    ("pop_culture",
     "Superman was created by Jerry Siegel and Joe Shuster, two Jewish American writers and artists.",
     "Superman was created by a team of writers working directly for the United States government.",
     "Siegel and Shuster, both from Jewish families in Cleveland, created Superman in the 1930s.",
     3),
    ("pop_culture",
     "Stan Lee, born Stanley Lieber, was Jewish and co-created characters including Spider-Man and the X-Men.",
     "Stan Lee, born Stanley Lieber, was Jewish and worked exclusively as an actor, never as a comic book writer.",
     "Stan Lee was a comic book writer and editor, central to creating many Marvel characters.",
     2),
    ("pop_culture",
     "Bob Kane, born Robert Kahn, was a Jewish American artist who co-created Batman.",
     "Bob Kane, born Robert Kahn, was a Jewish American artist who co-created Mickey Mouse.",
     "Bob Kane co-created Batman in 1939; Mickey Mouse was created by Walt Disney and Ub Iwerks.",
     3),
    ("pop_culture",
     "Jack Kirby, born Jacob Kurtzberg, was a Jewish comic artist who co-created Captain America, whose earliest cover famously showed him punching Hitler.",
     "Jack Kirby, born Jacob Kurtzberg, was a Jewish comic artist who co-created Captain America, a character with no connection to World War II themes.",
     "Captain America Comics #1 (1941), co-created by Kirby and Joe Simon, notably depicted Cap punching Hitler on its cover.",
     3),
    ("pop_culture",
     "Baseball pitcher Sandy Koufax famously declined to pitch Game 1 of the 1965 World Series because it fell on Yom Kippur.",
     "Baseball pitcher Sandy Koufax famously refused to ever play professional baseball on a Saturday.",
     "Koufax sat out Game 1 of the 1965 World Series specifically because it coincided with Yom Kippur.",
     2),
    ("pop_culture",
     "Swimmer Mark Spitz, who is Jewish, won seven gold medals at the 1972 Munich Olympics.",
     "Swimmer Mark Spitz, who is Jewish, competed in the Olympics but never won a gold medal.",
     "Mark Spitz won a then-record seven gold medals at the 1972 Summer Olympics.",
     3),
    ("pop_culture",
     "Gymnast Aly Raisman, an Olympic medalist, is Jewish and has competed for the US Olympic team.",
     "Gymnast Aly Raisman, an Olympic medalist, has said she has no Jewish heritage.",
     "Aly Raisman is Jewish and has spoken about her heritage, including competing to a routine set to 'Hava Nagila.'",
     3),
    ("pop_culture",
     "NFL wide receiver Julian Edelman, who played for the New England Patriots, is Jewish.",
     "NFL wide receiver Julian Edelman, who played for the New England Patriots, is not Jewish.",
     "Julian Edelman has Jewish heritage through his father and has spoken about it publicly.",
     4),
    ("pop_culture",
     "Irving Berlin, a Jewish immigrant songwriter, wrote 'White Christmas,' one of the best-selling Christmas songs of all time.",
     "Irving Berlin, a Jewish immigrant songwriter, refused to ever write songs about Christian holidays.",
     "Irving Berlin wrote White Christmas despite being Jewish, one of pop music's famous ironies.",
     3),
    ("pop_culture",
     "Leonard Bernstein, a Jewish composer and conductor, wrote the music for the musical 'West Side Story.'",
     "Leonard Bernstein, a Jewish composer and conductor, wrote the music for the musical 'The Sound of Music.'",
     "Bernstein composed West Side Story; The Sound of Music was written by Rodgers and Hammerstein.",
     3),
    ("pop_culture",
     "George Gershwin, who composed 'Rhapsody in Blue,' was the son of Jewish immigrants, and often worked with his lyricist brother Ira.",
     "George Gershwin, who composed 'Rhapsody in Blue,' had no siblings and worked entirely alone.",
     "George Gershwin frequently collaborated with his brother Ira, who wrote lyrics for many of his songs.",
     3),
    ("pop_culture",
     "'The Marvelous Mrs. Maisel' is a TV series about a Jewish woman who becomes a stand-up comedian in 1950s New York.",
     "'The Marvelous Mrs. Maisel' is a TV series about a professional magician in modern-day Las Vegas.",
     "The Marvelous Mrs. Maisel follows Miriam 'Midge' Maisel's stand-up comedy career in 1950s New York.",
     2),
    ("pop_culture",
     "'Broad City,' a comedy series created by and starring Abbi Jacobson and Ilana Glazer, both Jewish, is set in New York City.",
     "'Broad City,' a comedy series created by and starring Abbi Jacobson and Ilana Glazer, is a period drama set in the 1800s.",
     "Broad City is a contemporary comedy set in New York, not a historical drama.",
     3),
    ("pop_culture",
     "'Unorthodox,' a Netflix miniseries, follows a young woman leaving a Hasidic community in Brooklyn.",
     "'Unorthodox,' a Netflix miniseries, follows a group of astronauts on a mission to Mars.",
     "Unorthodox is based on a memoir about leaving a Hasidic Jewish community.",
     3),
    ("pop_culture",
     "Adam Sandler starred in the comedy film 'You Don't Mess with the Zohan,' about a former Israeli commando turned hairdresser.",
     "Adam Sandler starred in the comedy film 'You Don't Mess with the Zohan,' about a competitive chess champion.",
     "The film's premise centers on a former Israeli special forces agent working as a hairdresser in New York.",
     3),
    ("pop_culture",
     "Chicken soup is sometimes affectionately nicknamed 'Jewish penicillin' for its folk reputation as a cold remedy.",
     "Chicken soup is sometimes affectionately nicknamed 'Jewish champagne' for its folk reputation at celebrations.",
     "'Jewish penicillin' is the well-known nickname, referencing chicken soup's reputed cold-curing power, not a celebratory drink comparison.",
     2),
    ("pop_culture",
     "Manischewitz, a well-known brand of sweet kosher wine, is closely associated in American pop culture with Passover seders.",
     "Manischewitz, a well-known brand of sweet kosher wine, is a wine produced exclusively in France.",
     "Manischewitz is an American kosher food company long associated with Passover.",
     3),
    ("pop_culture",
     "Israel competes in the Eurovision Song Contest because its national broadcaster belongs to the European Broadcasting Union, despite Israel's geography.",
     "Israel competes in the Eurovision Song Contest because it is officially considered part of the European continent.",
     "Eurovision eligibility is based on European Broadcasting Union membership, not strict geography — which is also why Australia has competed.",
     4),
    ("pop_culture",
     "The words 'schlemiel' and 'shlimazel' appear in the opening theme song of the sitcom 'Laverne & Shirley.'",
     "The words 'schlemiel' and 'shlimazel' appear in the opening theme song of the sitcom 'Friends.'",
     "Laverne & Shirley's theme song famously includes the line featuring both Yiddish words.",
     3),
    ("pop_culture",
     "Chess champion Garry Kasparov has a Jewish mother.",
     "Chess champion Garry Kasparov has said he has no Jewish heritage.",
     "Garry Kasparov's mother, Klara Kasparova, was Armenian and Jewish.",
     5),
    ("pop_culture",
     "Radio personality Howard Stern is Jewish and has discussed his upbringing on his own show.",
     "Radio personality Howard Stern has said he was raised with no religious background of any kind.",
     "Howard Stern has spoken at length on-air about growing up Jewish on Long Island.",
     3),
    ("pop_culture",
     "Longtime broadcaster Larry King was born Lawrence Harvey Zeiger and was Jewish.",
     "Longtime broadcaster Larry King was born with the surname King and had no other birth name.",
     "Larry King changed his surname from Zeiger to King early in his broadcasting career.",
     4),
    ("pop_culture",
     "British actor Sacha Baron Cohen, known for characters like Borat, is Jewish.",
     "British actor Sacha Baron Cohen, known for characters like Borat, is not Jewish.",
     "Sacha Baron Cohen has spoken about his Jewish upbringing and observance.",
     3),
    ("pop_culture",
     "Israeli model Bar Refaeli has appeared on the cover of the Sports Illustrated Swimsuit Issue.",
     "Israeli model Bar Refaeli has never appeared in any major international magazine.",
     "Bar Refaeli appeared on the cover of the Sports Illustrated Swimsuit Issue in 2009.",
     4),
    ("pop_culture",
     "Comedian Sarah Silverman starred in her own Comedy Central sketch series, 'The Sarah Silverman Program.'",
     "Comedian Sarah Silverman has never had her own television series.",
     "The Sarah Silverman Program ran on Comedy Central from 2007 to 2010.",
     4),
    ("pop_culture",
     "Actress Gwyneth Paltrow has a Jewish father, producer and director Bruce Paltrow.",
     "Actress Gwyneth Paltrow has said neither of her parents had any Jewish heritage.",
     "Gwyneth Paltrow's father, Bruce Paltrow, was Jewish; her mother, Blythe Danner, is not.",
     4),
    ("pop_culture",
     "Comedian and filmmaker Jerry Lewis hosted an annual Labor Day telethon raising money for muscular dystrophy research for decades.",
     "Comedian and filmmaker Jerry Lewis is known primarily for a decades-long career as a classical violinist.",
     "Jerry Lewis hosted the Muscular Dystrophy Association telethon from 1966 to 2010.",
     3),
    ("pop_culture",
     "Comedian Rodney Dangerfield, known for the catchphrase 'I don't get no respect,' was Jewish.",
     "Comedian Rodney Dangerfield, known for the catchphrase 'I don't get no respect,' was not Jewish.",
     "Rodney Dangerfield, born Jacob Cohen, was Jewish.",
     3),
    ("pop_culture",
     "Groucho Marx, of the classic comedy team the Marx Brothers, was Jewish.",
     "Groucho Marx, of the classic comedy team the Marx Brothers, was not Jewish.",
     "The Marx Brothers came from a Jewish immigrant family in New York.",
     2),
]
