# Batch 9: ~46 new true/false pairs, working toward a 1780-statement target.
# Mines fresh territory: individual melachot (39 forbidden Shabbat labors),
# named Shabbats, lifecycle mourning stages, specific blessings, Talmud
# tractate structure, Yiddish loanwords, agricultural tithe terms, and more
# diaspora communities (Egypt, Caribbean, colonial America, Bosnia, Spain/
# Portugal citizenship law, Caucasus, South Africa, Argentina).

PAIRS = [
    # --- shabbat: individual melachot ---
    ("shabbat",
     "One of the 39 traditionally forbidden Shabbat labors is tying a permanent knot.",
     "None of the 39 traditionally forbidden Shabbat labors relate to tying knots.",
     "Tying a permanent knot is specifically listed among the 39 melachot, the traditional categories of forbidden Shabbat labor."),
    ("shabbat",
     "One of the 39 traditionally forbidden Shabbat labors is writing two or more letters.",
     "None of the 39 traditionally forbidden Shabbat labors relate to writing.",
     "Writing (specifically two or more letters) is one of the 39 traditional melachot."),
    ("shabbat",
     "One of the 39 traditionally forbidden Shabbat labors is sewing two stitches.",
     "None of the 39 traditionally forbidden Shabbat labors relate to sewing.",
     "Sewing two stitches is specifically listed among the 39 melachot."),
    ("shabbat",
     "One of the 39 traditionally forbidden Shabbat labors is building or demolishing a structure.",
     "None of the 39 traditionally forbidden Shabbat labors relate to construction or demolition.",
     "Building and demolishing are both separately listed among the 39 melachot."),
    ("shabbat",
     "One of the 39 traditionally forbidden Shabbat labors is trapping a living creature.",
     "None of the 39 traditionally forbidden Shabbat labors relate to trapping animals.",
     "Trapping is one of the 39 traditional melachot, originally tied to hunting-related labor."),
    ("shabbat",
     "One of the 39 traditionally forbidden Shabbat labors is winnowing or sorting mixed items.",
     "None of the 39 traditionally forbidden Shabbat labors relate to sorting or separating mixed items.",
     "Winnowing and selecting/sorting are separately listed among the 39 melachot, originally tied to agricultural processing."),

    # --- holidays ---
    ("holidays",
     "Chol HaMoed refers to the intermediate, semi-festive days of Passover and Sukkot, when some restrictions are relaxed compared to the holiday's main days.",
     "Chol HaMoed refers to the single most restrictive day of Passover and Sukkot, when every activity is forbidden.",
     "Chol HaMoed is a relaxed intermediate period, not the most restrictive day of the holiday."),
    ("holidays",
     "Ta'anit Bechorot, the Fast of the Firstborn, is traditionally observed by firstborn sons on the day before Passover begins.",
     "Ta'anit Bechorot, the Fast of the Firstborn, is traditionally observed by firstborn daughters on the day after Passover ends.",
     "This fast traditionally falls on the eve of Passover and is tied to firstborn sons, not firstborn daughters after the holiday."),
    ("holidays",
     "The Shabbat before Tisha B'Av is traditionally called Shabbat Chazon, named for the opening word of that week's prophetic reading.",
     "The Shabbat before Tisha B'Av is traditionally called Shabbat Nachamu, a name that actually belongs to the Shabbat following Tisha B'Av.",
     "Shabbat Chazon precedes Tisha B'Av; Shabbat Nachamu is a separate, later Shabbat of consolation."),
    ("holidays",
     "The Shabbat after Tisha B'Av is traditionally called Shabbat Nachamu, meaning 'be comforted,' beginning a period of consolation.",
     "The Shabbat after Tisha B'Av is traditionally called Shabbat Chazon, meaning 'vision,' a name that actually belongs to the Shabbat before Tisha B'Av.",
     "Shabbat Nachamu follows Tisha B'Av; Shabbat Chazon is the earlier, preceding Shabbat."),
    ("holidays",
     "Sephardic custom often begins reciting Selichot prayers a full month before Rosh Hashanah, from the start of Elul, earlier than common Ashkenazi practice.",
     "It's traditional for all communities, Ashkenazi and Sephardic alike, to begin reciting Selichot on exactly the same date every year, with no variation in timing.",
     "Selichot's starting date genuinely varies by community, with Sephardic custom generally starting earlier than common Ashkenazi practice."),
    ("holidays",
     "The month of Elul, immediately preceding Rosh Hashanah, is traditionally treated as a time for increased introspection and preparation for the High Holidays.",
     "The month of Elul, immediately preceding Rosh Hashanah, is traditionally treated as an ordinary month with no special spiritual significance.",
     "Elul is widely treated as a traditional lead-up period for reflection ahead of the High Holidays, not an unremarkable month."),

    # --- lifecycle ---
    ("lifecycle",
     "A sandek is a person given the honor of holding the baby during a brit milah (circumcision) ceremony.",
     "A sandek is a person given the honor of officiating a Jewish wedding ceremony.",
     "A sandek's role is specific to the brit milah ceremony, not officiating weddings."),
    ("lifecycle",
     "A traditional Jewish wedding chuppah is often open on all sides, sometimes held outdoors under the sky, symbolizing a new, hospitable home.",
     "A traditional Jewish wedding chuppah is traditionally a fully enclosed, windowless room, symbolizing privacy above all else.",
     "An open-sided or outdoor chuppah is the traditional form, not an enclosed windowless room."),
    ("lifecycle",
     "Kaddish for a deceased parent is traditionally recited for eleven months, while the fuller mourning period (avelut) for a parent traditionally extends for twelve months.",
     "Kaddish for a deceased parent is traditionally recited for twelve months, while the fuller mourning period, avelut, traditionally extends for only eleven months.",
     "Kaddish is traditionally stopped a month short, at eleven months, within a twelve-month avelut period for parents."),
    ("lifecycle",
     "Before burial, a person in the initial period of acute mourning is traditionally called an onen, and is exempt from certain religious obligations during this time.",
     "Before burial, a person in the initial period of acute mourning is traditionally required to take on extra religious obligations beyond the usual daily requirements.",
     "An onen is traditionally exempt from certain obligations, not burdened with additional ones, during this acute pre-burial period."),
    ("lifecycle",
     "It's traditional for mourners to refrain from haircuts and shaving during the sheloshim (30-day) period following a death.",
     "It's traditional for mourners to get a fresh haircut every week during the sheloshim (30-day) period following a death.",
     "Avoiding haircuts and shaving, not getting them regularly, is the traditional sheloshim practice."),

    # --- prayer ---
    ("prayer",
     "Birkat Hamapil is a blessing traditionally recited before going to sleep at night.",
     "Birkat Hamapil is a blessing traditionally recited immediately upon waking up in the morning.",
     "Birkat Hamapil is specifically a bedtime blessing, not a morning one."),
    ("prayer",
     "Tachanun, a penitential prayer, is traditionally omitted on Shabbat, festivals, and other joyous occasions.",
     "Tachanun, a penitential prayer, is traditionally recited only on Shabbat, festivals, and other joyous occasions, and skipped on ordinary weekdays.",
     "Tachanun's solemn tone means it's skipped on joyous days, the opposite of being reserved for them."),
    ("prayer",
     "The blessing recited over wine, Borei Pri Hagafen, uses the same wording whether at a Shabbat meal, a holiday meal, or a wedding.",
     "The blessing recited over wine changes its wording completely depending on whether it's a Shabbat meal, a holiday meal, or a wedding.",
     "Borei Pri Hagafen is a fixed formula used consistently across these different occasions, not a changing text."),
    ("prayer",
     "Birkot HaShachar, a series of morning blessings recited early in the daily prayer service, thank God for everyday things like sight, clothing, and the ability to stand upright.",
     "Birkot HaShachar is recited only on Yom Kippur, thanking God for forgiveness of the past year's sins.",
     "Birkot HaShachar is a daily morning practice about everyday gratitude, not a once-a-year Yom Kippur prayer."),

    # --- ritual_objects ---
    ("ritual_objects",
     "A besamim (spice) box used for Havdalah is traditionally often shaped like a small tower, sometimes with a tiny flag on top.",
     "A besamim box used for Havdalah is traditionally always shaped like a Star of David, with no other traditional design.",
     "The tower shape, often with a small flag, is a classic traditional besamim box design, though not the only one."),
    ("ritual_objects",
     "A tallit is traditionally required to have four corners, since the biblical commandment for tzitzit specifically applies to four-cornered garments.",
     "A tallit is traditionally required to have exactly six corners, matching the six-pointed Star of David.",
     "The tzitzit commandment applies to four-cornered garments, which is why a tallit traditionally has four corners, not six."),
    ("ritual_objects",
     "A Chanukah menorah (chanukiah) is traditionally allowed to be made from many different materials, including silver, olive wood, glass, or simple clay.",
     "A Chanukah menorah must traditionally be made only from pure gold, with no other material considered acceptable.",
     "Chanukiah material is flexible; there's no traditional requirement that it be made of gold."),

    # --- texts ---
    ("texts",
     "Tractate Berakhot, dealing primarily with blessings and prayer, is traditionally treated as the opening tractate of the Talmud.",
     "Tractate Berakhot, dealing primarily with the laws of Shabbat labor, is traditionally treated as the final tractate of the Talmud.",
     "Berakhot concerns blessings and prayer, and is traditionally the opening tractate, not a Shabbat-labor tractate placed last."),
    ("texts",
     "Nachmanides (Ramban), a 13th-century rabbi, philosopher, and physician, wrote an influential Torah commentary, distinct from Rashi's earlier commentary.",
     "Nachmanides (Ramban) and Rashi are traditionally understood to be the exact same historical person, using two different names.",
     "Ramban and Rashi are two distinct historical commentators from different centuries, not the same person."),
    ("texts",
     "Rashi, the influential medieval commentator, is traditionally said to have worked as a wine merchant in addition to his scholarly work.",
     "Rashi, the influential medieval commentator, is traditionally said to have worked as a professional soldier in addition to his scholarly work.",
     "Rashi's family is traditionally associated with the wine trade in France, not a military career."),
    ("texts",
     "The Ein Yaakov is a traditional compilation gathering the non-legal, narrative (aggadic) material scattered throughout the Talmud.",
     "The Ein Yaakov is a traditional compilation gathering only the legal rulings (halakha) scattered throughout the Talmud, omitting all narrative material.",
     "Ein Yaakov specifically collects aggadic (narrative) material, not the legal rulings."),

    # --- language ---
    ("language",
     "The Yiddish-derived word 'schlep,' used in English, means to carry or drag something with effort.",
     "The Yiddish-derived word 'schlep,' used in English, means to celebrate joyfully with music and dancing.",
     "'Schlep' means to haul something laboriously, not to celebrate."),
    ("language",
     "The Yiddish-derived word 'kvetch,' used in English, means to complain persistently.",
     "The Yiddish-derived word 'kvetch,' used in English, means to offer generous praise and compliments.",
     "'Kvetch' means to complain, the opposite of offering praise."),
    ("language",
     "'Bubbe' and 'zayde' are Yiddish terms of endearment for a grandmother and grandfather, respectively.",
     "'Bubbe' and 'zayde' are Yiddish terms for a bride and groom, respectively.",
     "These are grandparent terms, not wedding-related terms for a bride and groom."),
    ("language",
     "The Yiddish-derived word 'nosh,' used in English, means to snack on food casually.",
     "The Yiddish-derived word 'nosh,' used in English, means to formally host a large banquet.",
     "'Nosh' refers to casual snacking, not hosting a formal banquet."),

    # --- kashrut ---
    ("kashrut",
     "Tevel refers to produce that hasn't yet had its traditional tithes separated, and is traditionally not eaten until tithed.",
     "Tevel refers to produce that has already been fully tithed and blessed, ready for immediate consumption with no restrictions.",
     "Tevel is specifically untithed produce, traditionally restricted until tithing is completed, not already-processed produce."),
    ("kashrut",
     "The blessing recited before eating fruit from a tree is Borei Pri Ha'etz, while the blessing for produce grown from the ground is Borei Pri Ha'adama.",
     "The blessing recited before eating fruit from a tree is identical, word-for-word, to the blessing recited before eating bread.",
     "Tree fruit and bread each have their own distinct traditional blessing, not a shared one."),
    ("kashrut",
     "Demai refers to produce bought from a source where it's uncertain whether tithes were properly separated, traditionally requiring a smaller precautionary tithe.",
     "Demai refers to produce that is entirely forbidden to eat under any circumstances, with no remedy available.",
     "Demai has a defined traditional remedy (a precautionary tithe), unlike produce that's simply forbidden outright."),

    # --- symbols ---
    ("symbols",
     "A Tree of Life (Etz Chaim) is a traditional Jewish symbol, also used as the name for the wooden rollers of a Torah scroll.",
     "A Tree of Life (Etz Chaim) is a symbol used exclusively in modern Christian iconography, with no connection to Jewish tradition or the Torah scroll.",
     "'Etz Chaim' is a genuine traditional Jewish term, used both as a broader symbol and specifically for Torah scroll rollers."),

    # --- people ---
    ("people",
     "Rabbi Yosef Karo, author of the influential legal code the Shulchan Aruch, lived in the 16th century, partly in the city of Safed in the Land of Israel.",
     "Rabbi Yosef Karo, author of the influential legal code the Shulchan Aruch, lived in the 20th century, entirely in New York City.",
     "Karo was a 16th-century scholar associated with Safed, not a 20th-century figure based in New York."),
    ("people",
     "Rashi, the influential medieval Torah and Talmud commentator, lived in France in the 11th century.",
     "Rashi, the influential medieval Torah and Talmud commentator, lived in Spain in the 15th century.",
     "Rashi lived in 11th-century France (Troyes), not 15th-century Spain."),

    # --- diaspora ---
    ("diaspora",
     "Egypt's Cairo was historically home to a significant Jewish community, including the ancient Ben Ezra Synagogue, where the famous Cairo Genizah manuscripts were discovered.",
     "Egypt's Cairo was historically home to a significant Jewish community, including the ancient Ben Ezra Synagogue, which was built in the 20th century as a memorial.",
     "The Ben Ezra Synagogue is an ancient site, not a 20th-century memorial building, and is specifically where the Cairo Genizah was found."),
    ("diaspora",
     "Curaçao, in the Caribbean, is home to the Mikvé Israel-Emanuel Synagogue, one of the oldest continuously used synagogues in the Americas.",
     "Curaçao, in the Caribbean, has no historical Jewish community or synagogue of any kind.",
     "Curaçao has a well-documented historic Jewish community, centered on a synagogue dating back centuries."),
    ("diaspora",
     "The Touro Synagogue in Newport, Rhode Island, dedicated in 1763, is the oldest surviving synagogue building in the United States.",
     "The Touro Synagogue in Newport, Rhode Island, was built in the 21st century as a replica of an older European synagogue.",
     "Touro Synagogue is a genuine 18th-century building, the oldest surviving synagogue structure in the US, not a modern replica."),
    ("diaspora",
     "The Sarajevo Haggadah, an illuminated medieval manuscript, is one of the oldest surviving illustrated Jewish texts, associated with Bosnia's historic Jewish community.",
     "The Sarajevo Haggadah, an illuminated manuscript, was created in the 20th century as a modern artistic tribute to older traditions.",
     "The Sarajevo Haggadah is a genuine medieval manuscript, not a 20th-century creation."),
    ("diaspora",
     "Since 2015, Spain and Portugal have both offered a legal pathway to citizenship for descendants of Sephardic Jews expelled centuries earlier.",
     "Since 2015, Spain and Portugal have both formally banned any descendants of Sephardic Jews from acquiring citizenship, regardless of ancestry.",
     "Spain and Portugal introduced citizenship pathways for Sephardic descendants, not bans."),
    ("diaspora",
     "Mountain Jews, a distinct community historically from the Caucasus region, traditionally speak Juhuri, a Jewish dialect of a Persian-related language.",
     "Mountain Jews, a distinct community historically from the Caucasus region, traditionally speak only standard Russian, with no distinct language of their own.",
     "Mountain Jews traditionally speak Juhuri, their own distinct language, not simply standard Russian."),
    ("diaspora",
     "South African Jewish communities historically trace much of their origin to Lithuanian Jewish immigration in the late 19th and early 20th centuries.",
     "South African Jewish communities historically trace their origin entirely to Ethiopian Jewish immigration in the late 19th and early 20th centuries.",
     "South African Jewry's roots are overwhelmingly Lithuanian, not Ethiopian."),
    ("diaspora",
     "Argentina is home to one of the largest Jewish communities in Latin America, with early immigration significantly shaped by Eastern European Jewish agricultural colonists in the late 19th century.",
     "Argentina has historically had no significant Jewish community; most Latin American Jewish communities are instead concentrated in Chile.",
     "Argentina has one of Latin America's largest and most historically significant Jewish communities, not an absent one."),
]
