# Batch 14: Yiddish words, meanings, and origins — words not already
# covered elsewhere in the bank (chutzpah, mensch, oy vey, schlep, kvetch,
# bubbe/zayde, nosh already exist under language).

PAIRS = [
    ("language",
     "The Yiddish-derived word 'schmooze,' used in English, means to chat casually, often to build a friendly connection.",
     "The Yiddish-derived word 'schmooze,' used in English, means to negotiate aggressively over a price.",
     "Schmoozing is casual, friendly conversation or networking, not price haggling.",
     2),
    ("language",
     "The Yiddish-derived word 'tchotchke,' used in English, means a small decorative trinket or knick-knack.",
     "The Yiddish-derived word 'tchotchke,' used in English, means a large, heavy piece of furniture.",
     "A tchotchke is a small trinket or knick-knack, not a piece of furniture.",
     2),
    ("language",
     "The Yiddish word 'shlemiel' describes a clumsy, foolish, or luckless bungler.",
     "The Yiddish word 'shlemiel' describes a wealthy, highly successful businessperson.",
     "A shlemiel is a bungler prone to mishaps, not a successful businessperson.",
     3),
    ("language",
     "The Yiddish word 'shlimazel' describes a chronically unlucky person, someone bad luck seems to follow.",
     "The Yiddish word 'shlimazel' describes an exceptionally graceful dancer.",
     "A shlimazel is defined by persistent bad luck. A classic distinction: the shlemiel spills the soup, and the shlimazel is the one it lands on.",
     3),
    ("language",
     "The Yiddish-derived word 'klutz,' used in English, means a clumsy, awkward person.",
     "The Yiddish-derived word 'klutz,' used in English, means an especially skilled craftsperson.",
     "A klutz is clumsy, not skilled — the word traces back to a Yiddish/German word for a block of wood.",
     2),
    ("language",
     "The Yiddish-derived word 'kvell,' used in English, means to swell with pride, especially over a loved one's achievement.",
     "The Yiddish-derived word 'kvell,' used in English, means to feel embarrassed in public.",
     "To kvell is to beam with pride, not to feel embarrassment.",
     3),
    ("language",
     "The Yiddish-derived word 'shtick,' used in English, refers to a performer's signature comic routine or gimmick.",
     "The Yiddish-derived word 'shtick,' used in English, refers to a formal legal contract.",
     "Shtick refers to a comic routine or characteristic gimmick, not a legal document.",
     2),
    ("language",
     "The Yiddish-derived word 'maven,' used in English, means an expert or knowledgeable enthusiast in a particular field.",
     "The Yiddish-derived word 'maven,' used in English, means a complete beginner with no experience.",
     "A maven is an expert, the opposite of a beginner.",
     2),
    ("language",
     "The Yiddish-derived word 'nudnik,' used in English, describes a pestering, nagging, or tediously bothersome person.",
     "The Yiddish-derived word 'nudnik,' used in English, describes an especially quiet, shy person.",
     "A nudnik is a persistent pest or nag, not someone quiet and shy.",
     3),
    ("language",
     "The Yiddish-derived word 'yenta,' used in English, describes a gossip or busybody who meddles in others' affairs.",
     "The Yiddish-derived word 'yenta,' used in English, describes someone who never discusses other people's business.",
     "A yenta is a gossip or busybody, the opposite of discreet.",
     3),
    ("language",
     "The Yiddish-derived word 'verklempt,' used in English, means overcome with emotion, too choked up to speak.",
     "The Yiddish-derived word 'verklempt,' used in English, means feeling perfectly calm and relaxed.",
     "Verklempt describes being emotionally overwhelmed, not calm.",
     3),
    ("language",
     "The English word 'glitch' is often traced back to the Yiddish word 'glitshn,' meaning to slip or slide.",
     "The English word 'glitch' comes directly from the Latin word for 'error.'",
     "Glitch is widely traced to Yiddish 'glitshn' (to slip), entering English via early radio and space-program slang.",
     4),
    ("language",
     "The English word 'spiel,' meaning a long, rehearsed sales pitch or speech, comes from the Yiddish/German word for 'play.'",
     "The English word 'spiel,' meaning a long, rehearsed sales pitch or speech, comes from a Hebrew word meaning 'silence.'",
     "Spiel derives from Yiddish/German 'shpil'/'Spiel,' meaning play or game.",
     3),
    ("language",
     "Yiddish is sometimes affectionately called 'mame-loshn,' meaning 'mother tongue.'",
     "Yiddish is sometimes affectionately called 'melech-loshn,' meaning 'king's tongue.'",
     "'Mame-loshn' (mother tongue) is the traditional affectionate nickname for Yiddish.",
     4),
    ("language",
     "Despite a sharp decline after the Holocaust, Yiddish remains a first language for many Hasidic communities today, with children raised speaking it at home.",
     "Yiddish has had no native speakers of any kind since the 1960s.",
     "Yiddish continues as a living first language in many Hasidic communities worldwide, not just a historical language.",
     3),
]
