# Batch 3: ~53 new true/false pairs, weighted heavily toward laws and
# customs (kashrut, Shabbat, holiday observance, ritual objects, lifecycle
# rituals, prayer practice, synagogue custom, halakhic texts) per user
# request to make laws/customs the majority of the bank.

PAIRS = [
    # --- kashrut (laws) ---
    ("kashrut",
     "Before cooking, kosher meat traditionally has its blood removed through a soaking-and-salting process called kashering.",
     "Kosher meat is automatically ready to cook immediately after slaughter, with no further blood-removal process required.",
     "Kashering (soaking and salting) removes blood from meat after slaughter; it's a required extra step, not automatic."),
    ("kashrut",
     "The waiting period between eating meat and dairy varies by community and custom, ranging from about one hour to six hours.",
     "The waiting period between eating meat and dairy is fixed at exactly 24 hours in every Jewish community.",
     "There's no single universal wait time; customs range roughly from one to six hours depending on community."),
    ("kashrut",
     "Passover kosher rules add extra restrictions, forbidding chametz (leavened grain products) even in foods that are kosher year-round.",
     "Passover kosher rules are identical to year-round kosher rules, with no additional restrictions.",
     "Passover adds the specific prohibition on chametz, on top of standard year-round kashrut rules."),
    ("kashrut",
     "In strictly kosher homes, utensils and even appliances like dishwashers are sometimes kept entirely separate for meat and dairy.",
     "The same utensils can be used for meat and dairy as long as they're washed with soap in between.",
     "Kosher practice generally requires separate utensils (and sometimes separate appliances) for meat and dairy, not just washing between uses."),
    ("kashrut",
     "Some traditional Jewish communities avoid eating fish and meat together at the same meal, though fish and dairy may be combined.",
     "Fish and meat may never be eaten at the same meal in any Jewish community, while fish and dairy are strictly forbidden.",
     "The customary caution is around combining fish with meat, not fish with dairy, and it isn't treated as strictly as the meat-dairy separation itself."),
    ("kashrut",
     "For certain kosher foods, Jewish law traditionally requires that a Jewish person be involved in the cooking process, a concept called bishul Yisrael.",
     "Kosher status depends only on the ingredients used, never on who does the cooking.",
     "Bishul Yisrael is a real requirement for specific categories of cooked food, beyond just checking the ingredients."),
    ("kashrut",
     "Kosher wine traditionally must be handled, from grape-crushing through bottling, exclusively by Sabbath-observant Jews.",
     "Kosher wine can be made and handled by anyone, with no special requirements beyond using kosher grapes.",
     "Kosher wine has traditional handling requirements tied to who processes it, not just the grapes used."),
    ("kashrut",
     "The prohibition against eating a limb torn from a living animal is one of the traditional seven Noahide laws, considered universal rather than only for Jews.",
     "This prohibition applies only to Jewish people and is not considered part of any universal moral code.",
     "Ever min ha'chai (a limb from a living animal) is traditionally counted among the seven Noahide laws said to apply to all humanity."),
    ("kashrut",
     "After a kosher slaughter, an animal's internal organs are traditionally inspected for disease or defects that could still render it non-kosher.",
     "Once an animal has been properly slaughtered by a shochet, it is automatically kosher with no further inspection needed.",
     "Proper slaughter alone isn't sufficient; a post-slaughter inspection can still disqualify meat as treif."),
    ("kashrut",
     "Because insects generally aren't kosher, observant Jews traditionally check leafy vegetables carefully for them before eating.",
     "Insects are considered kosher as long as they're cooked thoroughly.",
     "Cooking doesn't make non-kosher insects acceptable; the traditional response is to check produce and remove them."),
    ("kashrut",
     "Certain locust species are a historical exception, permitted as kosher under Jewish law, unlike other insects — though most communities today no longer rely on it.",
     "All insects, including locusts, are absolutely forbidden under Jewish dietary law with no historical exceptions.",
     "The Torah names certain flying insects, including some locusts, as permitted; the tradition of identifying them has mostly lapsed in practice today."),

    # --- shabbat (laws and customs) ---
    ("shabbat",
     "It's traditional to eat three festive meals over the course of Shabbat, not just a single Friday night dinner.",
     "Traditionally, only one meal is eaten on Shabbat, on Friday night.",
     "Three meals — Friday night, Saturday midday, and a smaller third meal — are the traditional Shabbat structure."),
    ("shabbat",
     "Lighting a fire, including striking a match, is traditionally forbidden on Shabbat, which is why candles are lit before Shabbat begins.",
     "Lighting candles and fires is specifically encouraged as part of Shabbat observance throughout the day.",
     "Fire-related labor is among the forbidden Shabbat categories, so candles are lit beforehand rather than during Shabbat itself."),
    ("shabbat",
     "Many halachic authorities treat turning electric lights on and off as equivalent to a forbidden category of Shabbat labor.",
     "Turning electric lights on and off is universally permitted on Shabbat because electricity wasn't mentioned in ancient texts.",
     "Despite not being mentioned in ancient texts, most halachic authorities extend existing labor categories to cover electric switches."),
    ("shabbat",
     "A decorative spice box called a besamim, filled with fragrant items like cloves, is used during the Havdalah ceremony.",
     "A besamim is a small prayer book read only during the Havdalah ceremony, unrelated to spices.",
     "Besamim refers to fragrant spices (and the box holding them) smelled during Havdalah, not a book."),
    ("shabbat",
     "Muktzeh is a traditional category of items, such as money, pens, or phones, that are set aside and not handled on Shabbat, even without using them.",
     "Muktzeh refers to food that must be finished before Shabbat begins, with no connection to handling objects.",
     "Muktzeh concerns which objects may be physically handled on Shabbat, not a rule about finishing food beforehand."),

    # --- holidays (observance customs) ---
    ("holidays",
     "On Yom Kippur, traditional restrictions include not wearing leather shoes, in addition to fasting from food and drink.",
     "On Yom Kippur, the only traditional restriction is fasting from food; all other daily activities are permitted without limitation.",
     "Yom Kippur traditionally includes several restrictions beyond fasting, including avoiding leather footwear."),
    ("holidays",
     "Ne'ilah is the concluding prayer service of Yom Kippur, recited as the gates of repentance are traditionally said to be closing.",
     "Ne'ilah is the opening prayer service of Rosh Hashanah, recited to begin the new year.",
     "Ne'ilah closes out Yom Kippur; it isn't part of Rosh Hashanah at all."),
    ("holidays",
     "Selichot, penitential prayers, are traditionally recited in the period leading up to and during the High Holidays.",
     "Selichot are festive songs traditionally sung only during Purim.",
     "Selichot are solemn penitential prayers tied to the High Holiday season, not Purim festivities."),
    ("holidays",
     "Tashlich is a custom of symbolically casting away sins, often performed near a body of water, typically around Rosh Hashanah.",
     "Tashlich is a custom of symbolically casting away sins, performed by burning a written list of sins, typically around Passover.",
     "Tashlich is specifically tied to water and Rosh Hashanah, not burning and Passover."),
    ("holidays",
     "During Sukkot, it's traditional to eat meals — and for some, even sleep — inside the sukkah for the week-long holiday.",
     "During Sukkot, entering the sukkah at any point during the holiday is traditionally forbidden; it's viewed from outside only.",
     "The sukkah is meant to be used and dwelt in during the holiday, not just viewed from a distance."),
    ("holidays",
     "Hoshana Rabbah, the seventh day of Sukkot, includes a distinctive custom of beating willow branches on the ground.",
     "Hoshana Rabbah includes a custom of planting willow branches in the ground to grow new trees.",
     "The Hoshana Rabbah custom involves striking bundled willow branches against the ground, not planting them."),
    ("holidays",
     "The Passover Haggadah includes a tradition of opening the door for the prophet Elijah during the seder.",
     "The Passover Haggadah includes a tradition of opening all the windows in the house to let out chametz.",
     "The door-opening custom during the seder is specifically associated with welcoming Elijah."),
    ("holidays",
     "It's customary to search the house for chametz by candlelight the night before Passover begins, in a ritual called bedikat chametz.",
     "It's customary to search the house for chametz by candlelight the night after Passover ends, in a ritual called bedikat chametz.",
     "Bedikat chametz happens before Passover starts, as final preparation, not after the holiday ends."),
    ("holidays",
     "At the Passover seder, the four cups of wine are traditionally drunk while reclining to one side, a symbol of freedom.",
     "At the Passover seder, the four cups of wine are traditionally drunk while standing at attention, a symbol of readiness.",
     "Reclining while drinking the four cups symbolizes freedom, echoing how free people (rather than slaves) would recline to eat."),
    ("holidays",
     "The Jewish calendar includes several minor fast days beyond Yom Kippur, such as the Fast of Gedaliah and the Fast of Esther.",
     "Yom Kippur is the only fast day in the Jewish calendar; no other day traditionally involves fasting.",
     "Several minor fast days exist alongside Yom Kippur, though they're generally observed less strictly."),
    ("holidays",
     "The Fast of Esther is traditionally observed the day before Purim.",
     "The Fast of Esther is traditionally observed the day after Purim, as a day of recovery.",
     "The Fast of Esther precedes Purim, tied to the biblical Esther's own fast before approaching the king."),
    ("holidays",
     "The Ten Days of Repentance span from Rosh Hashanah to Yom Kippur, a period of heightened introspection.",
     "The Ten Days of Repentance span from Passover to Shavuot, a period of counting the Omer.",
     "The Ten Days of Repentance are the ten days between Rosh Hashanah and Yom Kippur; the Passover-to-Shavuot period is a separate 49-day count."),
    ("holidays",
     "During parts of the Omer count and the Three Weeks before Tisha B'Av, traditional customs include avoiding weddings and other festive events.",
     "During the Omer count and the Three Weeks before Tisha B'Av, tradition specifically encourages scheduling weddings and other festive events.",
     "These periods are traditionally treated as times of partial mourning, during which festive events like weddings are generally avoided."),

    # --- ritual_objects (laws and customs) ---
    ("ritual_objects",
     "Tzitzit, the fringes on a tallit or four-cornered garment, are traditionally supposed to include one blue thread, based on a dye called tekhelet.",
     "Tzitzit are traditionally supposed to include one red thread, based on a dye derived from certain berries.",
     "The Torah specifies a thread of tekhelet, a blue dye, among the white tzitzit strings — not a red berry dye."),
    ("ritual_objects",
     "Some observant Jewish men wear a four-cornered fringed garment under their clothing throughout the day, not just during formal prayer.",
     "The four-cornered fringed garment is worn only once a year, during Yom Kippur services.",
     "Many who observe this custom wear the garment daily, under everyday clothes, rather than on a single annual occasion."),
    ("ritual_objects",
     "A chanukiah's candles are traditionally arranged in a single row at equal height, unlike the branched menorah used in the ancient Temple.",
     "A chanukiah's candles are traditionally arranged in a circular pattern, unlike the branched menorah used in the ancient Temple.",
     "Jewish law traditionally requires Hanukkah lights to be level and in a row, distinguishing the chanukiah from the Temple menorah's shape."),
    ("ritual_objects",
     "Mezuzah scrolls are traditionally checked periodically by a scribe, since damaged or faded lettering can invalidate them.",
     "Mezuzah scrolls, once affixed, are never checked again, since Jewish law considers them permanently valid regardless of condition.",
     "Because the scroll's condition matters, periodic scribal checks are a traditional practice, not a one-time affair."),
    ("ritual_objects",
     "Traditional Torah scrolls are rolled by hand onto two wooden rollers called atzei chaim, meaning 'trees of life.'",
     "Traditional Torah scrolls are bound in leather like a book, using no wooden rollers.",
     "Torah scrolls use wooden rollers (atzei chaim) rather than book-style binding."),

    # --- lifecycle (laws and customs) ---
    ("lifecycle",
     "A traditional Jewish wedding ceremony includes seven blessings, called Sheva Brachot, recited over the couple.",
     "A traditional Jewish wedding ceremony includes three blessings, called Shalosh Brachot, recited over the couple.",
     "Seven blessings (Sheva Brachot), not three, are the traditional wedding blessings."),
    ("lifecycle",
     "Before a traditional Jewish wedding, it's customary for the groom to formally identify the bride before the ceremony, in a custom called bedeken.",
     "Before a traditional Jewish wedding, it's customary for the bride to blindfold the groom to symbolically test his trust, in a custom called bedeken.",
     "Bedeken involves the groom veiling and identifying the bride, traditionally recalling a mix-up in the biblical Jacob and Leah story."),
    ("lifecycle",
     "A ketubah is a traditional Jewish marriage contract outlining the groom's obligations to the bride.",
     "A ketubah is a traditional Jewish marriage contract outlining only the bride's obligations to the groom's family.",
     "The ketubah traditionally spells out the groom's financial and marital obligations to the bride, not the reverse."),
    ("lifecycle",
     "It's customary for a Jewish couple to fast on their wedding day until the ceremony, treated somewhat like a personal day of new beginnings.",
     "It's customary for a Jewish couple to feast continuously from morning until the ceremony on their wedding day.",
     "Many couples traditionally fast, not feast, before the chuppah, similar in spirit to Yom Kippur."),
    ("lifecycle",
     "Mourners traditionally sit on low stools or the floor during the shiva period, as a physical expression of grief.",
     "Mourners traditionally sit on the highest chair available during the shiva period, to be seen by visitors.",
     "Sitting low, not high, is the traditional posture of mourning during shiva."),
    ("lifecycle",
     "Mirrors in the house of mourning are traditionally covered during shiva.",
     "Mirrors in the house of mourning are traditionally polished and prominently displayed during shiva.",
     "Covering mirrors during shiva is a well-known mourning custom, the opposite of displaying them."),
    ("lifecycle",
     "It's traditional for visitors during shiva to wait for the mourner to speak first, rather than initiating conversation.",
     "It's traditional for visitors during shiva to bring gifts and initiate cheerful conversation to lift the mourner's spirits.",
     "Shiva visiting etiquette traditionally has visitors follow the mourner's lead in conversation, not the other way around."),
    ("lifecycle",
     "Yahrzeit, the annual anniversary of a loved one's death, is traditionally marked by lighting a candle that burns for 24 hours.",
     "Yahrzeit is a weekly anniversary of a loved one's death, marked every week with a small memorial meal.",
     "Yahrzeit is observed annually, not weekly, and traditionally centers on a 24-hour memorial candle."),

    # --- prayer (laws and customs) ---
    ("prayer",
     "Traditional daily prayer in many communities is structured around three services: morning (Shacharit), afternoon (Mincha), and evening (Maariv).",
     "Traditional daily prayer consists of a single combined service recited once a day, in the evening.",
     "The three-service structure — Shacharit, Mincha, and Maariv — is the traditional daily prayer framework."),
    ("prayer",
     "In many communities, a portion of the Torah is also read during morning services on Mondays and Thursdays, not only on Shabbat.",
     "The Torah is read publicly only once a week, exclusively on Shabbat, with no readings on any other day.",
     "Monday and Thursday morning Torah readings are a long-standing traditional practice alongside the main Shabbat reading."),
    ("prayer",
     "The Priestly Blessing (Birkat Kohanim) is traditionally recited by those tracing descent from the ancient priestly line, with hands held in a distinctive shape.",
     "The Priestly Blessing is traditionally recited by the youngest member of the congregation, with hands simply clasped together.",
     "Birkat Kohanim is specifically tied to Kohanim (priestly lineage) and a distinctive hand position, not the youngest congregant."),
    ("prayer",
     "A traditional teaching holds that a Jewish person should aim to recite 100 blessings over the course of each day.",
     "A traditional teaching holds that a Jewish person should recite exactly seven blessings over the course of each day.",
     "The traditional figure cited is 100 daily blessings, not seven."),

    # --- synagogue (laws and customs) ---
    ("synagogue",
     "In traditionally Orthodox synagogues, men and women often sit in separate sections divided by a partition called a mechitza, while many Reform and Conservative synagogues have mixed seating.",
     "All synagogues, across every Jewish movement, require a mechitza dividing men's and women's seating.",
     "Practice varies by movement: Orthodox synagogues commonly use a mechitza, while many Reform and Conservative synagogues do not."),
    ("synagogue",
     "Torah reading in synagogue is traditionally accompanied by an aliyah, where an individual is called up to recite blessings before and after each section.",
     "Torah reading in synagogue is traditionally done in complete silence, with congregants specifically forbidden to recite any blessings.",
     "Being called up for an aliyah, including reciting blessings, is a standard part of the Torah reading, not something forbidden."),

    # --- texts (halakhic literature) ---
    ("texts",
     "The Shulchan Aruch, compiled by Rabbi Yosef Karo in the 16th century, is one of the most widely referenced codes of Jewish law.",
     "The Shulchan Aruch was compiled in the 20th century as Israel's first civil legal code.",
     "The Shulchan Aruch is a 16th-century code of religious law, not a modern state's civil code."),
    ("texts",
     "Halakha is the term for traditional Jewish religious law, covering areas from prayer to diet to business ethics.",
     "Halakha refers specifically to Jewish mystical teachings, unrelated to religious law or daily practice.",
     "Halakha means Jewish law broadly, not a specific mystical tradition."),
    ("texts",
     "The Talmud records not only legal rulings but also dissenting minority opinions, preserving disagreements between rabbis for later study.",
     "The Talmud records only the final, agreed-upon legal rulings, with all dissenting rabbinic opinions removed.",
     "Minority and rejected opinions are deliberately preserved in the Talmud alongside accepted rulings, not deleted."),
    ("texts",
     "Much of the Babylonian Talmud was developed by rabbinic academies in Babylon in the centuries after the Second Temple's destruction.",
     "Jewish legal scholarship stopped entirely after the Second Temple's destruction in 70 CE.",
     "Rabbinic legal scholarship continued and flourished after 70 CE, notably producing the Babylonian Talmud over subsequent centuries."),

    # --- history (legal institutions) ---
    ("history",
     "The Sanhedrin was an ancient rabbinic court and legislative body; the Great Sanhedrin traditionally had 71 members.",
     "The Sanhedrin was an ancient royal court composed exclusively of the king's family members, unrelated to religious law.",
     "The Sanhedrin was a rabbinic legal body, traditionally numbering 71 members, not a royal family council."),
]
