# Batch 11: standalone FALSE statements, written in direct response to
# feedback that the paired true/false-with-one-word-changed style felt
# "pedantic... more English comprehension than Jewish general knowledge."
# These are short, single-claim, wholesale-false statements — plausible
# misconceptions someone might actually hold, not sentences that hinge on
# spotting one swapped word buried in a long clause.

ENTRIES = [
    ("kashrut",
     "Kosher certification means a rabbi has personally blessed the food product.",
     "Kosher certification confirms the ingredients and production process meet dietary law requirements — it isn't a blessing ceremony performed by a rabbi."),
    ("kashrut",
     "Kosher dietary laws exist purely for health and hygiene reasons, with no religious basis.",
     "Traditional authorities generally treat kosher laws as religious commandments followed as an act of observance, not primarily as a hygiene system."),
    ("kashrut",
     "Kosher fish must be cooked before it can be considered kosher; raw fish is never kosher.",
     "A fish's kosher status depends on having fins and scales, not on whether it's cooked — raw kosher fish, as in sushi, is still kosher."),
    ("kashrut",
     "The only requirement for kosher food is which animals are eaten — there are no rules about how food is prepared.",
     "Kosher law also covers preparation, such as separating meat and dairy and how animals are slaughtered, not just which species are eaten."),
    ("kashrut",
     "Fruits and vegetables can never be considered kosher — only meat and dairy products can be kosher-certified.",
     "Fruits and vegetables are generally kosher by default, and certification still commonly applies to them, largely around processing and insect-checking."),
    ("ritual_objects",
     "A mezuzah is traditionally worn as a necklace.",
     "A mezuzah is a case affixed to a doorpost, not a piece of jewelry worn on the body."),
    ("ritual_objects",
     "Tefillin are traditionally worn continuously, day and night, including while sleeping.",
     "Tefillin are traditionally worn during weekday morning prayer and removed afterward, not worn continuously."),
    ("texts",
     "The Torah was originally written in Yiddish.",
     "The Torah was written in Hebrew (with some later Jewish texts in Aramaic); Yiddish developed many centuries afterward as a separate language."),
    ("texts",
     "The Talmud and the Torah are simply two different names for the same text.",
     "The Torah and the Talmud are distinct texts from different eras — the Talmud is later rabbinic commentary and law built upon the Torah."),
    ("texts",
     "The Mishnah was written many centuries before the Torah.",
     "The Mishnah, compiled around 200 CE, came many centuries after the Torah, not before it."),
    ("lifecycle",
     "A Bar Mitzvah can only take place in Israel.",
     "A Bar Mitzvah is a coming-of-age milestone that can be marked wherever a Jewish community exists, not only in Israel."),
    ("lifecycle",
     "Jewish weddings are traditionally private ceremonies held with no guests present.",
     "Jewish weddings are traditionally public, festive events attended by family and community."),
    ("prayer",
     "Jewish tradition considers praying alone to be preferable to praying with a community.",
     "Communal prayer, especially with a minyan, is traditionally considered preferable to praying alone."),
    ("prayer",
     "The purpose of Jewish prayer is exclusively to request personal wealth from God.",
     "Traditional Jewish prayer includes praise, gratitude, and requests covering wellbeing well beyond material wealth."),
    ("synagogue",
     "Anyone can become a rabbi simply by declaring themselves one, with no study required.",
     "Traditional rabbinic ordination requires extensive study, not simple self-declaration."),
    ("holidays",
     "The shofar is traditionally blown throughout the month of Nisan, the month of Passover.",
     "The shofar is centrally associated with Elul and the High Holidays, not the month of Nisan."),
    ("holidays",
     "Purim is a solemn day of mourning and fasting.",
     "Purim is one of the most joyous, festive holidays in the Jewish calendar, not a day of mourning."),
    ("holidays",
     "Rosh Hashanah marks the beginning of the secular new year on January 1st.",
     "Rosh Hashanah is the Jewish new year, observed on a date set by the Hebrew calendar, not January 1st."),
    ("holidays",
     "Passover celebrates the Jewish people receiving the Ten Commandments at Mount Sinai.",
     "Passover commemorates the Exodus from Egypt; the giving of the Torah at Sinai is commemorated by Shavuot instead."),
    ("diaspora",
     "Historically, Jewish communities existed only in the Middle East, with no significant presence anywhere else in the world.",
     "Jewish communities have a long documented history across Europe, Africa, Asia, and later the Americas, not just the Middle East."),
    ("symbols",
     "The Star of David has been the primary symbol of Judaism since the time of the Ten Commandments.",
     "While the six-pointed star shape itself is ancient, its widespread adoption specifically as a symbol of Judaism is a much later development, mainly from the medieval period onward."),
    ("symbols",
     "The number 18 (chai) is considered unlucky in Jewish tradition.",
     "18 is considered a lucky, symbolically significant number in Jewish tradition, linked to the word 'chai' meaning life — not unlucky."),
    ("language",
     "The word 'kosher' is originally an English word with no Hebrew origin.",
     "'Kosher' comes from the Hebrew word 'kasher,' meaning fit or proper, not from English."),
    ("history",
     "The Western Wall is located in Rome.",
     "The Western Wall is located in Jerusalem, not Rome."),
    ("history",
     "The Dead Sea Scrolls were written in the 20th century.",
     "The Dead Sea Scrolls are ancient manuscripts dating back roughly two thousand years, not modern documents."),
]
