# Batch 4: ~51 new true/false pairs, continuing the laws/customs emphasis
# (kashrut, Shabbat, holiday observance, ritual objects, lifecycle rituals,
# prayer, synagogue roles, halakhic texts), with a few word-origin facts
# under "language" and a charity-teaching fact under "people".

PAIRS = [
    # --- kashrut ---
    ("kashrut",
     "Some kosher standards require chalav Yisrael supervision for dairy products, meaning a Jewish person observed the milking process.",
     "All dairy products are automatically kosher regardless of any supervision during milking.",
     "Chalav Yisrael is a real, stricter kosher dairy standard tied to supervised milking, not an automatic default."),
    ("kashrut",
     "The knife used for kosher slaughter, called a chalaf, must be perfectly smooth with no nicks, traditionally checked by hand and fingernail before each use.",
     "The knife used for kosher slaughter must be serrated with small teeth, similar to a saw.",
     "A chalaf must be checked smooth and flawless; a serrated blade would be invalid for kosher slaughter."),
    ("kashrut",
     "Eggs are traditionally checked for blood spots before use, since an egg containing one may need to be discarded or have the spot removed, depending on custom.",
     "Eggs are always kosher no matter what, since eggs are considered a neutral (pareve) food regardless of contents.",
     "Blood spots in eggs raise a real kashrut concern; eggs aren't automatically acceptable regardless of what's inside."),
    ("kashrut",
     "Fruit from a tree's first three years of growth, called orlah, is traditionally not eaten under Jewish law.",
     "Fruit from a tree's first three years of growth is specifically required to be eaten first, before any older fruit.",
     "Orlah fruit is traditionally avoided during those first three years, not prioritized for eating."),
    ("kashrut",
     "Shmita is a sabbatical year observed every seven years in the Land of Israel, during which agricultural land is traditionally left to rest.",
     "Shmita is a sabbatical year observed every seven years, during which all business activity worldwide traditionally stops.",
     "Shmita specifically concerns agricultural land in Israel resting, not a worldwide halt to all business."),
    ("kashrut",
     "It's a traditional custom for some Jews to donate a tenth of their income to charity, a practice called ma'aser kesafim.",
     "It's a traditional custom for some Jews to donate half of their income to charity, a practice called ma'aser kesafim.",
     "Ma'aser traditionally refers to a tenth (10%), not half, of one's income."),
    ("kashrut",
     "Gelatin derived from non-kosher animal sources is not kosher, which is why some candies and marshmallows require special kosher certification.",
     "Gelatin is always kosher regardless of its source animal, since it's considered a processed, neutral substance.",
     "Gelatin's kosher status depends on its source; non-kosher animal sources make it non-kosher despite processing."),
    ("kashrut",
     "Kosher supervisors, called mashgichim, sometimes stay on-site throughout a food production run to provide continuous supervision.",
     "Kosher certification is granted permanently after a single visit, with no need for any ongoing supervision.",
     "Some kosher certifications require continuous, not one-time, supervision, sometimes with a mashgiach present throughout production."),
    ("kashrut",
     "Kosher cooking traditionally classifies foods into three categories: meat (fleishig), dairy (milchig), and neutral (pareve).",
     "Kosher cooking recognizes only two categories of food: kosher and non-kosher, with no further classification.",
     "The fleishig/milchig/pareve three-way classification is central to how kosher kitchens are organized."),
    ("kashrut",
     "In strictly observant homes, Passover kitchens are sometimes entirely converted for the week using dedicated Passover-only dishes and utensils stored the rest of the year.",
     "Passover kitchens use the exact same everyday dishes and utensils as the rest of the year, with no special preparation required.",
     "Many observant households keep a separate set of Passover-only kitchenware specifically to avoid any chametz contamination."),

    # --- shabbat ---
    ("shabbat",
     "Shabbat candles are traditionally lit about 18 minutes before sunset on Friday.",
     "Shabbat candles are traditionally lit exactly at midnight on Friday.",
     "The traditional lighting time is shortly before sunset, roughly 18 minutes, not midnight."),
    ("shabbat",
     "It's traditional for the Havdalah wine cup to be filled to overflowing, symbolizing a wish for a full week of blessing.",
     "It's traditional for the Havdalah wine cup to be left mostly empty, symbolizing humility for the week ahead.",
     "Overflowing the cup, not leaving it empty, is the traditional symbol of hoped-for abundance."),
    ("shabbat",
     "Under specific traditional rules, a non-Jewish person may sometimes be asked to perform a Shabbat-prohibited task, a scenario sometimes called a 'Shabbos goy.'",
     "It's traditionally forbidden under all circumstances for anyone, Jewish or not, to perform any task in a Jewish home on Shabbat.",
     "There's a real, detailed body of traditional rules covering when a non-Jewish person may be asked to help with a Shabbat-prohibited task."),
    ("shabbat",
     "The braided Havdalah candle is traditionally extinguished by dipping it in the leftover wine after the blessing is recited.",
     "The braided Havdalah candle is traditionally left to burn out completely on its own, and extinguishing it early is forbidden.",
     "Dipping the candle in spilled wine is the traditional way to put it out at the end of Havdalah."),

    # --- holidays ---
    ("holidays",
     "Rosh Chodesh, marking the start of a new Hebrew month, is traditionally treated as a minor holiday with its own added prayers.",
     "Rosh Chodesh, marking the start of a new Hebrew month, has no religious significance and no special prayers are added.",
     "Rosh Chodesh carries real minor-holiday status, with specific additions to the prayer service."),
    ("holidays",
     "The Hebrew calendar is lunisolar, following the moon for months while periodically adding a leap month to stay aligned with the solar year.",
     "The Hebrew calendar is purely solar, identical in structure to the Gregorian calendar, with no lunar basis.",
     "The Hebrew calendar tracks lunar months but periodically corrects for the solar year with an added month, unlike a purely solar calendar."),
    ("holidays",
     "A Hebrew leap year adds an entire extra month, called Adar II, rather than just an extra day.",
     "A Hebrew leap year adds a single extra day, similar to a Gregorian leap year.",
     "Hebrew leap years add a full 13th month, not a single extra day."),
    ("holidays",
     "Purim is celebrated a day later, on the 15th of Adar, in cities that were historically walled at the time of Joshua, most famously Jerusalem — a version called Shushan Purim.",
     "Purim is celebrated identically on the same date everywhere in the world, with no city-based exceptions.",
     "Walled cities like Jerusalem traditionally observe Purim a day later than the rest of the world."),
    ("holidays",
     "The Kol Nidrei prayer, recited at the start of Yom Kippur evening services, addresses the annulment of vows.",
     "The Kol Nidrei prayer, recited at the start of Yom Kippur evening services, is a joyful hymn celebrating the new year.",
     "Kol Nidrei is a solemn legal-style declaration about vows, not a celebratory new year hymn."),
    ("holidays",
     "Yizkor, a memorial prayer service for the deceased, is traditionally recited on Yom Kippur and several other major holidays.",
     "Yizkor, a memorial prayer service, is traditionally recited only at funerals, never during holidays.",
     "Yizkor is recited during specific holiday services across the year, not exclusively at funerals."),
    ("holidays",
     "On Sukkot, the etrog is traditionally inspected carefully for blemishes, with a perfect, unblemished etrog considered especially prized.",
     "On Sukkot, the etrog is traditionally eaten raw as the primary festive meal food, similar to how apples are eaten on Rosh Hashanah.",
     "The etrog is used ritually as one of the Four Species, not eaten as a festive meal centerpiece."),
    ("holidays",
     "During most of the Omer count, it's traditional to refrain from haircuts and weddings, except for a customary break on Lag BaOmer.",
     "During the entire Omer count, it's traditional to get a fresh haircut every single day.",
     "The Omer period traditionally involves avoiding haircuts, with Lag BaOmer serving as a notable exception, not a daily haircut custom."),
    ("holidays",
     "Simchat Torah includes a custom of dancing with the Torah scrolls, called hakafot.",
     "Simchat Torah includes a custom of solemn silent reading of the Torah scrolls without any music or dancing.",
     "Hakafot — joyful dancing with the Torah scrolls — is a defining custom of Simchat Torah, not silent reading."),
    ("holidays",
     "Tisha B'Av traditionally includes sitting on low stools, similar to the shiva mourning custom, since it's considered a day of national mourning.",
     "Tisha B'Av traditionally includes a festive meal eaten while standing, to symbolize resilience.",
     "Tisha B'Av borrows mourning customs like sitting low, rather than featuring a festive standing meal."),
    ("holidays",
     "The Shabbat immediately before Passover has a special name, Shabbat HaGadol ('the Great Sabbath').",
     "The Shabbat immediately before Passover has a special name, Shabbat HaKatan ('the Small Sabbath').",
     "The pre-Passover Shabbat is traditionally called Shabbat HaGadol, not Shabbat HaKatan."),
    ("holidays",
     "The Shabbat before Yom Kippur has a special name, Shabbat Shuvah ('Sabbath of Return'), tied to its traditional theme of repentance.",
     "The Shabbat before Yom Kippur has a special name, Shabbat Shalom, a name shared with the ordinary weekly greeting.",
     "The pre-Yom Kippur Shabbat is specifically called Shabbat Shuvah; 'Shabbat Shalom' is just the everyday greeting, not a holiday name."),

    # --- ritual_objects ---
    ("ritual_objects",
     "A gartel, a ceremonial belt some observant Jewish men wear during prayer, is meant to symbolically separate the heart from the lower body.",
     "A gartel is a ceremonial belt some observant Jewish men wear, meant to hold up prayer books during services.",
     "The gartel's traditional purpose is a symbolic separation during prayer, not holding books."),
    ("ritual_objects",
     "A kittel, a simple white robe, is traditionally worn by some Jews on Yom Kippur and at their own wedding, among other occasions.",
     "A kittel is a colorful ceremonial robe worn exclusively by rabbis during Torah reading.",
     "A kittel is plain white and worn by ordinary worshippers on specific solemn or significant occasions, not a rabbi-only Torah-reading garment."),
    ("ritual_objects",
     "A challah cover, a decorative cloth, is traditionally placed over the two loaves of Shabbat bread until they're ready to be blessed and cut.",
     "A challah cover is traditionally placed underneath the bread, never over it, as a serving tray.",
     "The cover traditionally goes over the loaves, concealing them until the blessing, not underneath as a tray."),

    # --- lifecycle ---
    ("lifecycle",
     "Conversion to Judaism traditionally involves study, immersion in a ritual bath called a mikveh, and for men, ritual circumcision or a symbolic equivalent.",
     "Conversion to Judaism traditionally requires no formal process, immersion, or ceremony of any kind.",
     "Traditional conversion involves a defined process, including study and mikveh immersion, not an informal or ceremony-free path."),
    ("lifecycle",
     "A mikveh is a ritual bath used for several purposes, including some conversions and, in many traditional communities, family purity practices.",
     "A mikveh is a decorative fountain found only in synagogue courtyards, without any ritual use.",
     "A mikveh is a ritual immersion pool with defined religious uses, not a purely decorative fountain."),
    ("lifecycle",
     "Jewish divorce is traditionally finalized through a legal document called a get, given by the husband to the wife.",
     "Jewish divorce traditionally requires no legal document; a verbal declaration from either spouse alone is sufficient.",
     "A get is a specific written legal document central to a traditional Jewish divorce, not a mere verbal statement."),
    ("lifecycle",
     "Traditionally, a baby boy is given his Hebrew name at his brit milah (circumcision ceremony), while a baby girl is often named in a synagogue ceremony.",
     "Traditionally, only baby girls receive a formal Hebrew naming ceremony; boys receive their Hebrew name automatically with no ceremony.",
     "Both boys and girls traditionally have naming ceremonies, just held in different contexts."),
    ("lifecycle",
     "In some communities, it's customary to hold a festive gathering called a shalom zachar on the Friday night after a baby boy's birth, before the brit milah.",
     "In some communities, it's customary to hold a silent fast on the Friday night after a baby boy's birth, before the brit milah.",
     "Shalom zachar is traditionally a festive welcoming gathering, not a fast."),
    ("lifecycle",
     "In many communities, it's traditional for a bride to circle the groom seven times during the wedding ceremony.",
     "In many communities, it's traditional for the groom to circle the bride seven times during the wedding ceremony.",
     "The traditional circling custom has the bride circling the groom, not the reverse."),

    # --- prayer ---
    ("prayer",
     "The Shabbat and holiday morning service traditionally includes an additional prayer called Musaf, not recited on ordinary weekdays.",
     "Musaf is a prayer recited every weekday morning, in addition to the standard daily service.",
     "Musaf is specifically a Shabbat-and-holiday addition, not a regular weekday prayer."),
    ("prayer",
     "Traditional Jewish prayer is largely centered on a fixed liturgy read from a prayer book called a siddur.",
     "Traditional Jewish prayer strictly forbids the use of any prayer book, requiring prayers to be entirely improvised each time.",
     "A fixed liturgy recited from a siddur, not free improvisation, is the traditional structure of Jewish prayer."),
    ("prayer",
     "Kaddish, recited in several forms throughout Jewish prayer services, is written primarily in Aramaic rather than Hebrew.",
     "Kaddish, recited in several forms throughout Jewish prayer services, is written primarily in Yiddish.",
     "Kaddish is mostly in Aramaic, a related but distinct language from both Hebrew and Yiddish."),
    ("prayer",
     "Traditional Jewish prayer often involves gentle swaying back and forth, a practice sometimes called shuckling.",
     "Traditional Jewish prayer requires standing perfectly still without any movement at all times.",
     "Shuckling, rhythmic swaying, is a well-known traditional feature of Jewish prayer, not stillness."),
    ("prayer",
     "Birkat HaMazon, grace after meals, is a traditional set of blessings recited after eating a meal containing bread.",
     "Birkat HaMazon, grace after meals, is traditionally recited before eating any meal, not after.",
     "As its name suggests, Birkat HaMazon is recited after the meal, not beforehand."),

    # --- synagogue ---
    ("synagogue",
     "A gabbai is a synagogue role responsible for organizing the Torah reading service, such as calling people up for aliyot.",
     "A gabbai is a synagogue role responsible only for cleaning the building, unrelated to religious services.",
     "A gabbai has specific ritual responsibilities around the Torah service, not just building maintenance."),
    ("synagogue",
     "Many synagogues maintain a genizah, a storage space for worn-out sacred texts that can't simply be thrown away because they contain God's name.",
     "Many synagogues maintain a genizah, a display case for the rabbi's personal awards and certificates.",
     "A genizah is traditionally for retiring sacred texts respectfully, not for displaying personal awards."),
    ("synagogue",
     "A cantor, or chazzan, is a trained singer who traditionally leads congregational prayer melodically.",
     "A cantor, or chazzan, is a synagogue's chief financial officer, responsible for managing donations.",
     "A chazzan's traditional role is musically leading prayer, not handling synagogue finances."),
    ("synagogue",
     "It's traditional for the person leading prayer services to face the same direction as the congregation, toward Jerusalem, rather than facing the congregation.",
     "It's traditional for the person leading prayer services to face the congregation directly, similar to a performer facing an audience.",
     "The prayer leader traditionally faces the same direction as everyone else, not the congregation itself."),

    # --- texts ---
    ("texts",
     "Pirkei Avot ('Ethics of the Fathers') is a Mishnaic tractate focused on ethical teachings and wisdom sayings rather than legal rulings.",
     "Pirkei Avot is a Mishnaic tractate focused exclusively on the laws of kosher slaughter.",
     "Pirkei Avot is specifically an ethical and wisdom text, distinct from the Mishnah's legal tractates on topics like slaughter."),
    ("texts",
     "The Zohar, a foundational text of Jewish mysticism, is traditionally associated with the 2nd-century sage Rabbi Shimon bar Yochai, though most scholars date its writing to 13th-century Spain.",
     "The Zohar, a foundational text of Jewish mysticism, was definitively written and published in 20th-century New York.",
     "Traditional attribution places the Zohar in antiquity, while modern scholarship traces its writing to medieval Spain — not 20th-century New York."),
    ("texts",
     "Midrash refers to a genre of rabbinic literature that interprets biblical stories, often filling narrative gaps with additional teachings and parables.",
     "Midrash refers exclusively to a genre of rabbinic literature consisting only of mathematical calculations for the Hebrew calendar.",
     "Midrash is narrative and interpretive in nature, not a calendar-calculation genre."),
    ("texts",
     "Responsa literature (she'elot u-teshuvot) consists of written questions sent to rabbis about Jewish law, along with their formal written answers, spanning many centuries.",
     "Responsa literature consists of anonymous complaints submitted to synagogue boards, unrelated to Jewish law.",
     "Responsa are a long legal-literary tradition of formal Q&A on Jewish law, not anonymous complaints."),

    # --- language ---
    ("language",
     "Tzedakah, often translated as 'charity,' comes from a Hebrew root meaning 'justice' or 'righteousness,' reflecting its status as an obligation.",
     "Tzedakah, often translated as 'charity,' comes from a Hebrew root meaning 'gift,' reflecting that it's considered a fully optional act.",
     "Tzedakah's root ties it to justice/righteousness, framing it as an obligation rather than pure optional generosity."),
    ("language",
     "The word 'Talmud' itself means 'teaching' or 'study' in Hebrew.",
     "The word 'Talmud' itself means 'law court' in Hebrew.",
     "'Talmud' derives from a root meaning to learn or teach, not a term for a law court."),

    # --- people ---
    ("people",
     "Maimonides described a traditional eight-level hierarchy of charitable giving, with the highest level being helping someone become self-sufficient.",
     "Maimonides described a traditional eight-level hierarchy of charitable giving, with the highest level being giving anonymously to a stranger on the street.",
     "Anonymous giving ranks highly in Maimonides' hierarchy, but the top level is specifically enabling someone to become self-supporting."),
]
