# Batch 15: Jewish pop culture — Eurovision, celebrities, film/TV, and
# culturally iconic food moments. New category: pop_culture.

PAIRS = [
    ("pop_culture",
     "Israel has won the Eurovision Song Contest four times, most recently in 2018.",
     "Israel has never won the Eurovision Song Contest.",
     "Israel has won Eurovision four times: 1978, 1979, 1998, and 2018.",
     2),
    ("pop_culture",
     "Dana International, who won Eurovision for Israel in 1998, was the contest's first openly transgender winner.",
     "Dana International represented Israel at Eurovision several times but never won.",
     "Dana International won Eurovision 1998 with 'Diva,' becoming the contest's first openly transgender winner.",
     3),
    ("pop_culture",
     "Netta won Eurovision 2018 for Israel with the song 'Toy.'",
     "Netta won Eurovision 2018 for Israel with a cover of a classic Israeli folk song.",
     "Netta's winning 2018 entry was an original song called 'Toy,' not a cover.",
     2),
    ("pop_culture",
     "Because Israel won Eurovision 2018, the following year's contest was hosted in Tel Aviv.",
     "Because Israel won Eurovision 2018, the following year's contest was hosted in London.",
     "Eurovision tradition has the winning country host the following year's contest; Israel's 2018 win brought Eurovision 2019 to Tel Aviv.",
     3),
    ("pop_culture",
     "Adam Sandler wrote and performs 'The Chanukah Song,' a comedic song listing celebrities who are Jewish.",
     "Adam Sandler wrote and performs 'The Chanukah Song,' a serious religious hymn performed in synagogues.",
     "'The Chanukah Song' is a comedy song, not a liturgical hymn.",
     1),
    ("pop_culture",
     "Actress Natalie Portman was born in Jerusalem, Israel.",
     "Actress Natalie Portman was born in Los Angeles, California.",
     "Natalie Portman was born in Jerusalem before her family moved to the United States when she was a child.",
     2),
    ("pop_culture",
     "Actress Gal Gadot, known for playing Wonder Woman, served in the Israel Defense Forces before her acting career.",
     "Actress Gal Gadot, known for playing Wonder Woman, has never lived in Israel.",
     "Gal Gadot is Israeli and completed mandatory IDF service before becoming an actress.",
     2),
    ("pop_culture",
     "Rapper Drake, who had a bar mitzvah as a teenager, has Jewish heritage through his mother.",
     "Rapper Drake has said in interviews that he has no connection to Judaism at all.",
     "Drake's mother is Jewish, and he has spoken and joked publicly about having had a bar mitzvah.",
     2),
    ("pop_culture",
     "Bob Dylan, born Robert Zimmerman, is Jewish and won the Nobel Prize in Literature in 2016.",
     "Bob Dylan, born Robert Zimmerman, is Jewish and won an Olympic gold medal in 2016.",
     "Bob Dylan won the 2016 Nobel Prize in Literature, not an Olympic medal.",
     2),
    ("pop_culture",
     "Barbra Streisand won the Academy Award for Best Actress for her role in 'Funny Girl.'",
     "Barbra Streisand won the Academy Award for Best Actress for her role in 'Yentl.'",
     "Streisand won Best Actress for Funny Girl (1968); she directed and starred in Yentl but didn't win Best Actress for it.",
     3),
    ("pop_culture",
     "Actress Mila Kunis was born in Ukraine and is Jewish.",
     "Actress Mila Kunis was born in Russia and is not Jewish.",
     "Mila Kunis was born in Chernivtsi, Ukraine, to a Jewish family, before emigrating to the US as a child.",
     3),
    ("pop_culture",
     "The musical 'Fiddler on the Roof' is based on stories by Yiddish author Sholem Aleichem about a milkman named Tevye.",
     "The musical 'Fiddler on the Roof' is based on a true crime memoir written in the 1980s.",
     "Fiddler on the Roof adapts Sholem Aleichem's Tevye stories, written decades before the musical existed.",
     3),
    ("pop_culture",
     "Katz's Delicatessen, a famous Jewish deli in New York City, appeared in the movie 'When Harry Met Sally.'",
     "Katz's Delicatessen, a famous Jewish deli in New York City, has never appeared in any film or TV show.",
     "Katz's Deli is the setting of the famous diner scene in When Harry Met Sally.",
     3),
    ("pop_culture",
     "'Saturday Night Live' has featured a recurring parody character called 'Hanukkah Harry,' a Hanukkah counterpart to Santa Claus.",
     "'Saturday Night Live' has never featured any Hanukkah-themed sketches or characters.",
     "Hanukkah Harry is a recurring SNL character, first appearing in a 1989 sketch.",
     3),
    ("pop_culture",
     "'Hava Nagila,' a song closely associated with Jewish celebrations, has been recorded or performed by many mainstream pop artists over the years.",
     "'Hava Nagila' has only ever been performed at Jewish weddings and has never been recorded commercially by any artist.",
     "Hava Nagila has been covered by a wide range of mainstream performers well beyond wedding settings.",
     2),
]
