# Batch 8: ~46 new true/false pairs. Deliberately steers clear of anything
# disputable or controversial — no modern politics, no persecution/conflict
# history, no contested denominational disputes. Sticks to well-documented
# religious practice, food and cultural customs, and word origins.

PAIRS = [
    # --- kashrut ---
    ("kashrut",
     "Kosher symbols sometimes include a 'P,' indicating a product has been specifically certified for Passover use.",
     "Kosher symbols sometimes include a 'P,' warning that a product contains pork byproducts.",
     "The 'P' marks Passover-specific certification; it has nothing to do with pork, which is never kosher regardless of labeling."),
    ("kashrut",
     "Before Passover, chametz that can't be disposed of is traditionally handled through mechirat chametz, a symbolic sale to a non-Jewish person, bought back after the holiday.",
     "Chametz that can't be disposed of before Passover is traditionally just thrown away, with no other legal mechanism available.",
     "Mechirat chametz, a formal symbolic sale, is the traditional legal mechanism for handling chametz that isn't feasible to discard."),
    ("kashrut",
     "'Glatt kosher' refers to a stricter kosher meat standard concerning the smoothness of an animal's lungs.",
     "'Glatt kosher' is a specific brand name belonging to one particular kosher certification company.",
     "Glatt (Yiddish/German for 'smooth') describes a lung-smoothness standard, not a company brand."),
    ("kashrut",
     "Fish require no ritual slaughter (shechita) to be kosher, unlike kosher land animals and birds.",
     "Fish require an even more elaborate ritual slaughter process than land animals to be considered kosher.",
     "Kosher fish are identified by having fins and scales; they don't require the shechita process land animals and birds do."),
    ("kashrut",
     "Many traditional authorities understand the Torah's kosher dietary laws as chukim — divine statutes followed out of obedience rather than laws with an obvious rational explanation.",
     "All rabbinic authorities traditionally and unanimously understand the Torah's kosher dietary laws as based purely on ancient food safety and hygiene concerns.",
     "Chukim is a real traditional category for commandments without an obvious rationale; a purely hygiene-based explanation isn't the traditional consensus view."),
    ("kashrut",
     "A 'pareve' (or parve) food contains neither meat nor dairy — such as fruit, vegetables, grains, fish, and eggs — and can traditionally be eaten with either.",
     "A 'pareve' food traditionally contains both meat and dairy together, specially prepared to bypass normal kosher separation rules.",
     "Pareve foods are neutral, containing neither meat nor dairy, not a special combination of both."),
    ("kashrut",
     "Honey is traditionally considered kosher despite coming from bees, which are not kosher insects, due to a specific traditional legal exception.",
     "Honey is traditionally not considered kosher under any circumstances, since it comes from bees, which are not kosher insects.",
     "Honey is a recognized traditional exception; its kosher status doesn't follow the general rule for products of non-kosher creatures."),

    # --- shabbat ---
    ("shabbat",
     "Bread at Shabbat meals is traditionally sprinkled with a bit of salt before being eaten, following the blessing.",
     "Bread at Shabbat meals is traditionally sprinkled with a bit of sugar before being eaten, following the blessing.",
     "Salt, not sugar, is the traditional addition to bread after the blessing, echoing an association with ancient Temple offerings."),
    ("shabbat",
     "On Friday night, it's traditional to recite 'Eshet Chayil' ('Woman of Valor'), a poem from Proverbs, in honor of the lady of the house.",
     "On Friday night, it's traditional to recite 'Eshet Chayil' in honor of the community's head rabbi.",
     "Eshet Chayil is traditionally recited in honor of the wife/mother of the household, not a rabbi."),
    ("shabbat",
     "It's customary to sing table songs called zemirot during Shabbat meals.",
     "It's customary to maintain complete silence during Shabbat meals, with singing specifically forbidden.",
     "Zemirot, traditional table songs, are a well-known feature of Shabbat meals, not a silent affair."),
    ("shabbat",
     "It's traditional in many families to recite a blessing over children, placing hands on their heads, as part of the Friday night Shabbat meal.",
     "It's traditional to bless children only on their birthdays, unrelated to the weekly Shabbat meal.",
     "Blessing children is a well-known weekly Friday night custom in many families, not limited to birthdays."),
    ("shabbat",
     "A 'Shabbat elevator,' sometimes installed in buildings with religious residents, automatically stops on every floor so passengers don't need to press buttons.",
     "A 'Shabbat elevator' is designed to move faster than a normal elevator, minimizing the time spent inside on Shabbat.",
     "A Shabbat elevator's defining feature is stopping automatically at every floor, avoiding the need to press buttons, not extra speed."),

    # --- holidays ---
    ("holidays",
     "On Sukkot, the lulav bundle is traditionally shaken in six directions during its blessing.",
     "On Sukkot, the lulav bundle is traditionally buried in the ground immediately after its blessing is recited.",
     "Shaking the lulav in six directions, not burying it, is the traditional practice after the blessing."),
    ("holidays",
     "It's traditional to eat dairy foods on Hanukkah, partly in memory of the story of Judith (Yehudit), separate from the oil-based fried food tradition.",
     "It's traditional to eat dairy foods on Purim in memory of the story of Judith (Yehudit).",
     "The dairy-food custom tied to Judith's story belongs to Hanukkah, not Purim."),
    ("holidays",
     "Shavuot traditionally includes an all-night Torah study custom called Tikkun Leil Shavuot.",
     "Yom Kippur traditionally includes an all-night Torah study custom called Tikkun Leil Shavuot, despite the name.",
     "Tikkun Leil Shavuot is specifically a Shavuot custom, as its name indicates, not a Yom Kippur one."),
    ("holidays",
     "It's traditional for children to receive Hanukkah gelt (money or chocolate coins) during Hanukkah.",
     "It's traditional for children to receive Hanukkah gelt (money or chocolate coins) during Passover.",
     "Hanukkah gelt is, as the name suggests, a Hanukkah custom, not a Passover one."),
    ("holidays",
     "Playing the dreidel game, where players wager nuts, coins, or chocolate on the spin's outcome, is a traditional Hanukkah pastime.",
     "Playing the dreidel game is traditionally reserved only for rabbis during formal synagogue services.",
     "The dreidel game is a widespread, informal Hanukkah pastime for players of all kinds, not a rabbis-only synagogue ritual."),
    ("holidays",
     "It's customary for some to wear white clothing on Yom Kippur, symbolizing purity.",
     "It's customary for some to wear black clothing on Yom Kippur, symbolizing mourning.",
     "White, not black, is the traditional symbolic clothing color associated with Yom Kippur's theme of purity."),
    ("holidays",
     "Some Sephardic and Mizrahi communities hold a special Tu BiShvat seder, involving specific fruits and blessings, paralleling the structure of a Passover seder.",
     "Some Sephardic and Mizrahi communities specifically forbid any special meal for Tu BiShvat, treating it as an entirely ordinary day.",
     "A structured Tu BiShvat seder is a real, documented custom in some communities, not a forbidden practice."),

    # --- ritual_objects ---
    ("ritual_objects",
     "A Kiddush cup is traditionally used specifically for the blessing recited over wine.",
     "A Kiddush cup is traditionally used specifically for washing hands before meals, unrelated to wine.",
     "A Kiddush cup is for the wine blessing; hand-washing uses a separate vessel entirely."),
    ("ritual_objects",
     "Many Jewish homes display a decorative piece with the Hebrew word 'Mizrach' on the eastern wall, indicating the direction of prayer toward Jerusalem for those living west of it.",
     "Many Jewish homes display a decorative piece with the Hebrew word 'Mizrach' on the western wall, indicating the direction away from Jerusalem.",
     "'Mizrach' means 'east' and is traditionally placed on the eastern wall by communities west of Jerusalem, not the western wall."),
    ("ritual_objects",
     "An etrog box, often ornately decorated, is traditionally used to protect the etrog from damage during Sukkot.",
     "An etrog box, often ornately decorated, is traditionally used to store tefillin when not in use.",
     "An etrog box is specifically made to protect the fragile etrog, not to store tefillin."),

    # --- lifecycle ---
    ("lifecycle",
     "A traditional pidyon haben ceremony involves the father symbolically giving five silver coins to a Kohen.",
     "A traditional pidyon haben ceremony involves the father symbolically giving five silver coins to a Levite.",
     "The coins are traditionally given to a Kohen, not a Levite, in the pidyon haben ceremony."),
    ("lifecycle",
     "It's traditional for the groom to be lifted on a chair and danced around during a Jewish wedding reception.",
     "It's traditional for the groom to remain seated silently throughout the entire wedding reception, with no dancing permitted.",
     "Lifting the groom (and often the bride) on a chair for festive dancing is a well-known traditional wedding custom."),
    ("lifecycle",
     "It's traditional for wedding guests to shout 'Mazel Tov' at the moment the groom breaks the glass underfoot.",
     "It's traditional for wedding guests to remain completely silent at the moment the groom breaks the glass underfoot.",
     "Breaking the glass is traditionally met with celebratory shouts of 'Mazel Tov,' not silence."),

    # --- prayer ---
    ("prayer",
     "It's traditional to bow slightly at specific points during the Amidah prayer, such as its opening and closing blessings.",
     "It's traditional to remain completely rigid, without any physical movement, throughout the entire Amidah prayer.",
     "Bowing at specific set points is a traditional part of the Amidah, not complete stillness throughout."),
    ("prayer",
     "A Mi Sheberach is a traditional prayer recited for someone who is ill or celebrating a special occasion, often said by name during Torah reading.",
     "A Mi Sheberach is a traditional prayer recited exclusively at funerals, mentioning the deceased by name.",
     "Mi Sheberach is typically for the living — for healing or celebration — not a funeral-specific prayer."),
    ("prayer",
     "Practice around Birkat Kohanim (the Priestly Blessing) varies: it's recited daily in many congregations in Israel, while many diaspora congregations recite it only on festivals.",
     "Birkat Kohanim is traditionally recited in every congregation worldwide at exactly the same frequency, with no variation in practice.",
     "Frequency of Birkat Kohanim genuinely varies by community and location, rather than following one universal schedule."),
    ("prayer",
     "It's customary among many observant Jews to say 'Baruch Hashem' ('Blessed be God') in casual conversation, often when asked how one is doing.",
     "It's customary to say 'Baruch Hashem' only during formal synagogue prayer services, never in casual conversation.",
     "'Baruch Hashem' is a common everyday expression in casual speech, not limited to formal prayer settings."),

    # --- synagogue ---
    ("synagogue",
     "A synagogue's library or study hall is traditionally called a beit midrash, meaning 'house of study.'",
     "A synagogue's library or study hall is traditionally called a beit din, meaning 'house of judgment.'",
     "Beit midrash means 'house of study'; a beit din is a different institution, a rabbinic court."),
    ("synagogue",
     "A synagogue is sometimes called a 'shul' in Yiddish-influenced English, a term especially common among Ashkenazi communities.",
     "A synagogue is sometimes called a 'shul' in Yiddish-influenced English, a term especially common among Sephardic communities, coined from Spanish.",
     "'Shul' comes from Yiddish and is especially associated with Ashkenazi usage, not a Spanish-derived Sephardic term."),

    # --- texts ---
    ("texts",
     "Maimonides' Mishneh Torah uniquely organized Jewish law by subject matter, rather than following the traditional order of the Talmud's tractates.",
     "Maimonides' Mishneh Torah strictly follows the same tractate order as the Talmud, with no reorganization.",
     "The Mishneh Torah's subject-based reorganization was a notable innovation, distinct from the Talmud's own structure."),
    ("texts",
     "The word 'siddur' itself means 'order' in Hebrew, reflecting the fixed sequence of prayers it contains.",
     "The word 'siddur' itself means 'song' in Hebrew, reflecting its use for melodies during prayer.",
     "'Siddur' comes from a root meaning 'order,' referring to its structured sequence of prayers, not a word for song."),
    ("texts",
     "The word 'Mishnah' comes from a Hebrew root meaning 'to repeat' or 'to study,' reflecting its origins as orally repeated teachings.",
     "The word 'Mishnah' comes from a Hebrew root meaning 'to forget,' reflecting concern that oral teachings might be lost.",
     "'Mishnah' relates to repetition and study, not a word meaning 'to forget.'"),

    # --- language ---
    ("language",
     "The Hebrew word 'Torah' is often translated as 'law,' but more precisely means 'teaching' or 'instruction.'",
     "The Hebrew word 'Torah' is often translated as 'teaching,' but more precisely and exclusively means 'punishment.'",
     "'Torah' relates to teaching and instruction, not punishment."),
    ("language",
     "'Mensch,' a Yiddish-derived word used in English, describes a person of good character and integrity.",
     "'Mensch,' a Yiddish-derived word used in English, describes a person who has committed a serious crime.",
     "'Mensch' is a term of praise for someone decent and honorable, the opposite of describing a criminal."),
    ("language",
     "'Oy vey,' a Yiddish expression now used in English, is typically used to express frustration or dismay.",
     "'Oy vey,' a Yiddish expression now used in English, is traditionally used only to express extreme joy and celebration.",
     "'Oy vey' conveys dismay or frustration, not celebration."),

    # --- diaspora ---
    ("diaspora",
     "Hungarian Jewish cuisine historically contributed dishes like cholent variations and flódni, a traditional multi-layered pastry, to broader Ashkenazi food culture.",
     "Hungarian Jewish cuisine historically contributed dishes like paella and gazpacho to broader Ashkenazi food culture.",
     "Flódni and cholent variations trace to Hungarian Jewish tradition; paella and gazpacho are Spanish dishes unrelated to it."),
    ("diaspora",
     "Poland was historically home to one of the largest Jewish communities in the world, with cities like Warsaw and Krakow at the center of Ashkenazi Jewish culture for centuries.",
     "Poland has never had any historical Jewish community of note; Ashkenazi Jewish culture developed entirely in Russia instead.",
     "Poland was historically a major center of Ashkenazi Jewish life for centuries, not simply absent from that history."),
    ("diaspora",
     "Hasidic Judaism, a spiritual revival movement, originated in 18th-century Eastern Europe, associated with its founder, the Baal Shem Tov.",
     "Hasidic Judaism, a spiritual revival movement, originated in 18th-century Western Europe, associated with its founder, Moses Mendelssohn.",
     "Hasidism traces to the Baal Shem Tov in Eastern Europe; Moses Mendelssohn is instead associated with the separate Haskalah movement."),
    ("diaspora",
     "Sephardic Jewish cuisine traditionally features dishes like sofrito, dried fruits, and rice-based dishes, distinct from Ashkenazi cuisine's noodle- and potato-based dishes.",
     "Sephardic Jewish cuisine and Ashkenazi Jewish cuisine are traditionally identical, with no distinguishing dishes or ingredients.",
     "Sephardic and Ashkenazi culinary traditions genuinely differ, shaped by very different regional influences."),
    ("diaspora",
     "Ethiopian Jewish cuisine traditionally features injera, a spongy flatbread, alongside spiced stews, shared with broader Ethiopian culinary tradition.",
     "Ethiopian Jewish cuisine traditionally features bagels and lox, imported directly from Ashkenazi communities in Eastern Europe.",
     "Injera and spiced stews reflect Ethiopian Jewish cuisine's roots in the broader regional food tradition, not Ashkenazi imports."),
    ("diaspora",
     "In some Persian Jewish families, it's traditional to gently swat each other with scallions while singing 'Dayenu' at the Passover seder, symbolizing the whips of slavery in Egypt.",
     "In some Persian Jewish families, it's traditional to exchange small gifts while singing 'Dayenu' at the Passover seder, symbolizing the blessings of freedom.",
     "The scallion-swatting custom during 'Dayenu' is a well-documented Persian Jewish Passover tradition, not a gift exchange."),
    ("diaspora",
     "Indian Jewish (Bene Israel) tradition includes making malida, a ceremonial dish of flattened rice, sugar, and fruit, offered during celebrations in honor of the prophet Elijah.",
     "Indian Jewish (Bene Israel) tradition includes making malida, a ceremonial dish of spiced meat, offered only during mourning rituals.",
     "Malida is a sweet celebratory dish tied to honoring Elijah, not a meat dish used only in mourning."),
    ("diaspora",
     "Iraqi Jewish cuisine traditionally includes dishes like kubbeh (stuffed dumplings) and t'beet, a slow-cooked Shabbat chicken and rice dish.",
     "Iraqi Jewish cuisine traditionally consists entirely of raw, uncooked dishes, since cooking was historically forbidden in the community.",
     "Kubbeh and t'beet are well-documented cooked traditional dishes; there's no such prohibition on cooking in Iraqi Jewish cuisine."),
    ("diaspora",
     "Ladino, the traditional Sephardic Jewish language, is still spoken and studied today, including through modern radio programs and educational initiatives aimed at preserving it.",
     "Ladino, the traditional Sephardic Jewish language, has had no speakers or students since the 15th century, with no modern preservation efforts.",
     "Ladino has active modern speakers and dedicated preservation efforts today, rather than having disappeared centuries ago."),
]
