# Batch 6: ~47 new true/false pairs, continuing the laws/customs emphasis:
# bird kashrut, more Shabbat and holiday customs, tefillin construction
# detail, synagogue architecture, and a run of halakhic-literature and
# history facts.

PAIRS = [
    # --- kashrut ---
    ("kashrut",
     "Kosher bird identification traditionally relies on a received tradition (mesorah) of specific species, rather than a simple biological rule like other kosher animal categories.",
     "Kosher bird identification uses the exact same fins-and-scales rule that applies to kosher fish.",
     "Birds are identified as kosher through received tradition about specific species, not a fins-and-scales rule, which applies to fish instead."),
    ("kashrut",
     "Turkey's kosher status was historically debated when the bird was introduced to the Old World, since it lacked an established mesorah; today it's widely accepted as kosher.",
     "Turkey's kosher status has never been questioned by any rabbinic authority, since it was always considered obviously kosher.",
     "Turkey's kosher status was a genuine historical debate precisely because it was a 'new' bird without prior tradition behind it."),
    ("kashrut",
     "'Mevushal' kosher wine, which has been briefly boiled or pasteurized, can be handled and poured by anyone without affecting its kosher status.",
     "'Mevushal' kosher wine requires even stricter handling than regular kosher wine, permitted to be touched only by rabbis.",
     "Mevushal wine is specifically an exception that loosens handling requirements, not a stricter category."),
    ("kashrut",
     "Tevilat Keilim is a traditional requirement to immerse certain new dishes or utensils made by non-Jewish manufacturers in a mikveh before use.",
     "Tevilat Keilim is a traditional requirement to season new dishes or utensils with salt for a week before use.",
     "Tevilat Keilim specifically involves immersion in a mikveh, not a salting process."),
    ("kashrut",
     "Some kosher-certified leafy greens are grown hydroponically specifically to make insect-free inspection easier and more reliable.",
     "Hydroponically grown vegetables are considered automatically non-kosher under Jewish law, regardless of inspection.",
     "Hydroponic growing is actually used to help meet kosher insect-checking standards, not to disqualify produce."),

    # --- shabbat ---
    ("shabbat",
     "'Shavua Tov' ('a good week') is traditionally said to others as Shabbat ends, paralleling 'Shabbat Shalom' said at its start.",
     "'Shabbat Shalom' is traditionally said both at the start and end of Shabbat, with no distinct phrase for its conclusion.",
     "There's a distinct traditional phrase, 'Shavua Tov,' for the end of Shabbat, separate from the greeting used at its start."),
    ("shabbat",
     "It's customary to avoid discussing weekday business or mundane worries during Shabbat conversation.",
     "It's customary to specifically reserve Shabbat conversation for business deals and financial planning, away from weekday distractions.",
     "Shabbat conversation traditionally steers away from business and mundane concerns, not toward them."),
    ("shabbat",
     "Melaveh Malkah is a customary meal held after Shabbat ends on Saturday night, its name meaning 'escorting the queen.'",
     "Melaveh Malkah is a customary meal held before Shabbat begins on Friday afternoon, its name meaning 'welcoming the queen.'",
     "Melaveh Malkah takes place after Shabbat concludes, symbolically escorting out the 'Shabbat Queen,' not welcoming her in."),

    # --- holidays ---
    ("holidays",
     "At the Passover seder, a drop of wine is traditionally spilled for each of the Ten Plagues, tempering joy with empathy for the Egyptians' suffering.",
     "At the Passover seder, a drop of wine is traditionally added, not spilled, for each of the Ten Plagues, to increase the joy of the meal.",
     "Wine is spilled, not added, for each plague, traditionally reflecting reduced rather than increased joy."),
    ("holidays",
     "The afikoman is a piece of matzah hidden during the seder, traditionally found or redeemed by children and eaten as the meal's last food.",
     "The afikoman is a piece of matzah traditionally eaten first, before any other part of the seder begins.",
     "The afikoman is specifically the last food eaten at the seder, not the first."),
    ("holidays",
     "Ushpizin is a custom of symbolically inviting one of seven biblical figures into the sukkah each night of Sukkot.",
     "Ushpizin is a custom of symbolically inviting one of seven biblical figures into the synagogue each night of Hanukkah.",
     "Ushpizin is tied specifically to Sukkot and the sukkah, not Hanukkah and the synagogue."),
    ("holidays",
     "Sukkot's Four Species are traditionally interpreted as representing different qualities or types of people within the community.",
     "Sukkot's Four Species are traditionally interpreted as representing the four ancient kingdoms that exiled the Jewish people.",
     "The traditional interpretation ties the Four Species to different types of people, not historical exiling empires."),
    ("holidays",
     "Yom Kippur's traditional Avodah service recounts the ancient Temple's high priest ceremony.",
     "Yom Kippur's traditional Avodah service recounts the story of the Exodus from Egypt.",
     "The Avodah service is specifically about the Temple high priest's Yom Kippur ritual, not the Exodus story."),
    ("holidays",
     "The molad, the precise moment of the new moon, is traditionally announced in synagogue on the Shabbat before Rosh Chodesh.",
     "The molad, the precise moment of the new moon, is traditionally kept secret and never announced publicly.",
     "Announcing the molad (Birkat HaChodesh) is a standard, public part of the service before a new month."),
    ("holidays",
     "It's customary to eat round challah on Rosh Hashanah, symbolizing a complete, unbroken year.",
     "It's customary to eat only square-shaped bread on Rosh Hashanah, symbolizing structure and order for the year ahead.",
     "Round challah, not square bread, is the traditional Rosh Hashanah custom, symbolizing wholeness and continuity."),

    # --- ritual_objects ---
    ("ritual_objects",
     "In a set of tefillin, the arm box holds all four scriptural passages together in one compartment, while the head box has four separate compartments, one per passage.",
     "In a set of tefillin, both the arm box and the head box hold all four scriptural passages together in a single shared compartment.",
     "The arm and head tefillin boxes are built differently: one compartment for the arm, four separate compartments for the head."),
    ("ritual_objects",
     "The traditional blue dye for tzitzit, tekhelet, came from a sea creature called chilazon, whose identity was lost for centuries and is debated today.",
     "The traditional blue dye for tzitzit, tekhelet, came from a common flower that is still easily identified and used today without any debate.",
     "Tekhelet's source was a specific sea creature whose identification was lost historically, not an easily identified flower."),
    ("ritual_objects",
     "A cracked shofar traditionally cannot be validly repaired with glue or other reinforcement for ritual use.",
     "A cracked shofar can traditionally be freely repaired with glue or other materials without affecting its ritual validity.",
     "A crack traditionally invalidates a shofar for ritual use, and gluing it back together doesn't restore its status."),
    ("ritual_objects",
     "The parchment used for a Torah scroll, tefillin, and mezuzot must traditionally come from a kosher animal, specially prepared for ritual use.",
     "The parchment used for a Torah scroll, tefillin, and mezuzot can traditionally be any commercially available paper, with no source requirements.",
     "Ritual parchment has specific source requirements tied to kosher animal hides, unlike ordinary paper."),

    # --- symbols ---
    ("symbols",
     "The ancient seven-branched menorah and the nine-branched Hanukkah chanukiah are two distinct objects, not different names for the same thing.",
     "The seven-branched menorah and the nine-branched chanukiah are simply two different names for the exact same object.",
     "They're genuinely different objects: a seven-branched Temple menorah and a nine-branched Hanukkah chanukiah."),
    ("symbols",
     "The hamsa, a hand-shaped amulet associated with protection, is used in Jewish tradition but isn't exclusively Jewish — it's shared across several Middle Eastern and North African cultures.",
     "The hamsa, a hand-shaped amulet, originated as an exclusively Jewish symbol with no presence in any other regional culture.",
     "The hamsa is shared across multiple cultures in the region, not an exclusively Jewish symbol."),
    ("symbols",
     "The number seven recurs throughout traditional Jewish practice, including the days of creation, the wedding blessings, and the circuits traditionally made around the bride.",
     "The number twelve recurs throughout traditional Jewish practice, including the days of creation, the wedding blessings, and the circuits traditionally made around the bride, echoing the twelve tribes.",
     "Each of those specific examples — creation, wedding blessings, bridal circuits — is traditionally tied to the number seven, not twelve."),

    # --- lifecycle ---
    ("lifecycle",
     "Firstborn sons from Kohen or Levi families are traditionally exempt from the pidyon haben redemption ceremony.",
     "Only firstborn sons from Kohen or Levi families are traditionally required to undergo the pidyon haben redemption ceremony, while others are exempt.",
     "Kohen and Levi firstborns are exempt because their lineage is already considered dedicated; other firstborn sons are the ones traditionally included."),
    ("lifecycle",
     "A traditional Jewish wedding ceremony cannot take place on Shabbat or most Jewish holidays.",
     "A traditional Jewish wedding ceremony can take place on any day of the year, including Shabbat and Yom Kippur, with no restrictions.",
     "Traditional Jewish law restricts weddings from being held on Shabbat and most holidays."),
    ("lifecycle",
     "Simchat Bat (or Zeved HaBat) is a traditional naming ceremony for a baby girl, with customs varying by community.",
     "Simchat Bat is a traditional naming ceremony held only for a family's first-born child, regardless of gender.",
     "Simchat Bat is specifically a naming custom for baby girls, not a first-born-of-any-gender ceremony."),
    ("lifecycle",
     "Yichud is the custom of a couple spending a few private minutes alone together immediately after their wedding ceremony.",
     "Yichud is the custom of a couple spending their entire wedding day apart, not seeing each other until the reception ends.",
     "Yichud specifically involves brief private time right after the ceremony, not day-long separation."),
    ("lifecycle",
     "A Bar Mitzvah boy traditionally delivers a short speech interpreting the Torah portion, called a dvar Torah.",
     "A Bar Mitzvah boy traditionally remains completely silent throughout his own ceremony, with a rabbi speaking on his behalf.",
     "Delivering a dvar Torah, a short speech, is a traditional part of a Bar Mitzvah, not silence."),
    ("lifecycle",
     "A get (Jewish divorce document) must traditionally be written specifically for the couple involved, not from a generic pre-printed form.",
     "A get can traditionally be a generic pre-printed form, filled in with names, similar to many standard legal documents.",
     "A get is traditionally required to be individually written for the specific couple, not filled in on a template."),

    # --- prayer ---
    ("prayer",
     "Tefillat HaDerech is a traveler's prayer traditionally recited before a journey.",
     "Tefillat HaDerech is a prayer traditionally recited only by someone confined to bed with illness.",
     "Tefillat HaDerech is specifically for travel, not illness."),
    ("prayer",
     "Birkat HaGomel is a blessing traditionally recited after surviving danger, often said publicly during Torah reading.",
     "Birkat HaGomel is a blessing traditionally recited before undertaking any risky activity, as a request for protection in advance.",
     "Birkat HaGomel is recited after surviving a dangerous situation, as thanks, not beforehand as a request."),
    ("prayer",
     "Asher Yatzar is a blessing traditionally recited after using the restroom, thanking for the body's proper function.",
     "Asher Yatzar is a blessing traditionally recited only before eating bread, thanking for the day's food.",
     "Asher Yatzar is specifically tied to bodily function after using the restroom, not to eating bread."),
    ("prayer",
     "Kiddush Levana traditionally includes a custom of gently rising onto one's toes toward the moon while reciting blessings outdoors.",
     "Kiddush Levana traditionally includes a custom of lying flat on the ground facing away from the moon while reciting blessings indoors.",
     "Kiddush Levana is an outdoor practice involving a gesture toward the moon, not lying down facing away from it indoors."),
    ("prayer",
     "Psalm 27 is traditionally added to daily prayers during the period from before Rosh Hashanah through Sukkot.",
     "No additional psalms are traditionally added to daily prayers at any point in the Hebrew calendar year.",
     "Psalm 27 is a specific, well-known seasonal addition to the prayer service around the High Holidays and Sukkot."),

    # --- synagogue ---
    ("synagogue",
     "A synagogue's bimah is traditionally placed in the center of the room in many older synagogues, while many modern synagogues place it at the front near the ark.",
     "A synagogue's bimah has always been placed in exactly the same spot, at the back of the room, in every synagogue throughout history.",
     "Bimah placement has genuinely varied over time and by community, from center-of-room to front-of-room layouts."),

    # --- texts ---
    ("texts",
     "The standardized page layout used in most printed editions of the Talmud today traces back to a 16th-century printing by Daniel Bomberg in Venice.",
     "The standardized page layout used in most printed editions of the Talmud today was only introduced in the late 20th century.",
     "The now-standard Talmud page layout dates back roughly 500 years, to Daniel Bomberg's Venice printings."),
    ("texts",
     "Rashi's commentary is traditionally printed in a distinctive typeface, different from the standard Hebrew print font used for the main text.",
     "Rashi's commentary is traditionally printed in the exact same typeface as the main Hebrew text, with no visual distinction.",
     "'Rashi script' is a genuinely distinct typeface, visually setting his commentary apart from the main text."),
    ("texts",
     "Trope marks (cantillation symbols) used for chanting Torah and Haftarah aren't written in the Torah scroll itself and must be memorized by the reader.",
     "Trope marks are written directly into the Torah scroll alongside the letters, to guide the reader's chanting.",
     "A Torah scroll contains no vowels or cantillation marks at all; readers memorize both the pronunciation and the chant."),
    ("texts",
     "The vowel points used in most printed Hebrew Bibles come from the Masoretic tradition, since a Torah scroll itself is written without them.",
     "The vowel points used in most printed Hebrew Bibles were part of the original text from the very beginning, including in Torah scrolls.",
     "Vowel points were added later by the Masoretes; a traditional Torah scroll remains unvocalized."),
    ("texts",
     "The Passover Haggadah exists in thousands of different printed editions, making it one of the most frequently reprinted Jewish texts in history.",
     "The Passover Haggadah exists in exactly one authorized printed edition, unchanged since its original publication.",
     "The Haggadah has been reprinted and reinterpreted in an enormous number of editions over the centuries, not just one fixed version."),

    # --- history ---
    ("history",
     "The Cairo Genizah, a cache of old manuscripts found in a Cairo synagogue's storage room, gave historians major insight into medieval Jewish life after its discovery in the late 19th century.",
     "The Cairo Genizah, a cache of old manuscripts, was discovered in the 21st century and has not yet been studied by historians.",
     "The Cairo Genizah was discovered in the late 1800s and has been extensively studied ever since, not recently and unstudied."),
    ("history",
     "The term 'diaspora' describes Jewish communities living outside the Land of Israel, a pattern dating back to the Babylonian exile.",
     "The term 'diaspora' describes Jewish communities living inside the Land of Israel exclusively, a term coined in the 20th century.",
     "'Diaspora' specifically refers to communities outside the Land of Israel, with roots going back to the Babylonian exile."),
    ("history",
     "The Hellenistic period following Alexander the Great's conquests set the stage for the events later commemorated by Hanukkah.",
     "The Hellenistic period following Alexander the Great's conquests set the stage for the events later commemorated by Passover.",
     "The Hellenistic-era Maccabean revolt is what Hanukkah commemorates, not the earlier Exodus story behind Passover."),
    ("history",
     "Yiddish-language theater and press flourished in early 20th-century New York, especially on Manhattan's Lower East Side.",
     "Yiddish-language theater and press flourished in early 20th-century Tokyo, especially in the city's harbor district.",
     "This flourishing of Yiddish culture is associated with New York's Lower East Side, not Tokyo."),

    # --- language ---
    ("language",
     "The Hebrew names of the months, like Nisan and Tishrei, were adopted during or after the Babylonian exile, replacing an earlier system that simply numbered the months.",
     "The Hebrew names of the months, like Nisan and Tishrei, are the original names used in the Torah from the very beginning.",
     "The Torah largely just numbers the months; the familiar names were adopted later, tied to the Babylonian period."),
    ("language",
     "'L'chaim,' a traditional Jewish toast, literally means 'to life.'",
     "'L'chaim,' a traditional Jewish toast, literally means 'to health.'",
     "'L'chaim' literally translates to 'to life,' not 'to health.'"),

    # --- people ---
    ("people",
     "Judah HaNasi is traditionally credited with compiling and redacting the Mishnah around 200 CE.",
     "Judah HaNasi is traditionally credited with compiling and redacting the Mishnah in the 20th century.",
     "Judah HaNasi's traditional dating is around 200 CE, roughly 1,800 years before the 20th century."),
    ("people",
     "Hillel and Shammai led two rival schools of Jewish legal thought in the late Second Temple period, frequently disagreeing on details of law.",
     "Hillel and Shammai were father and son who always agreed completely on every point of Jewish law.",
     "Hillel and Shammai headed distinct, often disagreeing schools of thought; they weren't father and son in perfect agreement."),
]
