# Batch 10: ~47 new true/false pairs, continuing toward the 1780 target.
# More melachot, minor calendar days, prayer-service structure, specific
# ritual objects, medieval commentators/codifiers, and more diaspora
# communities (Brazil, Suriname, Australia, Canada, Gibraltar, Baghdadi
# trading families, Morocco, Tunisia, Yemen).

PAIRS = [
    # --- shabbat: more melachot ---
    ("shabbat",
     "One of the 39 traditionally forbidden Shabbat labors is plowing (preparing soil for planting).",
     "None of the 39 traditionally forbidden Shabbat labors relate to preparing soil for planting.",
     "Plowing is one of the 39 melachot, rooted in the original agricultural categories of forbidden labor."),
    ("shabbat",
     "One of the 39 traditionally forbidden Shabbat labors is reaping (harvesting crops).",
     "None of the 39 traditionally forbidden Shabbat labors relate to harvesting crops.",
     "Reaping is specifically listed among the 39 melachot."),
    ("shabbat",
     "One of the 39 traditionally forbidden Shabbat labors is grinding.",
     "None of the 39 traditionally forbidden Shabbat labors relate to grinding.",
     "Grinding is one of the 39 melachot, originally tied to processing grain."),
    ("shabbat",
     "One of the 39 traditionally forbidden Shabbat labors is spinning thread.",
     "None of the 39 traditionally forbidden Shabbat labors relate to spinning thread.",
     "Spinning is one of the 39 melachot, part of the traditional textile-related categories."),
    ("shabbat",
     "One of the 39 traditionally forbidden Shabbat labors is dyeing.",
     "None of the 39 traditionally forbidden Shabbat labors relate to dyeing.",
     "Dyeing is specifically listed among the 39 melachot."),
    ("shabbat",
     "One of the 39 traditionally forbidden Shabbat labors is erasing, specifically in order to write again.",
     "None of the 39 traditionally forbidden Shabbat labors relate to erasing.",
     "Erasing (to enable further writing) is one of the 39 melachot, paired with the prohibition on writing."),
    ("shabbat",
     "One of the 39 traditionally forbidden Shabbat labors is combing or carding wool.",
     "None of the 39 traditionally forbidden Shabbat labors relate to preparing wool.",
     "Combing/carding wool is one of the 39 melachot, part of the traditional textile-preparation categories."),
    ("shabbat",
     "One of the 39 traditionally forbidden Shabbat labors is kneading dough.",
     "None of the 39 traditionally forbidden Shabbat labors relate to preparing dough.",
     "Kneading is specifically listed among the 39 melachot."),

    # --- holidays ---
    ("holidays",
     "Isru Chag is a minor day observed right after a major festival ends, traditionally treated with a mildly festive character.",
     "Isru Chag is the single most solemn fast day of the Jewish year, traditionally observed with strict mourning practices.",
     "Isru Chag is a light, festive-adjacent day following a major holiday, not a solemn fast day."),
    ("holidays",
     "It's traditional to avoid fasting or eulogies on Rosh Chodesh, treating it with a mildly festive character.",
     "It's traditional to specifically require fasting on Rosh Chodesh, treating it as a solemn day of atonement.",
     "Rosh Chodesh carries a mild festive status, during which fasting and eulogies are traditionally avoided, not required."),
    ("holidays",
     "Hanukkah candles are traditionally meant to burn for at least half an hour after nightfall before being allowed to go out.",
     "Hanukkah candles are traditionally meant to be extinguished immediately, within a minute of being lit.",
     "A minimum burn time of roughly half an hour after nightfall is the traditional standard, not near-immediate extinguishing."),
    ("holidays",
     "An abbreviated form of Hallel, sometimes called 'Half Hallel,' is traditionally recited on Rosh Chodesh and the latter days of Passover.",
     "It's traditional to recite the exact same full version of Hallel every single day it's said, with no shorter version ever used.",
     "A shortened 'Half Hallel' is a real, distinct traditional form used on certain days, unlike the full version used on other festivals."),
    ("holidays",
     "Purim Katan is observed in Hebrew leap years, falling in the first of the two Adar months, with a few minor festive customs but without the full Purim obligations.",
     "Purim Katan is observed every year on the same date as regular Purim, with identical obligations required in every Hebrew year.",
     "Purim Katan is specific to leap years and comes with lighter customs, unlike the full Purim observed in Adar (or Adar II in a leap year)."),

    # --- prayer ---
    ("prayer",
     "In many congregations, the Amidah is recited silently first, then repeated aloud by the prayer leader, a structure called chazarat hashatz.",
     "The Amidah is traditionally always recited exactly once, aloud, together by the entire congregation in unison, with no separate silent version.",
     "The silent-then-repeated structure (chazarat hashatz) is a standard traditional feature of communal prayer services."),
    ("prayer",
     "Ya'aleh V'Yavo is a prayer insert traditionally added to daily prayers and Birkat HaMazon on Rosh Chodesh and festivals.",
     "Ya'aleh V'Yavo is a prayer insert traditionally added to daily prayers only during the Three Weeks of mourning before Tisha B'Av.",
     "Ya'aleh V'Yavo is tied to Rosh Chodesh and festivals, not the mournful Three Weeks period."),
    ("prayer",
     "Baruch Dayan HaEmet, meaning 'Blessed is the true Judge,' is a blessing traditionally recited upon hearing of a death.",
     "Baruch Dayan HaEmet is a blessing traditionally recited upon hearing good news, such as a birth or engagement.",
     "This blessing is specifically tied to news of a death, not celebratory news."),
    ("prayer",
     "The Shema is traditionally recited twice daily, as part of both the morning and evening prayer services.",
     "The Shema is traditionally recited only once a year, as part of the Yom Kippur service.",
     "Reciting the Shema morning and evening, daily, is a foundational traditional practice, not a once-a-year one."),
    ("prayer",
     "Selichot services traditionally include reciting the Thirteen Attributes of Mercy, a set of biblical verses describing God's compassionate qualities.",
     "Selichot services traditionally include reciting the Ten Commandments in full, repeated multiple times throughout the service.",
     "The Thirteen Attributes of Mercy, not a repeated recitation of the Ten Commandments, are a defining feature of Selichot."),
    ("prayer",
     "SheHakol is a traditional catch-all blessing recited over foods that don't fit specific categories like bread, tree fruit, or ground produce, such as meat, fish, eggs, or most beverages.",
     "There is traditionally no blessing at all for foods that don't fit the specific categories of bread, fruit, or vegetables.",
     "SheHakol exists precisely to cover foods outside the other specific blessing categories, not leave them blessing-free."),
    ("prayer",
     "It's traditional to recite Birkat HaGomel after safely completing a long journey by sea or through the wilderness, among other situations of surviving danger.",
     "It's traditional to recite Birkat HaGomel only after winning a competitive game or sporting event.",
     "Birkat HaGomel is tied to surviving real danger, such as sea or wilderness travel, not winning a game."),

    # --- lifecycle ---
    ("lifecycle",
     "Vidui is a traditional confessional prayer, recited if possible by a person nearing death.",
     "Vidui is a traditional confessional prayer, recited exclusively by a couple immediately before their wedding.",
     "Vidui is specifically associated with the end of life, not a pre-wedding custom."),
    ("lifecycle",
     "It's traditional to recite Kaddish for a sibling, child, or spouse for thirty days (sheloshim), while the eleven-month practice is specifically associated with mourning a parent.",
     "It's traditional to recite Kaddish for a sibling, child, or spouse for a full eleven months, identical to mourning a parent, with no distinction between relatives.",
     "Kaddish duration traditionally differs by relationship: eleven months for a parent, thirty days for other close relatives."),
    ("lifecycle",
     "It's traditional for a bar mitzvah boy to receive his own personal set of tefillin around the time of his bar mitzvah, marking his new obligation to wear them.",
     "It's traditional for a bar mitzvah boy to give away his family's tefillin at his bar mitzvah, rather than receiving a set.",
     "Receiving one's own tefillin around bar mitzvah age is the traditional custom, not giving tefillin away."),

    # --- ritual_objects ---
    ("ritual_objects",
     "A keter Torah ('Torah crown') is a decorative silver crown sometimes placed atop a Torah scroll's rollers, distinct from rimonim finials.",
     "A keter Torah is a decorative headpiece traditionally worn by the rabbi, unrelated to the Torah scroll itself.",
     "A keter Torah adorns the Torah scroll itself, not a garment worn by a rabbi."),
    ("ritual_objects",
     "An atara is a decorative collar strip traditionally sewn onto a tallit, marking its top edge or neckline.",
     "An atara is a decorative collar strip traditionally sewn onto a Torah scroll's mantle, marking its base.",
     "An atara belongs on a tallit's neckline, not a Torah scroll's mantle."),
    ("ritual_objects",
     "A yad (Torah pointer) is traditionally not touched directly to the parchment, to avoid wearing down the ink and letters over repeated use.",
     "A yad is traditionally pressed firmly against the parchment while reading, to help guide the reader's finger along each letter.",
     "A yad is used without touching the parchment, specifically to protect the scroll's ink and letters from wear."),
    ("ritual_objects",
     "Tefillin straps (retzuot) are traditionally kept with their black leather side facing outward at all times.",
     "Tefillin straps (retzuot) are traditionally kept with their black leather side facing inward, hidden from view, at all times.",
     "The black side of the straps is traditionally meant to face outward, not be hidden."),

    # --- kashrut ---
    ("kashrut",
     "Traditional Jewish law generally forbids deriving any benefit from certain non-kosher foods, not just eating them.",
     "Traditional Jewish law only forbids eating non-kosher food directly; any other use or benefit from it is traditionally unrestricted.",
     "Some non-kosher items carry a broader 'benefit' prohibition (issur hana'ah), beyond simply not eating them."),
    ("kashrut",
     "It's traditional practice in many kosher kitchens to use color-coded dishware or utensil handles, such as red for meat and blue for dairy, to keep the categories visually distinct.",
     "It's traditional practice in kosher kitchens to use identical, unlabeled dishware for both meat and dairy, relying entirely on memory to keep them separate.",
     "Color-coding is a common practical aid for keeping meat and dairy dishware distinct, rather than relying purely on memory."),
    ("kashrut",
     "It's traditional for an observant household to keep separate sets of Passover dishes for meat, dairy, and pareve use, distinct from their year-round sets.",
     "It's traditional for an observant household to use one single shared set of dishes for both year-round and Passover use, with no distinction.",
     "Dedicated Passover dish sets, mirroring the meat/dairy/pareve categories, are the traditional approach, not a single shared set."),

    # --- symbols ---
    ("symbols",
     "The Ten Commandments tablets (Luchot), often shown with rounded tops, are a widely used decorative motif in synagogue architecture.",
     "The Ten Commandments tablets (Luchot) are traditionally never depicted visually, since any image of them is considered forbidden.",
     "Rounded-top tablet imagery is a very common, widely used traditional synagogue decorative motif, not a forbidden image."),
    ("symbols",
     "A pomegranate motif, alluding to a tradition connecting its many seeds to the 613 mitzvot, is a common decorative symbol on ritual items like Torah finials.",
     "A pineapple motif, alluding to a tradition connecting its texture to the 613 mitzvot, is a common decorative symbol on ritual items like Torah finials.",
     "The pomegranate, not the pineapple, is the traditional fruit symbol tied to the 613 mitzvot."),

    # --- texts ---
    ("texts",
     "Targum Onkelos, a specific ancient Aramaic translation of the Torah, is traditionally included alongside the Hebrew text in study editions called Mikraot Gedolot.",
     "Targum Onkelos is a modern English translation of the Torah, first published in the 20th century.",
     "Targum Onkelos is an ancient Aramaic translation, not a modern English one."),
    ("texts",
     "Mikraot Gedolot ('Great Scriptures') is a traditional study format of the Hebrew Bible that surrounds the main text with several classical commentaries side by side.",
     "Mikraot Gedolot is a traditional study format that presents the Hebrew Bible text alone, with no accompanying commentary of any kind.",
     "Mikraot Gedolot is specifically defined by its inclusion of multiple surrounding commentaries, not a bare, commentary-free text."),
    ("texts",
     "The Arba'ah Turim ('Four Columns'), written by Rabbi Yaakov ben Asher in the 14th century, was an influential legal code that shaped the later Shulchan Aruch's structure.",
     "The Arba'ah Turim was written in the 20th century as a direct English translation of the Shulchan Aruch for American audiences.",
     "The Arba'ah Turim predates and influenced the Shulchan Aruch, rather than being a modern translation of it."),

    # --- people ---
    ("people",
     "Onkelos, traditionally said to have been a convert to Judaism, is credited with producing the well-known Aramaic translation of the Torah, Targum Onkelos.",
     "Onkelos, traditionally said to have been a Babylonian king, is credited with destroying the first Targum translation of the Torah.",
     "Tradition credits Onkelos, a convert, with creating the Targum, not destroying an earlier version as a king."),
    ("people",
     "Saadia Gaon, a 10th-century scholar, produced an influential translation and commentary on the Hebrew Bible into Arabic.",
     "Saadia Gaon, a 20th-century scholar, produced an influential translation and commentary on the Hebrew Bible into English.",
     "Saadia Gaon lived in the 10th century and worked in Arabic, not the 20th century in English."),
    ("people",
     "Rabbi Yaakov ben Asher, author of the Arba'ah Turim, was the son of another influential medieval rabbinic authority, Rabbeinu Asher (the Rosh).",
     "Rabbi Yaakov ben Asher, author of the Arba'ah Turim, was the son of Rashi, connecting two of medieval Judaism's most famous commentators.",
     "Yaakov ben Asher's father was Rabbeinu Asher (the Rosh), a distinct figure from the earlier commentator Rashi."),

    # --- diaspora ---
    ("diaspora",
     "Recife, Brazil, was home to the first organized Jewish community in the Americas, established in the 17th century.",
     "Recife, Brazil, has never had any historical Jewish community; the first such community in the Americas was instead in Canada.",
     "Recife's 17th-century Jewish community is traditionally recognized as the first organized Jewish community in the Americas."),
    ("diaspora",
     "Jodensavanne, in Suriname, was a historic Jewish agricultural settlement established in the 17th and 18th centuries.",
     "Jodensavanne, in Suriname, is a modern shopping district built in the 21st century with no historical significance.",
     "Jodensavanne is a genuine historic settlement dating back centuries, not a recent development."),
    ("diaspora",
     "Australia is home to a significant Jewish community, historically concentrated especially in Melbourne and Sydney.",
     "Australia has never had a Jewish community of significant size; Jewish immigration to Australia has been essentially nonexistent historically.",
     "Australia has a well-documented, sizable Jewish community, especially in Melbourne and Sydney."),
    ("diaspora",
     "Canada is home to a significant Jewish community, historically concentrated especially in Montreal and Toronto.",
     "Canada has never had a Jewish community of significant size; Jewish immigration to Canada has been essentially nonexistent historically.",
     "Canada has a well-documented, sizable Jewish community, especially in Montreal and Toronto."),
    ("diaspora",
     "Gibraltar has a small but historically significant Jewish community, notable given the territory's overall small size.",
     "Gibraltar has never had any Jewish community or presence throughout its history.",
     "Gibraltar's Jewish community, while small, is real and historically well documented."),
    ("diaspora",
     "Baghdadi Jewish trading families, such as the Sassoons, established significant trading communities in places like India, Singapore, and Hong Kong during the 19th century.",
     "Baghdadi Jewish trading families historically avoided international trade entirely, remaining confined to Baghdad itself.",
     "Baghdadi Jewish merchant families were notably active in international trade across Asia, not confined to Baghdad."),
    ("diaspora",
     "Morocco is traditionally home to one of the largest historic Jewish populations in the Muslim world, with a Jewish presence dating back over 2,000 years.",
     "Morocco has historically had one of the smallest Jewish populations in the Muslim world, with a Jewish presence dating back only a few decades.",
     "Morocco's historic Jewish population was among the largest in the Muslim world, with roots going back millennia, not decades."),
    ("diaspora",
     "Tunisia's Jewish community historically included both an older, established population and 'Livornese' Jews who arrived from the Italian port city of Livorno starting in the 17th century.",
     "Tunisia's Jewish community has always been entirely uniform in origin, with no distinct subgroups or waves of arrival at any point in its history.",
     "Tunisian Jewry historically included genuinely distinct subgroups, including later arrivals from Livorno, Italy."),
    ("diaspora",
     "Yemenite Jewish communities were historically noted for unusually high rates of Hebrew literacy among men, achieved through widespread religious education.",
     "Yemenite Jewish communities historically had no formal religious education system, with Hebrew literacy limited to a small group of rabbis.",
     "Yemenite Jewish communities are well documented for broad religious education and resulting high Hebrew literacy among men, not a lack of education."),
]
