# Batch 2: ~68 new true/false pairs, curated for "outlandish but true" appeal
# while staying factually careful. Each tuple: (category, true_statement,
# false_statement, explanation).

PAIRS = [
    # --- holidays ---
    ("holidays",
     "Dreidels sold in Israel replace one Hebrew letter compared to dreidels sold elsewhere, changing the phrase from 'a great miracle happened there' to 'a great miracle happened here.'",
     "Dreidels are identical everywhere in the world, with no regional differences in their lettering.",
     "Outside Israel, the four letters stand for 'Nes Gadol Haya Sham' (a great miracle happened there); in Israel, one letter changes so it reads 'a great miracle happened here.'"),
    ("holidays",
     "Traditional Hanukkah foods like latkes and sufganiyot are fried in oil, to commemorate the miracle of the oil.",
     "Traditional Hanukkah foods are deliberately baked without any oil or fat, to commemorate the miracle of the oil.",
     "Hanukkah foods are fried in oil precisely to recall the miracle of the oil lasting eight days, not avoided."),
    ("holidays",
     "On Purim, it's customary to give gifts of food to friends (mishloach manot) and gifts to the poor (matanot la'evyonim).",
     "On Purim, it's customary to give gifts of clothing only to family members, and giving to the poor is not part of the holiday.",
     "Purim customs include mishloach manot (food gifts to friends) and matanot la'evyonim (gifts to the poor), both distinct traditions."),
    ("holidays",
     "The festive Purim meal is called a seudah.",
     "The festive Purim meal is called a seder, the same term used for the Passover meal.",
     "The Purim feast is called a seudah; 'seder' specifically refers to the Passover meal."),
    ("holidays",
     "Chametz (leavened grain products) is traditionally removed from the home before Passover begins.",
     "Chametz is traditionally removed from the home before Shavuot begins, not Passover.",
     "Removing chametz before the holiday begins is a Passover practice, tied to the unleavened bread eaten during the holiday."),
    ("holidays",
     "At the Passover seder, a hard-boiled egg dipped in salt water is part of the symbolic seder plate.",
     "At the Passover seder, an egg dipped in honey is part of the symbolic seder plate, to represent a sweet start to freedom.",
     "The seder egg (beitzah) is dipped in salt water; dipping in honey is associated with Rosh Hashanah, not Passover."),
    ("holidays",
     "On Rosh Hashanah, it's customary to dip apple slices in honey for a sweet new year.",
     "On Rosh Hashanah, it's customary to dip apple slices in salt for a sweet new year.",
     "Apples are dipped in honey, not salt, to symbolize hopes for a sweet year ahead."),
    ("holidays",
     "The shofar, a ram's horn, is blown on Rosh Hashanah partly as a symbolic call to reflection ahead of the Days of Awe.",
     "The shofar is blown at the start of the Passover seder to signal the meal may begin.",
     "The shofar is strongly associated with Rosh Hashanah (and Yom Kippur's close); it isn't part of the Passover seder."),

    # --- ritual_objects ---
    ("ritual_objects",
     "A shofar is traditionally made from a ram's horn.",
     "A shofar is traditionally made from an elephant tusk.",
     "Shofars are traditionally made from the horn of a kosher animal, most commonly a ram, never from tusks or ivory."),
    ("ritual_objects",
     "A shtreimel is a fur hat traditionally worn on Shabbat and holidays by some Hasidic Jewish men.",
     "A shtreimel is a type of prayer book traditionally used by some Hasidic Jewish men.",
     "A shtreimel is a fur hat, part of the traditional Shabbat and holiday dress in some Hasidic communities, not a book."),
    ("ritual_objects",
     "A Torah scroll is handwritten by a specially trained scribe called a sofer, using a quill and special ink.",
     "A Torah scroll is printed using a standard printing press, for consistency between copies.",
     "Torah scrolls used in synagogues are handwritten by a sofer; printed copies are not used for ritual reading."),
    ("ritual_objects",
     "The candle used for Havdalah, marking the end of Shabbat, is traditionally braided with multiple wicks.",
     "The candle used for Havdalah is traditionally a single thin candle, like a birthday candle.",
     "The Havdalah candle is distinctively braided with several wicks, unlike a standard single-wick candle."),
    ("ritual_objects",
     "A yad, the pointer used to follow a Torah scroll, is often made of silver and ends in a small pointing hand.",
     "A yad, the pointer used to follow a Torah scroll, is often made of silver and ends in a small hook shaped like a shepherd's staff.",
     "A yad traditionally ends in a shape resembling a small pointing hand or finger, which is where its Hebrew name ('hand') comes from."),
    ("ritual_objects",
     "Tefillin are traditionally worn on weekdays but not on Shabbat or major holidays.",
     "Tefillin are traditionally worn every day of the year, including Shabbat and all holidays, without exception.",
     "Tefillin are set aside on Shabbat and major holidays, which are considered to already carry their own sign of the covenant."),

    # --- symbols ---
    ("symbols",
     "The word 'kosher' literally means 'fit' or 'proper' in Hebrew, and can describe things beyond food.",
     "The word 'kosher' literally means 'blessed by a rabbi,' and applies only to food.",
     "'Kosher' comes from a Hebrew root meaning fit or proper, and is used more broadly than just food (for example, a 'kosher' document)."),
    ("symbols",
     "The Hebrew word 'chai,' meaning 'life,' is often worn as jewelry and is associated with the number 18 through gematria.",
     "The Hebrew word 'chai,' meaning 'life,' is often worn as jewelry and is associated with the number 7, symbolizing a full week of creation.",
     "In gematria, the letters of 'chai' add up to 18, making 18 (and multiples of it) a popular number for gifts and donations."),

    # --- texts ---
    ("texts",
     "The Mishnah, compiled around 200 CE, organizes Jewish oral law into six orders covering topics like agriculture, festivals, and civil law.",
     "The Mishnah was compiled in the 20th century as a modern legal commentary on Israeli civil law.",
     "The Mishnah is an ancient text, compiled around 200 CE, that codifies Jewish oral law into six thematic orders."),
    ("texts",
     "Rashi is the acronym-based name of a medieval commentator whose interpretations appear alongside most printed editions of the Torah and Talmud.",
     "Rashi is the name of an ancient Babylonian king mentioned in the Torah.",
     "'Rashi' stands for Rabbi Shlomo Yitzchaki, an 11th-century commentator, not a biblical or Babylonian king."),
    ("texts",
     "The Tanakh is an acronym for Torah, Nevi'im (Prophets), and Ketuvim (Writings) — the three sections of the Hebrew Bible.",
     "The Tanakh is an acronym for Talmud, Nevi'im, and Kabbalah.",
     "Tanakh is built from Torah, Nevi'im, and Ketuvim; the Talmud and Kabbalah are separate bodies of literature."),
    ("texts",
     "The Book of Ecclesiastes, known in Hebrew as Kohelet, is traditionally read during the festival of Sukkot.",
     "The Book of Ecclesiastes is traditionally read during Yom Kippur.",
     "Kohelet (Ecclesiastes) is traditionally read during Sukkot, not Yom Kippur."),
    ("texts",
     "The Book of Ruth is traditionally read on Shavuot.",
     "The Book of Ruth is traditionally read on Purim.",
     "Ruth is read on Shavuot; the Purim story comes from the Book of Esther instead."),
    ("texts",
     "The Song of Songs is traditionally read during Passover.",
     "The Song of Songs is traditionally read during Hanukkah.",
     "The Song of Songs is traditionally read during Passover, not Hanukkah."),
    ("texts",
     "The Book of Lamentations (Eichah) is traditionally read on Tisha B'Av, mourning the destruction of the Temples.",
     "The Book of Lamentations is traditionally read on Simchat Torah, a day of celebration.",
     "Lamentations, a book of mourning, is read on the solemn fast day of Tisha B'Av, not the celebratory holiday of Simchat Torah."),

    # --- shabbat ---
    ("shabbat",
     "Kiddush, a blessing recited over wine, traditionally marks the start of Shabbat and festival meals.",
     "Kiddush is traditionally recited only at Jewish weddings, never at Shabbat meals.",
     "Kiddush opens Shabbat and festival meals; it is a separate custom from anything recited specifically at weddings."),
    ("shabbat",
     "Two loaves of challah are traditionally placed on the Shabbat table, recalling the double portion of manna that fell before Shabbat in the wilderness.",
     "Two loaves of challah are traditionally placed on the Shabbat table, recalling the two tablets of the Ten Commandments.",
     "The two loaves specifically recall the double portion of manna that fell on Fridays so it wouldn't need to be gathered on Shabbat."),
    ("shabbat",
     "Observant Jews traditionally refrain from activities like driving and using electricity on Shabbat, as part of a broader category of forbidden creative labor.",
     "Observant Jews traditionally avoid eating bread and drinking wine on Shabbat.",
     "Shabbat restrictions center on categories of creative labor (melachah); eating bread and wine are actually part of traditional Shabbat meals."),
    ("shabbat",
     "An eruv is a symbolic boundary, often made with wire or string, that some Jewish communities set up to permit carrying items outdoors on Shabbat.",
     "An eruv is a special Shabbat meal eaten only by rabbis.",
     "An eruv is a physical boundary marker, not a meal, used to permit carrying outdoors on Shabbat in communities that maintain one."),

    # --- lifecycle ---
    ("lifecycle",
     "In many Jewish families, a ceremony called pidyon haben ('redemption of the firstborn son') is held about a month after certain firstborn sons are born.",
     "Pidyon haben, 'redemption of the firstborn son,' is a ceremony held immediately at birth, before the baby leaves the hospital.",
     "Pidyon haben is traditionally held on the 30th day after birth, not immediately."),
    ("lifecycle",
     "Ashkenazi tradition often names a baby after a deceased relative, while Sephardic tradition often names babies after living relatives, including parents.",
     "Both Ashkenazi and Sephardic traditions strictly forbid naming a baby after any relative, living or dead.",
     "Naming customs differ by community: Ashkenazi custom favors honoring the deceased, while Sephardic custom often honors the living, including parents and grandparents."),
    ("lifecycle",
     "At a traditional Jewish funeral, the body is not embalmed and burial takes place as soon as possible, ideally within a day.",
     "At a traditional Jewish funeral, the body is traditionally embalmed and burial is delayed for several weeks.",
     "Jewish tradition generally calls for burial without embalming, as quickly as practical after death."),
    ("lifecycle",
     "Mourners traditionally tear an item of clothing, a practice called keriah, as an expression of grief.",
     "Mourners traditionally shave their heads completely, while clothing is left untouched.",
     "Keriah, tearing a garment, is the traditional mourning practice; head-shaving is not the standard custom."),
    ("lifecycle",
     "It's customary to place a small stone, rather than flowers, on a Jewish grave when visiting.",
     "It's customary to place fresh flowers, never stones, on a Jewish grave when visiting.",
     "Leaving a small stone on a grave is a well-known Jewish visiting custom; flowers are not the traditional choice."),

    # --- prayer ---
    ("prayer",
     "The Amidah, also called the Shemoneh Esrei ('eighteen'), is a central prayer traditionally recited while standing.",
     "The Amidah is traditionally recited while lying prostrate on the floor.",
     "'Amidah' literally means 'standing' in Hebrew, describing how the prayer is recited."),
    ("prayer",
     "Jewish prayer services traditionally include prayers recited while facing in the direction of Jerusalem.",
     "Jewish prayer services traditionally include prayers recited while facing due north, regardless of location.",
     "Traditional Jewish prayer is oriented toward Jerusalem, not a fixed compass direction like north."),
    ("prayer",
     "The Aleinu prayer is traditionally recited near the end of each of the three daily prayer services.",
     "The Aleinu prayer is traditionally recited only once a year, on Yom Kippur.",
     "Aleinu concludes each of the three daily services (morning, afternoon, evening), not just once a year."),

    # --- synagogue ---
    ("synagogue",
     "Many synagogues keep an eternal light, or ner tamid, continuously lit above or near the ark.",
     "Many synagogues keep a light lit only once a year, on Yom Kippur.",
     "The ner tamid ('eternal light') is meant to stay lit continuously, echoing a light kept burning in the ancient Temple."),

    # --- kashrut ---
    ("kashrut",
     "Kosher certification symbols appear on many mainstream packaged food products, even ones with no obvious link to Jewish dietary practice.",
     "Kosher certification symbols appear only on products sold in specialty Judaica or Israeli grocery stores.",
     "Kosher symbols are widespread on ordinary supermarket products in many countries, well beyond specialty stores."),
    ("kashrut",
     "Grape products like wine and grape juice often require special kosher supervision beyond standard kosher certification.",
     "Grape products are automatically kosher and never require any special supervision.",
     "Wine and grape juice have additional traditional handling requirements, unlike most other kosher foods."),
    ("kashrut",
     "Kosher land animals must both chew their cud and have fully split hooves, which is why pigs (which have split hooves but don't chew cud) are not kosher.",
     "Pigs are considered kosher because they have split hooves, regardless of whether they chew their cud.",
     "Both signs are required together; pigs meet only one of the two kosher criteria, so they are not kosher."),
    ("kashrut",
     "Shellfish such as shrimp, lobster, and clams are not kosher, because kosher sea creatures must have both fins and scales.",
     "Shellfish are kosher as long as they are cooked separately from meat.",
     "The kosher requirement for sea creatures is fins and scales; shellfish lack both, regardless of how they're cooked."),

    # --- food ---
    ("food",
     "Gefilte fish is a poached or baked dish traditionally made from ground fish, often served as a starter at Shabbat and holiday meals.",
     "Gefilte fish is a raw fish dish, similar to sushi, traditionally eaten on Yom Kippur.",
     "Gefilte fish is cooked, not raw, and is a Shabbat and holiday starter rather than a Yom Kippur food."),
    ("food",
     "Bagels are traditionally boiled before being baked, which gives them their dense, chewy texture.",
     "Bagels are traditionally deep-fried, similar to doughnuts, rather than baked.",
     "The distinctive boil-then-bake method, not frying, is what gives bagels their characteristic chew."),
    ("food",
     "Hamantaschen are triangular filled cookies traditionally eaten on Purim, said to resemble the villain Haman's hat.",
     "Hamantaschen are traditionally eaten on Hanukkah, shaped to resemble a dreidel.",
     "Hamantaschen are a Purim food tied to the Haman story, not a Hanukkah tradition."),
    ("food",
     "Schmaltz, rendered chicken or goose fat, was traditionally used in Ashkenazi Jewish cooking in place of butter, keeping meat and dairy separate.",
     "Schmaltz is a type of soft cheese traditionally used in Ashkenazi Jewish cooking.",
     "Schmaltz is a fat, not a cheese, and its use in place of butter is tied to the kosher separation of meat and dairy."),
    ("food",
     "Kugel is a baked casserole, often made from noodles or potatoes, commonly served on Shabbat.",
     "Kugel is a cold soup, traditionally served on Passover.",
     "Kugel is a baked casserole dish, most associated with Shabbat, not a soup."),
    ("food",
     "Kreplach are small dumplings, often filled with meat, traditionally eaten on certain occasions such as Purim and Yom Kippur eve.",
     "Kreplach are a type of unleavened cracker, traditionally eaten throughout Passover.",
     "Kreplach are dumplings, distinct from the unleavened matzah crackers eaten during Passover."),

    # --- history ---
    ("history",
     "Theodor Herzl, a founding figure of modern political Zionism, was a journalist who covered the Dreyfus Affair in France.",
     "Theodor Herzl was a 12th-century rabbi who led a Crusade-era community in Jerusalem.",
     "Herzl was a 19th-century Austro-Hungarian journalist and writer, not a medieval rabbi."),
    ("history",
     "The State of Israel declared independence on May 14, 1948.",
     "The State of Israel declared independence on May 14, 1967.",
     "Israel's declaration of independence was in 1948; 1967 is instead associated with the Six-Day War."),
    ("history",
     "Jerusalem is considered a holy city in Judaism, Christianity, and Islam.",
     "Jerusalem is considered holy only in Judaism and has no religious significance in Christianity or Islam.",
     "Jerusalem holds religious significance across all three Abrahamic faiths, not Judaism alone."),
    ("history",
     "The Western Wall is a remnant of the retaining wall that surrounded the Second Temple's courtyard, not the Temple building itself.",
     "The Western Wall is a remnant of the original First Temple building itself, built by King Solomon.",
     "The Western Wall supported the Temple Mount's courtyard; it predates neither the First Temple nor is it the Temple building itself."),
    ("history",
     "The Dead Sea Scrolls, ancient manuscripts including early copies of Hebrew Bible texts, were discovered in caves near the Dead Sea starting in 1947.",
     "The Dead Sea Scrolls were discovered inside the Western Wall in Jerusalem in 1920.",
     "The scrolls were found in caves near the Dead Sea (at Qumran), first in 1947, not inside the Western Wall."),
    ("history",
     "Masada, an ancient fortress in Israel, is associated with a first-century siege and resistance against Roman forces.",
     "Masada is a modern military base built in Israel in the 1980s.",
     "Masada is an ancient site tied to events in 73–74 CE, not a modern military installation."),

    # --- language ---
    ("language",
     "Modern Hebrew was revived as a spoken everyday language in the late 19th and early 20th centuries, largely credited to the efforts of Eliezer Ben-Yehuda.",
     "Modern Hebrew has been spoken as a majority daily language continuously for over 2,000 years without interruption.",
     "Hebrew was mainly a language of prayer and scholarship for centuries before its deliberate revival as an everyday spoken language."),
    ("language",
     "Ladino, sometimes called Judeo-Spanish, is a language historically spoken by Sephardic Jews, blending Old Spanish with Hebrew and other influences.",
     "Ladino is a language historically spoken only by Ashkenazi Jews in Eastern Europe.",
     "Ladino developed among Sephardic Jewish communities, distinct from Yiddish, which developed among Ashkenazi Jews."),
    ("language",
     "The Hebrew alphabet has 22 letters and is traditionally written and read from right to left.",
     "The Hebrew alphabet has 26 letters and is traditionally written and read from left to right.",
     "Hebrew has 22 letters and reads right to left, unlike English's 26 letters read left to right."),
    ("language",
     "The Yiddish-derived word 'chutzpah,' now used in English, generally means shameless audacity or boldness.",
     "The Yiddish-derived word 'chutzpah,' now used in English, generally means quiet humility.",
     "'Chutzpah' describes brazen nerve or audacity, essentially the opposite of humility."),

    # --- israel ---
    ("israel",
     "Drip irrigation technology, now used in agriculture worldwide, was significantly advanced and commercialized in Israel starting in the 1960s.",
     "Drip irrigation technology was invented and first commercialized in the Netherlands in the 1600s.",
     "Modern drip irrigation's development and commercialization is strongly associated with Israeli engineers and companies from the 1960s onward."),
    ("israel",
     "The navigation app Waze, later acquired by Google, was originally developed by a team in Israel.",
     "The navigation app Waze was originally developed by a team in Japan.",
     "Waze was founded by Israeli entrepreneurs and developed in Israel before its acquisition by Google."),
    ("israel",
     "Albert Einstein was offered the largely ceremonial presidency of Israel in 1952 and turned it down.",
     "Albert Einstein served as Israel's first president, from 1948 to 1952.",
     "Einstein was offered the presidency after Chaim Weizmann's death but declined, citing a lack of aptitude for the role; he never held the office."),
    ("israel",
     "The Israeli flag features a Star of David between two blue stripes, a design inspired by the traditional tallit (prayer shawl).",
     "The Israeli flag's blue stripes are meant to represent the sea and sky, with no connection to any Jewish religious item.",
     "The flag's stripes are explicitly modeled on the traditional blue-and-white stripes of a tallit."),
    ("israel",
     "The Hebrew University of Jerusalem and the Technion, two of Israel's leading universities, were both founded before the State of Israel itself in 1948.",
     "Both the Hebrew University of Jerusalem and the Technion were founded after 1948, as part of the new state's initial infrastructure.",
     "The Technion was founded in 1912 and Hebrew University in 1918, both decades before Israel's 1948 statehood."),
    ("israel",
     "Israel is home to the lowest point on Earth's land surface, along the shore of the Dead Sea.",
     "Israel is home to the highest point on Earth's land surface.",
     "The Dead Sea shore sits over 400 meters below sea level, the lowest point of dry land on the planet."),
    ("israel",
     "The Maccabiah Games, sometimes called the 'Jewish Olympics,' are a multi-sport event held in Israel roughly every four years.",
     "The Maccabiah Games are held in a rotating host country each time, similar to the actual Olympics.",
     "Unlike the Olympics, the Maccabiah Games are consistently held in Israel rather than rotating between host countries."),
    ("israel",
     "Israel's Independence Day, Yom HaAtzmaut, falls on a different Gregorian calendar date each year because it is set by the Hebrew calendar.",
     "Israel's Independence Day, Yom HaAtzmaut, falls on the same Gregorian calendar date every year.",
     "Because it's fixed to a Hebrew calendar date, Yom HaAtzmaut shifts relative to the Gregorian calendar from year to year."),
    ("israel",
     "Yom HaShoah is an official day of remembrance for the roughly six million Jewish victims of the Holocaust.",
     "Yom HaShoah is a day celebrating the founding of the State of Israel.",
     "Yom HaShoah is a solemn remembrance day for Holocaust victims; Israel's founding is instead marked by Yom HaAtzmaut."),

    # --- people ---
    ("people",
     "Albert Einstein, who developed the theory of relativity, was born to a Jewish family in Ulm, Germany.",
     "Albert Einstein, who developed the theory of relativity, was born to a Jewish family in Jerusalem.",
     "Einstein was born in Ulm, Germany, in 1879, not in Jerusalem."),
    ("people",
     "Maimonides (Rambam), a 12th-century rabbi and philosopher, authored the Mishneh Torah, a major code of Jewish law.",
     "Maimonides authored the Talmud itself, in the 3rd century CE.",
     "Maimonides lived centuries after the Talmud was compiled; his major legal work is the Mishneh Torah."),
    ("people",
     "Maimonides formulated a widely referenced list of Thirteen Principles of Jewish faith.",
     "Maimonides formulated the Ten Commandments, later revised from an original list of twenty.",
     "The Ten Commandments appear in the Torah itself; Maimonides is instead known for his own Thirteen Principles of faith."),
]
