# Batch 5: ~47 new true/false pairs, continuing the laws/customs emphasis,
# reaching into agricultural law, calendar mechanics, lifecycle milestones
# not yet covered, and a handful of history/language/people facts.

PAIRS = [
    # --- kashrut ---
    ("kashrut",
     "Ashkenazi custom traditionally avoids kitniyot (legumes, rice, and corn) on Passover, while Sephardic custom generally does not.",
     "Both Ashkenazi and Sephardic custom traditionally treat kitniyot (legumes, rice, and corn) identically to chametz, forbidden everywhere on Passover.",
     "Kitniyot restrictions are an Ashkenazi custom, not a universal Jewish law; Sephardic communities generally don't follow it."),
    ("kashrut",
     "Pas Yisrael is a stricter kosher standard some observe, requiring that bread be baked with some Jewish involvement in the process.",
     "Pas Yisrael is a kosher standard requiring that bread contain no wheat at all, only alternative grains.",
     "Pas Yisrael concerns who is involved in baking, not which grains are used."),
    ("kashrut",
     "Cheese sometimes requires special kosher supervision because the rennet used to make it can come from a non-kosher animal source.",
     "Cheese never requires any special kosher supervision beyond confirming it's a dairy product.",
     "Rennet's animal source is a real kosher concern for cheese, beyond simply being a dairy product."),
    ("kashrut",
     "Kosher land mammals include cows, sheep, goats, and deer, since they chew their cud and have split hooves.",
     "Kosher land mammals include cows, sheep, goats, and rabbits, since they chew their cud and have split hooves.",
     "Rabbits are specifically named in the Torah as appearing to chew their cud but lacking split hooves, making them not kosher despite the resemblance."),
    ("kashrut",
     "Multiple kosher certification agencies exist, each with its own distinct symbol, rather than one single universal kosher symbol.",
     "There is exactly one official kosher certification symbol recognized worldwide, issued by a single global authority.",
     "Kosher certification is decentralized, with many different agencies and symbols (such as OU, OK, and Star-K) rather than one universal mark."),
    ("kashrut",
     "Sturgeon's kosher status is debated among rabbinic authorities, since its scales are tiny and embedded rather than clearly visible.",
     "Sturgeon's kosher status has never been debated, since all fish with any scales at all are unanimously considered kosher.",
     "Sturgeon (the source of most caviar) is a genuinely disputed case precisely because of its unusual scales."),
    ("kashrut",
     "'Kosher salt' gets its name from its traditional use in the koshering (salting) process for meat, not because the salt itself requires certification.",
     "'Kosher salt' gets its name because it is the only type of salt considered acceptable under Jewish dietary law.",
     "Most salt is inherently kosher; 'kosher salt' refers to a coarse-grained style suited to drawing out blood from meat."),

    # --- shabbat ---
    ("shabbat",
     "Techum Shabbat is a traditional limit, roughly 2,000 cubits, on how far one may walk outside a town's boundary on Shabbat.",
     "Techum Shabbat is a traditional rule requiring one to walk at least 2,000 cubits outside a town's boundary on Shabbat.",
     "Techum Shabbat sets a maximum walking distance, not a minimum requirement."),
    ("shabbat",
     "It's traditional to wear nicer, special clothing on Shabbat, distinct from ordinary weekday clothes.",
     "It's traditional to wear the plainest, most worn-out clothing available on Shabbat, to emphasize simplicity.",
     "Shabbat is traditionally honored with finer clothing, not deliberately worn-out garments."),
    ("shabbat",
     "Eruv Tavshilin is a symbolic food-preparation custom performed before a holiday that falls right before Shabbat, permitting cooking for Shabbat during the holiday.",
     "Eruv Tavshilin is a symbolic custom performed only on ordinary Fridays, unrelated to any holiday scheduling.",
     "Eruv Tavshilin specifically addresses the case of a holiday falling just before Shabbat, not an ordinary Friday."),
    ("shabbat",
     "Kiddush Levana, a blessing over the new moon, is traditionally recited outdoors within roughly the first two weeks of the Hebrew month.",
     "Kiddush Levana, a blessing over the new moon, is traditionally recited indoors only once a year, on Yom Kippur.",
     "Kiddush Levana is a monthly outdoor practice tied to the moon's visibility, not a once-a-year, indoor, Yom Kippur custom."),
    ("shabbat",
     "Carrying an item from a private domain to a public one is one of the 39 traditionally forbidden categories of Shabbat labor.",
     "None of the 39 traditionally forbidden categories of Shabbat labor relate to carrying items between different types of spaces.",
     "Carrying between domains (hotzaah) is specifically one of the 39 melachot, which is why an eruv exists to work around it."),

    # --- holidays ---
    ("holidays",
     "Many Jewish holidays are traditionally observed for an extra day outside Israel, a practice called Yom Tov Sheni shel Galuyot.",
     "Every Jewish holiday is traditionally observed for exactly the same number of days everywhere in the world, with no exceptions.",
     "Several holidays traditionally gain an additional day in the diaspora, a longstanding practice with calendar-related historical roots."),
    ("holidays",
     "Each night of Hanukkah, a new candle is traditionally added to the chanukiah from right to left, but the candles are lit starting with that night's newest candle, left to right.",
     "Each night of Hanukkah, a new candle is traditionally added to the chanukiah from left to right, and the candles are lit starting with the oldest candle, right to left.",
     "Candles are added right-to-left but lit left-to-right, starting with the newest candle each night."),
    ("holidays",
     "Hanukkah candles are traditionally placed in a doorway or window facing the street, to publicize the miracle.",
     "Hanukkah candles are traditionally kept hidden in a closed cabinet, so as not to draw attention to the holiday.",
     "Pirsumei nisa, publicizing the miracle, is a core reason Hanukkah candles are placed visibly facing outward, not hidden."),
    ("holidays",
     "Birkat HaChama, a blessing over the sun, is traditionally recited only once every 28 years.",
     "Birkat HaChama, a blessing over the sun, is traditionally recited every single morning as part of daily prayer.",
     "Birkat HaChama is tied to a rare 28-year solar cycle calculation, making it one of the least frequently recited traditional blessings."),
    ("holidays",
     "Tu B'Av is a minor holiday historically associated with matchmaking, sometimes described as a Jewish 'Valentine's Day.'",
     "Tu B'Av is a major fast day historically associated with mourning the destruction of the Temples.",
     "Tu B'Av is a joyous minor holiday tied to matchmaking traditions, not a fast day (that description fits Tisha B'Av instead)."),
    ("holidays",
     "Kaporos (or Kapparot), a pre-Yom Kippur custom observed in some communities, symbolically transfers a person's sins, traditionally using a chicken or money.",
     "Kaporos is a post-Yom Kippur custom observed in some communities, involving a celebratory meal with no symbolic elements.",
     "Kaporos traditionally happens before Yom Kippur and centers on a specific symbolic act, not just an ordinary meal."),
    ("holidays",
     "The Three Weeks between the 17th of Tammuz and Tisha B'Av mark a traditional period of mourning for the destruction of the Temples.",
     "The Three Weeks between the 17th of Tammuz and Tisha B'Av mark a traditional period of celebration for the Temples' original construction.",
     "This period is traditionally one of mourning, leading up to Tisha B'Av, not a celebration."),
    ("holidays",
     "The fast of the 17th of Tammuz traditionally marks the breach of Jerusalem's walls before the Temple's destruction.",
     "The fast of the 17th of Tammuz traditionally marks the rededication of the Temple after the Maccabean victory.",
     "That rededication is instead what Hanukkah commemorates; the 17th of Tammuz marks an earlier, mournful event."),
    ("holidays",
     "Purim traditionally includes a custom of wearing costumes and masks.",
     "Purim traditionally includes a custom of maintaining complete silence throughout the day.",
     "Costumes and masks are a well-known Purim custom, not silence."),

    # --- ritual_objects ---
    ("ritual_objects",
     "Torah scroll cases vary by community: some Sephardic communities use a rigid case called a tik, while Ashkenazi communities typically use a soft fabric mantle.",
     "Torah scroll cases are identical in every Jewish community worldwide, with no variation in style.",
     "Torah scroll housing styles genuinely differ by community, from rigid Sephardic cases to soft Ashkenazi mantles."),
    ("ritual_objects",
     "Rimonim are decorative silver finials that traditionally sit atop a Torah scroll's wooden rollers.",
     "Rimonim are decorative silver finials that traditionally sit atop a chanukiah's candle branches.",
     "Rimonim adorn Torah scroll rollers, not a chanukiah."),
    ("ritual_objects",
     "A parochet is a curtain that traditionally covers or hangs in front of a synagogue's Torah ark.",
     "A parochet is a curtain that traditionally covers the bimah where the Torah is read.",
     "A parochet is specifically associated with the ark, not the bimah."),

    # --- lifecycle ---
    ("lifecycle",
     "Upsherin is a custom observed in some communities involving a boy's first haircut, typically around age three.",
     "Upsherin is a custom observed in some communities involving a girl's first pair of earrings, typically around age three.",
     "Upsherin specifically refers to a first haircut custom, not an earring custom."),
    ("lifecycle",
     "An aufruf is a custom of calling the groom up to the Torah on the Shabbat before his wedding.",
     "An aufruf is a custom of calling the bride up to the Torah on the morning of her wedding day.",
     "The aufruf custom traditionally involves the groom, on the Shabbat beforehand, not the bride on the wedding day itself."),
    ("lifecycle",
     "Tenaim is a traditional engagement document or ceremony, distinct from the ketubah, typically held before the wedding itself.",
     "Tenaim is another name for the ketubah, the marriage contract read during the wedding ceremony.",
     "Tenaim and the ketubah are two distinct documents, tied to different stages of the marriage process."),
    ("lifecycle",
     "Shloshim is a 30-day mourning period following shiva, less intensive in its restrictions than the first seven days.",
     "Shloshim is a 30-day mourning period that comes before shiva, more intensive in its restrictions than the seven days that follow.",
     "Shloshim follows shiva and eases some of its restrictions, rather than preceding and intensifying them."),
    ("lifecycle",
     "Kaddish for a deceased parent is traditionally recited for 11 months, not a full year, after death.",
     "Kaddish for a deceased parent is traditionally recited for exactly 12 months, a full year, after death.",
     "The traditional practice specifically stops just short of a full year, at 11 months."),
    ("lifecycle",
     "An unveiling is a ceremony dedicating a tombstone, often held around a year after death in some communities.",
     "An unveiling is a ceremony dedicating a tombstone, traditionally held on the same day as the funeral itself.",
     "Unveilings are typically held some time after the funeral, commonly around the one-year mark, not on the funeral day."),

    # --- prayer ---
    ("prayer",
     "Shehecheyanu is a blessing traditionally recited to mark new or first-time experiences, including many holidays.",
     "Shehecheyanu is a blessing traditionally recited only at funerals, to mark the end of a life.",
     "Shehecheyanu celebrates new beginnings and experiences, the opposite of a funeral-specific blessing."),
    ("prayer",
     "Hallel, a set of psalms of praise, is traditionally recited on many joyous holidays, but not on Rosh Hashanah or Yom Kippur.",
     "Hallel, a set of psalms of praise, is traditionally recited only on Rosh Hashanah and Yom Kippur, and on no other holiday.",
     "Hallel is skipped specifically on Rosh Hashanah and Yom Kippur, while being recited on many other festive occasions."),
    ("prayer",
     "Modeh Ani is a short prayer traditionally said immediately upon waking, before even washing one's hands.",
     "Modeh Ani is a short prayer traditionally said only right before going to sleep at night.",
     "Modeh Ani is specifically a first-thing-in-the-morning prayer, not a nighttime one."),
    ("prayer",
     "Netilat Yadayim, a ritual hand-washing with a blessing, is traditionally performed before eating bread.",
     "Netilat Yadayim, a ritual hand-washing with a blessing, is traditionally performed only after eating bread.",
     "This hand-washing traditionally happens before the meal, ahead of the blessing over bread."),

    # --- synagogue ---
    ("synagogue",
     "A minyan of ten adults can traditionally pray together anywhere; a dedicated synagogue building isn't technically required.",
     "A minyan can traditionally only pray together inside a synagogue building that has been specifically consecrated by a rabbi.",
     "A minyan's validity depends on having ten adults present, not on the location being a consecrated building."),
    ("synagogue",
     "A rabbi's traditional role centers on teaching and expertise in Jewish law, rather than special ordination required to lead prayer.",
     "A rabbi's traditional role requires special ordination without which no Jewish prayer service can take place.",
     "Any knowledgeable adult can traditionally lead prayer; a rabbi's distinct role is centered on legal and educational authority."),

    # --- texts ---
    ("texts",
     "The Haftarah is a reading from the Prophets that traditionally follows the Torah reading on Shabbat, thematically linked to it.",
     "The Haftarah is a reading from the Torah that traditionally replaces the regular Torah reading twice a year.",
     "The Haftarah comes from the Prophets (Nevi'im), not the Torah, and supplements rather than replaces the Torah reading."),
    ("texts",
     "Targum refers to ancient Aramaic translations of the Torah.",
     "Targum refers to ancient Greek translations of the Torah.",
     "Targum specifically denotes Aramaic translations; a well-known ancient Greek translation is called the Septuagint instead."),
    ("texts",
     "A machzor is a specific prayer book used for holidays, distinct from the everyday siddur.",
     "A machzor and a siddur are simply two different names for the exact same prayer book.",
     "A machzor is a holiday-specific prayer book, separate from the standard everyday siddur."),

    # --- history ---
    ("history",
     "The Babylonian exile followed the First Temple's destruction in 586 BCE; Cyrus the Great later permitted the Jewish return.",
     "The Babylonian exile followed the Second Temple's destruction in 70 CE; Julius Caesar later permitted the Jewish return.",
     "The Babylonian exile is tied to the First Temple's destruction and Cyrus the Great's later decree, not the Second Temple or Julius Caesar."),
    ("history",
     "The Bar Kochba revolt was a Jewish uprising against Roman rule from 132 to 135 CE.",
     "The Bar Kochba revolt was a Jewish uprising against Babylonian rule in the 6th century BCE.",
     "Bar Kochba led a revolt against Rome in the 2nd century CE, centuries after the Babylonian period."),
    ("history",
     "A 'Golden Age' of Jewish culture flourished in Muslim Spain (Al-Andalus), producing notable poets and philosophers.",
     "A 'Golden Age' of Jewish culture is traditionally associated with 19th-century Russia, producing notable poets and philosophers.",
     "This particular 'Golden Age' refers to medieval Muslim Spain, not 19th-century Russia."),
    ("history",
     "Jews were expelled from Spain in 1492.",
     "Jews were expelled from Spain in 1792.",
     "The Spanish expulsion took place in 1492, three centuries earlier than the alternate date."),

    # --- people ---
    ("people",
     "Hillel is credited with the teaching 'That which is hateful to you, do not do to your fellow,' said to summarize the Torah 'while standing on one foot.'",
     "Hillel is credited with a teaching that the entire Torah could not be summarized in any short form, no matter how it was attempted.",
     "The famous 'standing on one foot' story has Hillel offering exactly this kind of concise summary, not refusing to give one."),
    ("people",
     "Rabbi Akiva, a leading Mishnaic-era sage, supported the Bar Kochba revolt and was executed by Roman authorities.",
     "Rabbi Akiva, a leading Mishnaic-era sage, opposed all forms of resistance to Rome and died peacefully of old age.",
     "Tradition holds that Akiva supported Bar Kochba's revolt and was killed by the Romans, not that he died peacefully."),

    # --- language ---
    ("language",
     "Gematria is a traditional system that assigns numeric values to Hebrew letters, used in interpretation and wordplay.",
     "Gematria is a traditional system that assigns musical notes to Hebrew letters, used for composing prayer melodies.",
     "Gematria concerns numeric values, not musical notation."),
    ("language",
     "'Mazel tov' literally means something closer to 'good constellation' or 'good luck,' commonly used to mean 'congratulations.'",
     "'Mazel tov' literally means 'safe travels,' commonly used as a farewell when someone leaves on a trip.",
     "'Mazel tov' relates to luck/fortune, used to mean congratulations, not as a travel farewell."),
]
